// Code generated by ent, DO NOT EDIT.

package geofence

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/logistics-service/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldEQ(FieldTenantID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldEQ(FieldName, v))
}

// ZoneType applies equality check predicate on the "zone_type" field. It's identical to ZoneTypeEQ.
func ZoneType(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldEQ(FieldZoneType, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldEQ(FieldStatus, v))
}

// Color applies equality check predicate on the "color" field. It's identical to ColorEQ.
func Color(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldEQ(FieldColor, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uuid.UUID) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uuid.UUID) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uuid.UUID) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uuid.UUID) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldLTE(FieldTenantID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldContainsFold(FieldName, v))
}

// ZoneTypeEQ applies the EQ predicate on the "zone_type" field.
func ZoneTypeEQ(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldEQ(FieldZoneType, v))
}

// ZoneTypeNEQ applies the NEQ predicate on the "zone_type" field.
func ZoneTypeNEQ(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldNEQ(FieldZoneType, v))
}

// ZoneTypeIn applies the In predicate on the "zone_type" field.
func ZoneTypeIn(vs ...string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldIn(FieldZoneType, vs...))
}

// ZoneTypeNotIn applies the NotIn predicate on the "zone_type" field.
func ZoneTypeNotIn(vs ...string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldNotIn(FieldZoneType, vs...))
}

// ZoneTypeGT applies the GT predicate on the "zone_type" field.
func ZoneTypeGT(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldGT(FieldZoneType, v))
}

// ZoneTypeGTE applies the GTE predicate on the "zone_type" field.
func ZoneTypeGTE(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldGTE(FieldZoneType, v))
}

// ZoneTypeLT applies the LT predicate on the "zone_type" field.
func ZoneTypeLT(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldLT(FieldZoneType, v))
}

// ZoneTypeLTE applies the LTE predicate on the "zone_type" field.
func ZoneTypeLTE(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldLTE(FieldZoneType, v))
}

// ZoneTypeContains applies the Contains predicate on the "zone_type" field.
func ZoneTypeContains(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldContains(FieldZoneType, v))
}

// ZoneTypeHasPrefix applies the HasPrefix predicate on the "zone_type" field.
func ZoneTypeHasPrefix(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldHasPrefix(FieldZoneType, v))
}

// ZoneTypeHasSuffix applies the HasSuffix predicate on the "zone_type" field.
func ZoneTypeHasSuffix(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldHasSuffix(FieldZoneType, v))
}

// ZoneTypeEqualFold applies the EqualFold predicate on the "zone_type" field.
func ZoneTypeEqualFold(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldEqualFold(FieldZoneType, v))
}

// ZoneTypeContainsFold applies the ContainsFold predicate on the "zone_type" field.
func ZoneTypeContainsFold(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldContainsFold(FieldZoneType, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldContainsFold(FieldStatus, v))
}

// ColorEQ applies the EQ predicate on the "color" field.
func ColorEQ(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldEQ(FieldColor, v))
}

// ColorNEQ applies the NEQ predicate on the "color" field.
func ColorNEQ(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldNEQ(FieldColor, v))
}

// ColorIn applies the In predicate on the "color" field.
func ColorIn(vs ...string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldIn(FieldColor, vs...))
}

// ColorNotIn applies the NotIn predicate on the "color" field.
func ColorNotIn(vs ...string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldNotIn(FieldColor, vs...))
}

// ColorGT applies the GT predicate on the "color" field.
func ColorGT(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldGT(FieldColor, v))
}

// ColorGTE applies the GTE predicate on the "color" field.
func ColorGTE(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldGTE(FieldColor, v))
}

// ColorLT applies the LT predicate on the "color" field.
func ColorLT(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldLT(FieldColor, v))
}

// ColorLTE applies the LTE predicate on the "color" field.
func ColorLTE(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldLTE(FieldColor, v))
}

// ColorContains applies the Contains predicate on the "color" field.
func ColorContains(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldContains(FieldColor, v))
}

// ColorHasPrefix applies the HasPrefix predicate on the "color" field.
func ColorHasPrefix(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldHasPrefix(FieldColor, v))
}

// ColorHasSuffix applies the HasSuffix predicate on the "color" field.
func ColorHasSuffix(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldHasSuffix(FieldColor, v))
}

// ColorIsNil applies the IsNil predicate on the "color" field.
func ColorIsNil() predicate.GeoFence {
	return predicate.GeoFence(sql.FieldIsNull(FieldColor))
}

// ColorNotNil applies the NotNil predicate on the "color" field.
func ColorNotNil() predicate.GeoFence {
	return predicate.GeoFence(sql.FieldNotNull(FieldColor))
}

// ColorEqualFold applies the EqualFold predicate on the "color" field.
func ColorEqualFold(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldEqualFold(FieldColor, v))
}

// ColorContainsFold applies the ContainsFold predicate on the "color" field.
func ColorContainsFold(v string) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldContainsFold(FieldColor, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.GeoFence {
	return predicate.GeoFence(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.GeoFence {
	return predicate.GeoFence(sql.FieldNotNull(FieldMetadata))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GeoFence {
	return predicate.GeoFence(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GeoFence) predicate.GeoFence {
	return predicate.GeoFence(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GeoFence) predicate.GeoFence {
	return predicate.GeoFence(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GeoFence) predicate.GeoFence {
	return predicate.GeoFence(sql.NotPredicates(p))
}
