// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/logistics-service/internal/ent/carrierpartner"
	"github.com/google/uuid"
)

// CarrierPartnerCreate is the builder for creating a CarrierPartner entity.
type CarrierPartnerCreate struct {
	config
	mutation *CarrierPartnerMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (_c *CarrierPartnerCreate) SetTenantID(v uuid.UUID) *CarrierPartnerCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *CarrierPartnerCreate) SetName(v string) *CarrierPartnerCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetProviderCode sets the "provider_code" field.
func (_c *CarrierPartnerCreate) SetProviderCode(v string) *CarrierPartnerCreate {
	_c.mutation.SetProviderCode(v)
	return _c
}

// SetAPICredentialsJSON sets the "api_credentials_json" field.
func (_c *CarrierPartnerCreate) SetAPICredentialsJSON(v map[string]interface{}) *CarrierPartnerCreate {
	_c.mutation.SetAPICredentialsJSON(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *CarrierPartnerCreate) SetStatus(v string) *CarrierPartnerCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *CarrierPartnerCreate) SetNillableStatus(v *string) *CarrierPartnerCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *CarrierPartnerCreate) SetMetadata(v map[string]interface{}) *CarrierPartnerCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CarrierPartnerCreate) SetCreatedAt(v time.Time) *CarrierPartnerCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CarrierPartnerCreate) SetNillableCreatedAt(v *time.Time) *CarrierPartnerCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CarrierPartnerCreate) SetUpdatedAt(v time.Time) *CarrierPartnerCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CarrierPartnerCreate) SetNillableUpdatedAt(v *time.Time) *CarrierPartnerCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CarrierPartnerCreate) SetID(v uuid.UUID) *CarrierPartnerCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *CarrierPartnerCreate) SetNillableID(v *uuid.UUID) *CarrierPartnerCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the CarrierPartnerMutation object of the builder.
func (_c *CarrierPartnerCreate) Mutation() *CarrierPartnerMutation {
	return _c.mutation
}

// Save creates the CarrierPartner in the database.
func (_c *CarrierPartnerCreate) Save(ctx context.Context) (*CarrierPartner, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CarrierPartnerCreate) SaveX(ctx context.Context) *CarrierPartner {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CarrierPartnerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CarrierPartnerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CarrierPartnerCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := carrierpartner.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		v := carrierpartner.DefaultMetadata
		_c.mutation.SetMetadata(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := carrierpartner.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := carrierpartner.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := carrierpartner.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CarrierPartnerCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "CarrierPartner.tenant_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "CarrierPartner.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := carrierpartner.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CarrierPartner.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProviderCode(); !ok {
		return &ValidationError{Name: "provider_code", err: errors.New(`ent: missing required field "CarrierPartner.provider_code"`)}
	}
	if v, ok := _c.mutation.ProviderCode(); ok {
		if err := carrierpartner.ProviderCodeValidator(v); err != nil {
			return &ValidationError{Name: "provider_code", err: fmt.Errorf(`ent: validator failed for field "CarrierPartner.provider_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "CarrierPartner.status"`)}
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		return &ValidationError{Name: "metadata", err: errors.New(`ent: missing required field "CarrierPartner.metadata"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CarrierPartner.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CarrierPartner.updated_at"`)}
	}
	return nil
}

func (_c *CarrierPartnerCreate) sqlSave(ctx context.Context) (*CarrierPartner, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CarrierPartnerCreate) createSpec() (*CarrierPartner, *sqlgraph.CreateSpec) {
	var (
		_node = &CarrierPartner{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(carrierpartner.Table, sqlgraph.NewFieldSpec(carrierpartner.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(carrierpartner.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(carrierpartner.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.ProviderCode(); ok {
		_spec.SetField(carrierpartner.FieldProviderCode, field.TypeString, value)
		_node.ProviderCode = value
	}
	if value, ok := _c.mutation.APICredentialsJSON(); ok {
		_spec.SetField(carrierpartner.FieldAPICredentialsJSON, field.TypeJSON, value)
		_node.APICredentialsJSON = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(carrierpartner.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(carrierpartner.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(carrierpartner.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(carrierpartner.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CarrierPartner.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CarrierPartnerUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *CarrierPartnerCreate) OnConflict(opts ...sql.ConflictOption) *CarrierPartnerUpsertOne {
	_c.conflict = opts
	return &CarrierPartnerUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CarrierPartner.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CarrierPartnerCreate) OnConflictColumns(columns ...string) *CarrierPartnerUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CarrierPartnerUpsertOne{
		create: _c,
	}
}

type (
	// CarrierPartnerUpsertOne is the builder for "upsert"-ing
	//  one CarrierPartner node.
	CarrierPartnerUpsertOne struct {
		create *CarrierPartnerCreate
	}

	// CarrierPartnerUpsert is the "OnConflict" setter.
	CarrierPartnerUpsert struct {
		*sql.UpdateSet
	}
)

// SetTenantID sets the "tenant_id" field.
func (u *CarrierPartnerUpsert) SetTenantID(v uuid.UUID) *CarrierPartnerUpsert {
	u.Set(carrierpartner.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *CarrierPartnerUpsert) UpdateTenantID() *CarrierPartnerUpsert {
	u.SetExcluded(carrierpartner.FieldTenantID)
	return u
}

// SetName sets the "name" field.
func (u *CarrierPartnerUpsert) SetName(v string) *CarrierPartnerUpsert {
	u.Set(carrierpartner.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CarrierPartnerUpsert) UpdateName() *CarrierPartnerUpsert {
	u.SetExcluded(carrierpartner.FieldName)
	return u
}

// SetProviderCode sets the "provider_code" field.
func (u *CarrierPartnerUpsert) SetProviderCode(v string) *CarrierPartnerUpsert {
	u.Set(carrierpartner.FieldProviderCode, v)
	return u
}

// UpdateProviderCode sets the "provider_code" field to the value that was provided on create.
func (u *CarrierPartnerUpsert) UpdateProviderCode() *CarrierPartnerUpsert {
	u.SetExcluded(carrierpartner.FieldProviderCode)
	return u
}

// SetAPICredentialsJSON sets the "api_credentials_json" field.
func (u *CarrierPartnerUpsert) SetAPICredentialsJSON(v map[string]interface{}) *CarrierPartnerUpsert {
	u.Set(carrierpartner.FieldAPICredentialsJSON, v)
	return u
}

// UpdateAPICredentialsJSON sets the "api_credentials_json" field to the value that was provided on create.
func (u *CarrierPartnerUpsert) UpdateAPICredentialsJSON() *CarrierPartnerUpsert {
	u.SetExcluded(carrierpartner.FieldAPICredentialsJSON)
	return u
}

// ClearAPICredentialsJSON clears the value of the "api_credentials_json" field.
func (u *CarrierPartnerUpsert) ClearAPICredentialsJSON() *CarrierPartnerUpsert {
	u.SetNull(carrierpartner.FieldAPICredentialsJSON)
	return u
}

// SetStatus sets the "status" field.
func (u *CarrierPartnerUpsert) SetStatus(v string) *CarrierPartnerUpsert {
	u.Set(carrierpartner.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CarrierPartnerUpsert) UpdateStatus() *CarrierPartnerUpsert {
	u.SetExcluded(carrierpartner.FieldStatus)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *CarrierPartnerUpsert) SetMetadata(v map[string]interface{}) *CarrierPartnerUpsert {
	u.Set(carrierpartner.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *CarrierPartnerUpsert) UpdateMetadata() *CarrierPartnerUpsert {
	u.SetExcluded(carrierpartner.FieldMetadata)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CarrierPartnerUpsert) SetUpdatedAt(v time.Time) *CarrierPartnerUpsert {
	u.Set(carrierpartner.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CarrierPartnerUpsert) UpdateUpdatedAt() *CarrierPartnerUpsert {
	u.SetExcluded(carrierpartner.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.CarrierPartner.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(carrierpartner.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CarrierPartnerUpsertOne) UpdateNewValues() *CarrierPartnerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(carrierpartner.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(carrierpartner.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CarrierPartner.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CarrierPartnerUpsertOne) Ignore() *CarrierPartnerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CarrierPartnerUpsertOne) DoNothing() *CarrierPartnerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CarrierPartnerCreate.OnConflict
// documentation for more info.
func (u *CarrierPartnerUpsertOne) Update(set func(*CarrierPartnerUpsert)) *CarrierPartnerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CarrierPartnerUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *CarrierPartnerUpsertOne) SetTenantID(v uuid.UUID) *CarrierPartnerUpsertOne {
	return u.Update(func(s *CarrierPartnerUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *CarrierPartnerUpsertOne) UpdateTenantID() *CarrierPartnerUpsertOne {
	return u.Update(func(s *CarrierPartnerUpsert) {
		s.UpdateTenantID()
	})
}

// SetName sets the "name" field.
func (u *CarrierPartnerUpsertOne) SetName(v string) *CarrierPartnerUpsertOne {
	return u.Update(func(s *CarrierPartnerUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CarrierPartnerUpsertOne) UpdateName() *CarrierPartnerUpsertOne {
	return u.Update(func(s *CarrierPartnerUpsert) {
		s.UpdateName()
	})
}

// SetProviderCode sets the "provider_code" field.
func (u *CarrierPartnerUpsertOne) SetProviderCode(v string) *CarrierPartnerUpsertOne {
	return u.Update(func(s *CarrierPartnerUpsert) {
		s.SetProviderCode(v)
	})
}

// UpdateProviderCode sets the "provider_code" field to the value that was provided on create.
func (u *CarrierPartnerUpsertOne) UpdateProviderCode() *CarrierPartnerUpsertOne {
	return u.Update(func(s *CarrierPartnerUpsert) {
		s.UpdateProviderCode()
	})
}

// SetAPICredentialsJSON sets the "api_credentials_json" field.
func (u *CarrierPartnerUpsertOne) SetAPICredentialsJSON(v map[string]interface{}) *CarrierPartnerUpsertOne {
	return u.Update(func(s *CarrierPartnerUpsert) {
		s.SetAPICredentialsJSON(v)
	})
}

// UpdateAPICredentialsJSON sets the "api_credentials_json" field to the value that was provided on create.
func (u *CarrierPartnerUpsertOne) UpdateAPICredentialsJSON() *CarrierPartnerUpsertOne {
	return u.Update(func(s *CarrierPartnerUpsert) {
		s.UpdateAPICredentialsJSON()
	})
}

// ClearAPICredentialsJSON clears the value of the "api_credentials_json" field.
func (u *CarrierPartnerUpsertOne) ClearAPICredentialsJSON() *CarrierPartnerUpsertOne {
	return u.Update(func(s *CarrierPartnerUpsert) {
		s.ClearAPICredentialsJSON()
	})
}

// SetStatus sets the "status" field.
func (u *CarrierPartnerUpsertOne) SetStatus(v string) *CarrierPartnerUpsertOne {
	return u.Update(func(s *CarrierPartnerUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CarrierPartnerUpsertOne) UpdateStatus() *CarrierPartnerUpsertOne {
	return u.Update(func(s *CarrierPartnerUpsert) {
		s.UpdateStatus()
	})
}

// SetMetadata sets the "metadata" field.
func (u *CarrierPartnerUpsertOne) SetMetadata(v map[string]interface{}) *CarrierPartnerUpsertOne {
	return u.Update(func(s *CarrierPartnerUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *CarrierPartnerUpsertOne) UpdateMetadata() *CarrierPartnerUpsertOne {
	return u.Update(func(s *CarrierPartnerUpsert) {
		s.UpdateMetadata()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CarrierPartnerUpsertOne) SetUpdatedAt(v time.Time) *CarrierPartnerUpsertOne {
	return u.Update(func(s *CarrierPartnerUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CarrierPartnerUpsertOne) UpdateUpdatedAt() *CarrierPartnerUpsertOne {
	return u.Update(func(s *CarrierPartnerUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CarrierPartnerUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CarrierPartnerCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CarrierPartnerUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CarrierPartnerUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: CarrierPartnerUpsertOne.ID is not supported by MySQL driver. Use CarrierPartnerUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CarrierPartnerUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CarrierPartnerCreateBulk is the builder for creating many CarrierPartner entities in bulk.
type CarrierPartnerCreateBulk struct {
	config
	err      error
	builders []*CarrierPartnerCreate
	conflict []sql.ConflictOption
}

// Save creates the CarrierPartner entities in the database.
func (_c *CarrierPartnerCreateBulk) Save(ctx context.Context) ([]*CarrierPartner, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CarrierPartner, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CarrierPartnerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CarrierPartnerCreateBulk) SaveX(ctx context.Context) []*CarrierPartner {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CarrierPartnerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CarrierPartnerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CarrierPartner.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CarrierPartnerUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *CarrierPartnerCreateBulk) OnConflict(opts ...sql.ConflictOption) *CarrierPartnerUpsertBulk {
	_c.conflict = opts
	return &CarrierPartnerUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CarrierPartner.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CarrierPartnerCreateBulk) OnConflictColumns(columns ...string) *CarrierPartnerUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CarrierPartnerUpsertBulk{
		create: _c,
	}
}

// CarrierPartnerUpsertBulk is the builder for "upsert"-ing
// a bulk of CarrierPartner nodes.
type CarrierPartnerUpsertBulk struct {
	create *CarrierPartnerCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CarrierPartner.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(carrierpartner.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CarrierPartnerUpsertBulk) UpdateNewValues() *CarrierPartnerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(carrierpartner.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(carrierpartner.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CarrierPartner.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CarrierPartnerUpsertBulk) Ignore() *CarrierPartnerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CarrierPartnerUpsertBulk) DoNothing() *CarrierPartnerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CarrierPartnerCreateBulk.OnConflict
// documentation for more info.
func (u *CarrierPartnerUpsertBulk) Update(set func(*CarrierPartnerUpsert)) *CarrierPartnerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CarrierPartnerUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *CarrierPartnerUpsertBulk) SetTenantID(v uuid.UUID) *CarrierPartnerUpsertBulk {
	return u.Update(func(s *CarrierPartnerUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *CarrierPartnerUpsertBulk) UpdateTenantID() *CarrierPartnerUpsertBulk {
	return u.Update(func(s *CarrierPartnerUpsert) {
		s.UpdateTenantID()
	})
}

// SetName sets the "name" field.
func (u *CarrierPartnerUpsertBulk) SetName(v string) *CarrierPartnerUpsertBulk {
	return u.Update(func(s *CarrierPartnerUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CarrierPartnerUpsertBulk) UpdateName() *CarrierPartnerUpsertBulk {
	return u.Update(func(s *CarrierPartnerUpsert) {
		s.UpdateName()
	})
}

// SetProviderCode sets the "provider_code" field.
func (u *CarrierPartnerUpsertBulk) SetProviderCode(v string) *CarrierPartnerUpsertBulk {
	return u.Update(func(s *CarrierPartnerUpsert) {
		s.SetProviderCode(v)
	})
}

// UpdateProviderCode sets the "provider_code" field to the value that was provided on create.
func (u *CarrierPartnerUpsertBulk) UpdateProviderCode() *CarrierPartnerUpsertBulk {
	return u.Update(func(s *CarrierPartnerUpsert) {
		s.UpdateProviderCode()
	})
}

// SetAPICredentialsJSON sets the "api_credentials_json" field.
func (u *CarrierPartnerUpsertBulk) SetAPICredentialsJSON(v map[string]interface{}) *CarrierPartnerUpsertBulk {
	return u.Update(func(s *CarrierPartnerUpsert) {
		s.SetAPICredentialsJSON(v)
	})
}

// UpdateAPICredentialsJSON sets the "api_credentials_json" field to the value that was provided on create.
func (u *CarrierPartnerUpsertBulk) UpdateAPICredentialsJSON() *CarrierPartnerUpsertBulk {
	return u.Update(func(s *CarrierPartnerUpsert) {
		s.UpdateAPICredentialsJSON()
	})
}

// ClearAPICredentialsJSON clears the value of the "api_credentials_json" field.
func (u *CarrierPartnerUpsertBulk) ClearAPICredentialsJSON() *CarrierPartnerUpsertBulk {
	return u.Update(func(s *CarrierPartnerUpsert) {
		s.ClearAPICredentialsJSON()
	})
}

// SetStatus sets the "status" field.
func (u *CarrierPartnerUpsertBulk) SetStatus(v string) *CarrierPartnerUpsertBulk {
	return u.Update(func(s *CarrierPartnerUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CarrierPartnerUpsertBulk) UpdateStatus() *CarrierPartnerUpsertBulk {
	return u.Update(func(s *CarrierPartnerUpsert) {
		s.UpdateStatus()
	})
}

// SetMetadata sets the "metadata" field.
func (u *CarrierPartnerUpsertBulk) SetMetadata(v map[string]interface{}) *CarrierPartnerUpsertBulk {
	return u.Update(func(s *CarrierPartnerUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *CarrierPartnerUpsertBulk) UpdateMetadata() *CarrierPartnerUpsertBulk {
	return u.Update(func(s *CarrierPartnerUpsert) {
		s.UpdateMetadata()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CarrierPartnerUpsertBulk) SetUpdatedAt(v time.Time) *CarrierPartnerUpsertBulk {
	return u.Update(func(s *CarrierPartnerUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CarrierPartnerUpsertBulk) UpdateUpdatedAt() *CarrierPartnerUpsertBulk {
	return u.Update(func(s *CarrierPartnerUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CarrierPartnerUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CarrierPartnerCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CarrierPartnerCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CarrierPartnerUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
