// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/logistics-service/internal/ent/chainofcustody"
	"github.com/bengobox/logistics-service/internal/ent/predicate"
)

// ChainOfCustodyDelete is the builder for deleting a ChainOfCustody entity.
type ChainOfCustodyDelete struct {
	config
	hooks    []Hook
	mutation *ChainOfCustodyMutation
}

// Where appends a list predicates to the ChainOfCustodyDelete builder.
func (_d *ChainOfCustodyDelete) Where(ps ...predicate.ChainOfCustody) *ChainOfCustodyDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ChainOfCustodyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ChainOfCustodyDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ChainOfCustodyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(chainofcustody.Table, sqlgraph.NewFieldSpec(chainofcustody.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ChainOfCustodyDeleteOne is the builder for deleting a single ChainOfCustody entity.
type ChainOfCustodyDeleteOne struct {
	_d *ChainOfCustodyDelete
}

// Where appends a list predicates to the ChainOfCustodyDelete builder.
func (_d *ChainOfCustodyDeleteOne) Where(ps ...predicate.ChainOfCustody) *ChainOfCustodyDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ChainOfCustodyDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{chainofcustody.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ChainOfCustodyDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
