// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/logistics-service/internal/ent/fleet"
	"github.com/bengobox/logistics-service/internal/ent/fleetmember"
	"github.com/bengobox/logistics-service/internal/ent/predicate"
	"github.com/bengobox/logistics-service/internal/ent/riderrating"
	"github.com/bengobox/logistics-service/internal/ent/taskassignment"
	"github.com/bengobox/logistics-service/internal/ent/user"
	"github.com/bengobox/logistics-service/internal/ent/vehicle"
	"github.com/google/uuid"
)

// FleetMemberUpdate is the builder for updating FleetMember entities.
type FleetMemberUpdate struct {
	config
	hooks    []Hook
	mutation *FleetMemberMutation
}

// Where appends a list predicates to the FleetMemberUpdate builder.
func (_u *FleetMemberUpdate) Where(ps ...predicate.FleetMember) *FleetMemberUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *FleetMemberUpdate) SetTenantID(v uuid.UUID) *FleetMemberUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *FleetMemberUpdate) SetNillableTenantID(v *uuid.UUID) *FleetMemberUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetFleetID sets the "fleet_id" field.
func (_u *FleetMemberUpdate) SetFleetID(v uuid.UUID) *FleetMemberUpdate {
	_u.mutation.SetFleetID(v)
	return _u
}

// SetNillableFleetID sets the "fleet_id" field if the given value is not nil.
func (_u *FleetMemberUpdate) SetNillableFleetID(v *uuid.UUID) *FleetMemberUpdate {
	if v != nil {
		_u.SetFleetID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *FleetMemberUpdate) SetUserID(v uuid.UUID) *FleetMemberUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *FleetMemberUpdate) SetNillableUserID(v *uuid.UUID) *FleetMemberUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetDriverCode sets the "driver_code" field.
func (_u *FleetMemberUpdate) SetDriverCode(v string) *FleetMemberUpdate {
	_u.mutation.SetDriverCode(v)
	return _u
}

// SetNillableDriverCode sets the "driver_code" field if the given value is not nil.
func (_u *FleetMemberUpdate) SetNillableDriverCode(v *string) *FleetMemberUpdate {
	if v != nil {
		_u.SetDriverCode(*v)
	}
	return _u
}

// ClearDriverCode clears the value of the "driver_code" field.
func (_u *FleetMemberUpdate) ClearDriverCode() *FleetMemberUpdate {
	_u.mutation.ClearDriverCode()
	return _u
}

// SetIDNumber sets the "id_number" field.
func (_u *FleetMemberUpdate) SetIDNumber(v string) *FleetMemberUpdate {
	_u.mutation.SetIDNumber(v)
	return _u
}

// SetNillableIDNumber sets the "id_number" field if the given value is not nil.
func (_u *FleetMemberUpdate) SetNillableIDNumber(v *string) *FleetMemberUpdate {
	if v != nil {
		_u.SetIDNumber(*v)
	}
	return _u
}

// ClearIDNumber clears the value of the "id_number" field.
func (_u *FleetMemberUpdate) ClearIDNumber() *FleetMemberUpdate {
	_u.mutation.ClearIDNumber()
	return _u
}

// SetLicenseNo sets the "license_no" field.
func (_u *FleetMemberUpdate) SetLicenseNo(v string) *FleetMemberUpdate {
	_u.mutation.SetLicenseNo(v)
	return _u
}

// SetNillableLicenseNo sets the "license_no" field if the given value is not nil.
func (_u *FleetMemberUpdate) SetNillableLicenseNo(v *string) *FleetMemberUpdate {
	if v != nil {
		_u.SetLicenseNo(*v)
	}
	return _u
}

// ClearLicenseNo clears the value of the "license_no" field.
func (_u *FleetMemberUpdate) ClearLicenseNo() *FleetMemberUpdate {
	_u.mutation.ClearLicenseNo()
	return _u
}

// SetStatus sets the "status" field.
func (_u *FleetMemberUpdate) SetStatus(v string) *FleetMemberUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *FleetMemberUpdate) SetNillableStatus(v *string) *FleetMemberUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetInviteCode sets the "invite_code" field.
func (_u *FleetMemberUpdate) SetInviteCode(v string) *FleetMemberUpdate {
	_u.mutation.SetInviteCode(v)
	return _u
}

// SetNillableInviteCode sets the "invite_code" field if the given value is not nil.
func (_u *FleetMemberUpdate) SetNillableInviteCode(v *string) *FleetMemberUpdate {
	if v != nil {
		_u.SetInviteCode(*v)
	}
	return _u
}

// ClearInviteCode clears the value of the "invite_code" field.
func (_u *FleetMemberUpdate) ClearInviteCode() *FleetMemberUpdate {
	_u.mutation.ClearInviteCode()
	return _u
}

// SetKycSubmittedAt sets the "kyc_submitted_at" field.
func (_u *FleetMemberUpdate) SetKycSubmittedAt(v time.Time) *FleetMemberUpdate {
	_u.mutation.SetKycSubmittedAt(v)
	return _u
}

// SetNillableKycSubmittedAt sets the "kyc_submitted_at" field if the given value is not nil.
func (_u *FleetMemberUpdate) SetNillableKycSubmittedAt(v *time.Time) *FleetMemberUpdate {
	if v != nil {
		_u.SetKycSubmittedAt(*v)
	}
	return _u
}

// ClearKycSubmittedAt clears the value of the "kyc_submitted_at" field.
func (_u *FleetMemberUpdate) ClearKycSubmittedAt() *FleetMemberUpdate {
	_u.mutation.ClearKycSubmittedAt()
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *FleetMemberUpdate) SetReviewedAt(v time.Time) *FleetMemberUpdate {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *FleetMemberUpdate) SetNillableReviewedAt(v *time.Time) *FleetMemberUpdate {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *FleetMemberUpdate) ClearReviewedAt() *FleetMemberUpdate {
	_u.mutation.ClearReviewedAt()
	return _u
}

// SetReviewedBy sets the "reviewed_by" field.
func (_u *FleetMemberUpdate) SetReviewedBy(v string) *FleetMemberUpdate {
	_u.mutation.SetReviewedBy(v)
	return _u
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_u *FleetMemberUpdate) SetNillableReviewedBy(v *string) *FleetMemberUpdate {
	if v != nil {
		_u.SetReviewedBy(*v)
	}
	return _u
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (_u *FleetMemberUpdate) ClearReviewedBy() *FleetMemberUpdate {
	_u.mutation.ClearReviewedBy()
	return _u
}

// SetRejectionReason sets the "rejection_reason" field.
func (_u *FleetMemberUpdate) SetRejectionReason(v string) *FleetMemberUpdate {
	_u.mutation.SetRejectionReason(v)
	return _u
}

// SetNillableRejectionReason sets the "rejection_reason" field if the given value is not nil.
func (_u *FleetMemberUpdate) SetNillableRejectionReason(v *string) *FleetMemberUpdate {
	if v != nil {
		_u.SetRejectionReason(*v)
	}
	return _u
}

// ClearRejectionReason clears the value of the "rejection_reason" field.
func (_u *FleetMemberUpdate) ClearRejectionReason() *FleetMemberUpdate {
	_u.mutation.ClearRejectionReason()
	return _u
}

// SetOnboardingSource sets the "onboarding_source" field.
func (_u *FleetMemberUpdate) SetOnboardingSource(v string) *FleetMemberUpdate {
	_u.mutation.SetOnboardingSource(v)
	return _u
}

// SetNillableOnboardingSource sets the "onboarding_source" field if the given value is not nil.
func (_u *FleetMemberUpdate) SetNillableOnboardingSource(v *string) *FleetMemberUpdate {
	if v != nil {
		_u.SetOnboardingSource(*v)
	}
	return _u
}

// ClearOnboardingSource clears the value of the "onboarding_source" field.
func (_u *FleetMemberUpdate) ClearOnboardingSource() *FleetMemberUpdate {
	_u.mutation.ClearOnboardingSource()
	return _u
}

// SetIDPassportAttachment sets the "id_passport_attachment" field.
func (_u *FleetMemberUpdate) SetIDPassportAttachment(v string) *FleetMemberUpdate {
	_u.mutation.SetIDPassportAttachment(v)
	return _u
}

// SetNillableIDPassportAttachment sets the "id_passport_attachment" field if the given value is not nil.
func (_u *FleetMemberUpdate) SetNillableIDPassportAttachment(v *string) *FleetMemberUpdate {
	if v != nil {
		_u.SetIDPassportAttachment(*v)
	}
	return _u
}

// ClearIDPassportAttachment clears the value of the "id_passport_attachment" field.
func (_u *FleetMemberUpdate) ClearIDPassportAttachment() *FleetMemberUpdate {
	_u.mutation.ClearIDPassportAttachment()
	return _u
}

// SetRiderPhoto sets the "rider_photo" field.
func (_u *FleetMemberUpdate) SetRiderPhoto(v string) *FleetMemberUpdate {
	_u.mutation.SetRiderPhoto(v)
	return _u
}

// SetNillableRiderPhoto sets the "rider_photo" field if the given value is not nil.
func (_u *FleetMemberUpdate) SetNillableRiderPhoto(v *string) *FleetMemberUpdate {
	if v != nil {
		_u.SetRiderPhoto(*v)
	}
	return _u
}

// ClearRiderPhoto clears the value of the "rider_photo" field.
func (_u *FleetMemberUpdate) ClearRiderPhoto() *FleetMemberUpdate {
	_u.mutation.ClearRiderPhoto()
	return _u
}

// SetVehicleID sets the "vehicle_id" field.
func (_u *FleetMemberUpdate) SetVehicleID(v uuid.UUID) *FleetMemberUpdate {
	_u.mutation.SetVehicleID(v)
	return _u
}

// SetNillableVehicleID sets the "vehicle_id" field if the given value is not nil.
func (_u *FleetMemberUpdate) SetNillableVehicleID(v *uuid.UUID) *FleetMemberUpdate {
	if v != nil {
		_u.SetVehicleID(*v)
	}
	return _u
}

// ClearVehicleID clears the value of the "vehicle_id" field.
func (_u *FleetMemberUpdate) ClearVehicleID() *FleetMemberUpdate {
	_u.mutation.ClearVehicleID()
	return _u
}

// SetJoinedAt sets the "joined_at" field.
func (_u *FleetMemberUpdate) SetJoinedAt(v time.Time) *FleetMemberUpdate {
	_u.mutation.SetJoinedAt(v)
	return _u
}

// SetNillableJoinedAt sets the "joined_at" field if the given value is not nil.
func (_u *FleetMemberUpdate) SetNillableJoinedAt(v *time.Time) *FleetMemberUpdate {
	if v != nil {
		_u.SetJoinedAt(*v)
	}
	return _u
}

// SetSuspendedAt sets the "suspended_at" field.
func (_u *FleetMemberUpdate) SetSuspendedAt(v time.Time) *FleetMemberUpdate {
	_u.mutation.SetSuspendedAt(v)
	return _u
}

// SetNillableSuspendedAt sets the "suspended_at" field if the given value is not nil.
func (_u *FleetMemberUpdate) SetNillableSuspendedAt(v *time.Time) *FleetMemberUpdate {
	if v != nil {
		_u.SetSuspendedAt(*v)
	}
	return _u
}

// ClearSuspendedAt clears the value of the "suspended_at" field.
func (_u *FleetMemberUpdate) ClearSuspendedAt() *FleetMemberUpdate {
	_u.mutation.ClearSuspendedAt()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *FleetMemberUpdate) SetMetadata(v map[string]interface{}) *FleetMemberUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetSpecializationTags sets the "specialization_tags" field.
func (_u *FleetMemberUpdate) SetSpecializationTags(v []string) *FleetMemberUpdate {
	_u.mutation.SetSpecializationTags(v)
	return _u
}

// AppendSpecializationTags appends value to the "specialization_tags" field.
func (_u *FleetMemberUpdate) AppendSpecializationTags(v []string) *FleetMemberUpdate {
	_u.mutation.AppendSpecializationTags(v)
	return _u
}

// SetHasColdStorage sets the "has_cold_storage" field.
func (_u *FleetMemberUpdate) SetHasColdStorage(v bool) *FleetMemberUpdate {
	_u.mutation.SetHasColdStorage(v)
	return _u
}

// SetNillableHasColdStorage sets the "has_cold_storage" field if the given value is not nil.
func (_u *FleetMemberUpdate) SetNillableHasColdStorage(v *bool) *FleetMemberUpdate {
	if v != nil {
		_u.SetHasColdStorage(*v)
	}
	return _u
}

// SetMaxWeightCapacityKg sets the "max_weight_capacity_kg" field.
func (_u *FleetMemberUpdate) SetMaxWeightCapacityKg(v float64) *FleetMemberUpdate {
	_u.mutation.ResetMaxWeightCapacityKg()
	_u.mutation.SetMaxWeightCapacityKg(v)
	return _u
}

// SetNillableMaxWeightCapacityKg sets the "max_weight_capacity_kg" field if the given value is not nil.
func (_u *FleetMemberUpdate) SetNillableMaxWeightCapacityKg(v *float64) *FleetMemberUpdate {
	if v != nil {
		_u.SetMaxWeightCapacityKg(*v)
	}
	return _u
}

// AddMaxWeightCapacityKg adds value to the "max_weight_capacity_kg" field.
func (_u *FleetMemberUpdate) AddMaxWeightCapacityKg(v float64) *FleetMemberUpdate {
	_u.mutation.AddMaxWeightCapacityKg(v)
	return _u
}

// ClearMaxWeightCapacityKg clears the value of the "max_weight_capacity_kg" field.
func (_u *FleetMemberUpdate) ClearMaxWeightCapacityKg() *FleetMemberUpdate {
	_u.mutation.ClearMaxWeightCapacityKg()
	return _u
}

// SetAverageRating sets the "average_rating" field.
func (_u *FleetMemberUpdate) SetAverageRating(v float64) *FleetMemberUpdate {
	_u.mutation.ResetAverageRating()
	_u.mutation.SetAverageRating(v)
	return _u
}

// SetNillableAverageRating sets the "average_rating" field if the given value is not nil.
func (_u *FleetMemberUpdate) SetNillableAverageRating(v *float64) *FleetMemberUpdate {
	if v != nil {
		_u.SetAverageRating(*v)
	}
	return _u
}

// AddAverageRating adds value to the "average_rating" field.
func (_u *FleetMemberUpdate) AddAverageRating(v float64) *FleetMemberUpdate {
	_u.mutation.AddAverageRating(v)
	return _u
}

// SetTotalRatings sets the "total_ratings" field.
func (_u *FleetMemberUpdate) SetTotalRatings(v int) *FleetMemberUpdate {
	_u.mutation.ResetTotalRatings()
	_u.mutation.SetTotalRatings(v)
	return _u
}

// SetNillableTotalRatings sets the "total_ratings" field if the given value is not nil.
func (_u *FleetMemberUpdate) SetNillableTotalRatings(v *int) *FleetMemberUpdate {
	if v != nil {
		_u.SetTotalRatings(*v)
	}
	return _u
}

// AddTotalRatings adds value to the "total_ratings" field.
func (_u *FleetMemberUpdate) AddTotalRatings(v int) *FleetMemberUpdate {
	_u.mutation.AddTotalRatings(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FleetMemberUpdate) SetUpdatedAt(v time.Time) *FleetMemberUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPayoutMethod sets the "payout_method" field.
func (_u *FleetMemberUpdate) SetPayoutMethod(v fleetmember.PayoutMethod) *FleetMemberUpdate {
	_u.mutation.SetPayoutMethod(v)
	return _u
}

// SetNillablePayoutMethod sets the "payout_method" field if the given value is not nil.
func (_u *FleetMemberUpdate) SetNillablePayoutMethod(v *fleetmember.PayoutMethod) *FleetMemberUpdate {
	if v != nil {
		_u.SetPayoutMethod(*v)
	}
	return _u
}

// ClearPayoutMethod clears the value of the "payout_method" field.
func (_u *FleetMemberUpdate) ClearPayoutMethod() *FleetMemberUpdate {
	_u.mutation.ClearPayoutMethod()
	return _u
}

// SetPayoutPhone sets the "payout_phone" field.
func (_u *FleetMemberUpdate) SetPayoutPhone(v string) *FleetMemberUpdate {
	_u.mutation.SetPayoutPhone(v)
	return _u
}

// SetNillablePayoutPhone sets the "payout_phone" field if the given value is not nil.
func (_u *FleetMemberUpdate) SetNillablePayoutPhone(v *string) *FleetMemberUpdate {
	if v != nil {
		_u.SetPayoutPhone(*v)
	}
	return _u
}

// ClearPayoutPhone clears the value of the "payout_phone" field.
func (_u *FleetMemberUpdate) ClearPayoutPhone() *FleetMemberUpdate {
	_u.mutation.ClearPayoutPhone()
	return _u
}

// SetPayoutBankCode sets the "payout_bank_code" field.
func (_u *FleetMemberUpdate) SetPayoutBankCode(v string) *FleetMemberUpdate {
	_u.mutation.SetPayoutBankCode(v)
	return _u
}

// SetNillablePayoutBankCode sets the "payout_bank_code" field if the given value is not nil.
func (_u *FleetMemberUpdate) SetNillablePayoutBankCode(v *string) *FleetMemberUpdate {
	if v != nil {
		_u.SetPayoutBankCode(*v)
	}
	return _u
}

// ClearPayoutBankCode clears the value of the "payout_bank_code" field.
func (_u *FleetMemberUpdate) ClearPayoutBankCode() *FleetMemberUpdate {
	_u.mutation.ClearPayoutBankCode()
	return _u
}

// SetPayoutAccountNumber sets the "payout_account_number" field.
func (_u *FleetMemberUpdate) SetPayoutAccountNumber(v string) *FleetMemberUpdate {
	_u.mutation.SetPayoutAccountNumber(v)
	return _u
}

// SetNillablePayoutAccountNumber sets the "payout_account_number" field if the given value is not nil.
func (_u *FleetMemberUpdate) SetNillablePayoutAccountNumber(v *string) *FleetMemberUpdate {
	if v != nil {
		_u.SetPayoutAccountNumber(*v)
	}
	return _u
}

// ClearPayoutAccountNumber clears the value of the "payout_account_number" field.
func (_u *FleetMemberUpdate) ClearPayoutAccountNumber() *FleetMemberUpdate {
	_u.mutation.ClearPayoutAccountNumber()
	return _u
}

// SetPayoutAccountName sets the "payout_account_name" field.
func (_u *FleetMemberUpdate) SetPayoutAccountName(v string) *FleetMemberUpdate {
	_u.mutation.SetPayoutAccountName(v)
	return _u
}

// SetNillablePayoutAccountName sets the "payout_account_name" field if the given value is not nil.
func (_u *FleetMemberUpdate) SetNillablePayoutAccountName(v *string) *FleetMemberUpdate {
	if v != nil {
		_u.SetPayoutAccountName(*v)
	}
	return _u
}

// ClearPayoutAccountName clears the value of the "payout_account_name" field.
func (_u *FleetMemberUpdate) ClearPayoutAccountName() *FleetMemberUpdate {
	_u.mutation.ClearPayoutAccountName()
	return _u
}

// SetPayoutRecipientCode sets the "payout_recipient_code" field.
func (_u *FleetMemberUpdate) SetPayoutRecipientCode(v string) *FleetMemberUpdate {
	_u.mutation.SetPayoutRecipientCode(v)
	return _u
}

// SetNillablePayoutRecipientCode sets the "payout_recipient_code" field if the given value is not nil.
func (_u *FleetMemberUpdate) SetNillablePayoutRecipientCode(v *string) *FleetMemberUpdate {
	if v != nil {
		_u.SetPayoutRecipientCode(*v)
	}
	return _u
}

// ClearPayoutRecipientCode clears the value of the "payout_recipient_code" field.
func (_u *FleetMemberUpdate) ClearPayoutRecipientCode() *FleetMemberUpdate {
	_u.mutation.ClearPayoutRecipientCode()
	return _u
}

// SetPayoutStatus sets the "payout_status" field.
func (_u *FleetMemberUpdate) SetPayoutStatus(v fleetmember.PayoutStatus) *FleetMemberUpdate {
	_u.mutation.SetPayoutStatus(v)
	return _u
}

// SetNillablePayoutStatus sets the "payout_status" field if the given value is not nil.
func (_u *FleetMemberUpdate) SetNillablePayoutStatus(v *fleetmember.PayoutStatus) *FleetMemberUpdate {
	if v != nil {
		_u.SetPayoutStatus(*v)
	}
	return _u
}

// SetFleet sets the "fleet" edge to the Fleet entity.
func (_u *FleetMemberUpdate) SetFleet(v *Fleet) *FleetMemberUpdate {
	return _u.SetFleetID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *FleetMemberUpdate) SetUser(v *User) *FleetMemberUpdate {
	return _u.SetUserID(v.ID)
}

// SetVehicle sets the "vehicle" edge to the Vehicle entity.
func (_u *FleetMemberUpdate) SetVehicle(v *Vehicle) *FleetMemberUpdate {
	return _u.SetVehicleID(v.ID)
}

// AddAssignmentIDs adds the "assignments" edge to the TaskAssignment entity by IDs.
func (_u *FleetMemberUpdate) AddAssignmentIDs(ids ...uuid.UUID) *FleetMemberUpdate {
	_u.mutation.AddAssignmentIDs(ids...)
	return _u
}

// AddAssignments adds the "assignments" edges to the TaskAssignment entity.
func (_u *FleetMemberUpdate) AddAssignments(v ...*TaskAssignment) *FleetMemberUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAssignmentIDs(ids...)
}

// AddRatingIDs adds the "ratings" edge to the RiderRating entity by IDs.
func (_u *FleetMemberUpdate) AddRatingIDs(ids ...uuid.UUID) *FleetMemberUpdate {
	_u.mutation.AddRatingIDs(ids...)
	return _u
}

// AddRatings adds the "ratings" edges to the RiderRating entity.
func (_u *FleetMemberUpdate) AddRatings(v ...*RiderRating) *FleetMemberUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRatingIDs(ids...)
}

// Mutation returns the FleetMemberMutation object of the builder.
func (_u *FleetMemberUpdate) Mutation() *FleetMemberMutation {
	return _u.mutation
}

// ClearFleet clears the "fleet" edge to the Fleet entity.
func (_u *FleetMemberUpdate) ClearFleet() *FleetMemberUpdate {
	_u.mutation.ClearFleet()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *FleetMemberUpdate) ClearUser() *FleetMemberUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearVehicle clears the "vehicle" edge to the Vehicle entity.
func (_u *FleetMemberUpdate) ClearVehicle() *FleetMemberUpdate {
	_u.mutation.ClearVehicle()
	return _u
}

// ClearAssignments clears all "assignments" edges to the TaskAssignment entity.
func (_u *FleetMemberUpdate) ClearAssignments() *FleetMemberUpdate {
	_u.mutation.ClearAssignments()
	return _u
}

// RemoveAssignmentIDs removes the "assignments" edge to TaskAssignment entities by IDs.
func (_u *FleetMemberUpdate) RemoveAssignmentIDs(ids ...uuid.UUID) *FleetMemberUpdate {
	_u.mutation.RemoveAssignmentIDs(ids...)
	return _u
}

// RemoveAssignments removes "assignments" edges to TaskAssignment entities.
func (_u *FleetMemberUpdate) RemoveAssignments(v ...*TaskAssignment) *FleetMemberUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAssignmentIDs(ids...)
}

// ClearRatings clears all "ratings" edges to the RiderRating entity.
func (_u *FleetMemberUpdate) ClearRatings() *FleetMemberUpdate {
	_u.mutation.ClearRatings()
	return _u
}

// RemoveRatingIDs removes the "ratings" edge to RiderRating entities by IDs.
func (_u *FleetMemberUpdate) RemoveRatingIDs(ids ...uuid.UUID) *FleetMemberUpdate {
	_u.mutation.RemoveRatingIDs(ids...)
	return _u
}

// RemoveRatings removes "ratings" edges to RiderRating entities.
func (_u *FleetMemberUpdate) RemoveRatings(v ...*RiderRating) *FleetMemberUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRatingIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FleetMemberUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FleetMemberUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FleetMemberUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FleetMemberUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FleetMemberUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := fleetmember.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FleetMemberUpdate) check() error {
	if v, ok := _u.mutation.PayoutMethod(); ok {
		if err := fleetmember.PayoutMethodValidator(v); err != nil {
			return &ValidationError{Name: "payout_method", err: fmt.Errorf(`ent: validator failed for field "FleetMember.payout_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PayoutStatus(); ok {
		if err := fleetmember.PayoutStatusValidator(v); err != nil {
			return &ValidationError{Name: "payout_status", err: fmt.Errorf(`ent: validator failed for field "FleetMember.payout_status": %w`, err)}
		}
	}
	if _u.mutation.FleetCleared() && len(_u.mutation.FleetIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FleetMember.fleet"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FleetMember.user"`)
	}
	return nil
}

func (_u *FleetMemberUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(fleetmember.Table, fleetmember.Columns, sqlgraph.NewFieldSpec(fleetmember.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(fleetmember.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.DriverCode(); ok {
		_spec.SetField(fleetmember.FieldDriverCode, field.TypeString, value)
	}
	if _u.mutation.DriverCodeCleared() {
		_spec.ClearField(fleetmember.FieldDriverCode, field.TypeString)
	}
	if value, ok := _u.mutation.IDNumber(); ok {
		_spec.SetField(fleetmember.FieldIDNumber, field.TypeString, value)
	}
	if _u.mutation.IDNumberCleared() {
		_spec.ClearField(fleetmember.FieldIDNumber, field.TypeString)
	}
	if value, ok := _u.mutation.LicenseNo(); ok {
		_spec.SetField(fleetmember.FieldLicenseNo, field.TypeString, value)
	}
	if _u.mutation.LicenseNoCleared() {
		_spec.ClearField(fleetmember.FieldLicenseNo, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(fleetmember.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.InviteCode(); ok {
		_spec.SetField(fleetmember.FieldInviteCode, field.TypeString, value)
	}
	if _u.mutation.InviteCodeCleared() {
		_spec.ClearField(fleetmember.FieldInviteCode, field.TypeString)
	}
	if value, ok := _u.mutation.KycSubmittedAt(); ok {
		_spec.SetField(fleetmember.FieldKycSubmittedAt, field.TypeTime, value)
	}
	if _u.mutation.KycSubmittedAtCleared() {
		_spec.ClearField(fleetmember.FieldKycSubmittedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(fleetmember.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(fleetmember.FieldReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ReviewedBy(); ok {
		_spec.SetField(fleetmember.FieldReviewedBy, field.TypeString, value)
	}
	if _u.mutation.ReviewedByCleared() {
		_spec.ClearField(fleetmember.FieldReviewedBy, field.TypeString)
	}
	if value, ok := _u.mutation.RejectionReason(); ok {
		_spec.SetField(fleetmember.FieldRejectionReason, field.TypeString, value)
	}
	if _u.mutation.RejectionReasonCleared() {
		_spec.ClearField(fleetmember.FieldRejectionReason, field.TypeString)
	}
	if value, ok := _u.mutation.OnboardingSource(); ok {
		_spec.SetField(fleetmember.FieldOnboardingSource, field.TypeString, value)
	}
	if _u.mutation.OnboardingSourceCleared() {
		_spec.ClearField(fleetmember.FieldOnboardingSource, field.TypeString)
	}
	if value, ok := _u.mutation.IDPassportAttachment(); ok {
		_spec.SetField(fleetmember.FieldIDPassportAttachment, field.TypeString, value)
	}
	if _u.mutation.IDPassportAttachmentCleared() {
		_spec.ClearField(fleetmember.FieldIDPassportAttachment, field.TypeString)
	}
	if value, ok := _u.mutation.RiderPhoto(); ok {
		_spec.SetField(fleetmember.FieldRiderPhoto, field.TypeString, value)
	}
	if _u.mutation.RiderPhotoCleared() {
		_spec.ClearField(fleetmember.FieldRiderPhoto, field.TypeString)
	}
	if value, ok := _u.mutation.JoinedAt(); ok {
		_spec.SetField(fleetmember.FieldJoinedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SuspendedAt(); ok {
		_spec.SetField(fleetmember.FieldSuspendedAt, field.TypeTime, value)
	}
	if _u.mutation.SuspendedAtCleared() {
		_spec.ClearField(fleetmember.FieldSuspendedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(fleetmember.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.SpecializationTags(); ok {
		_spec.SetField(fleetmember.FieldSpecializationTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSpecializationTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, fleetmember.FieldSpecializationTags, value)
		})
	}
	if value, ok := _u.mutation.HasColdStorage(); ok {
		_spec.SetField(fleetmember.FieldHasColdStorage, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MaxWeightCapacityKg(); ok {
		_spec.SetField(fleetmember.FieldMaxWeightCapacityKg, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxWeightCapacityKg(); ok {
		_spec.AddField(fleetmember.FieldMaxWeightCapacityKg, field.TypeFloat64, value)
	}
	if _u.mutation.MaxWeightCapacityKgCleared() {
		_spec.ClearField(fleetmember.FieldMaxWeightCapacityKg, field.TypeFloat64)
	}
	if value, ok := _u.mutation.AverageRating(); ok {
		_spec.SetField(fleetmember.FieldAverageRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAverageRating(); ok {
		_spec.AddField(fleetmember.FieldAverageRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalRatings(); ok {
		_spec.SetField(fleetmember.FieldTotalRatings, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalRatings(); ok {
		_spec.AddField(fleetmember.FieldTotalRatings, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(fleetmember.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PayoutMethod(); ok {
		_spec.SetField(fleetmember.FieldPayoutMethod, field.TypeEnum, value)
	}
	if _u.mutation.PayoutMethodCleared() {
		_spec.ClearField(fleetmember.FieldPayoutMethod, field.TypeEnum)
	}
	if value, ok := _u.mutation.PayoutPhone(); ok {
		_spec.SetField(fleetmember.FieldPayoutPhone, field.TypeString, value)
	}
	if _u.mutation.PayoutPhoneCleared() {
		_spec.ClearField(fleetmember.FieldPayoutPhone, field.TypeString)
	}
	if value, ok := _u.mutation.PayoutBankCode(); ok {
		_spec.SetField(fleetmember.FieldPayoutBankCode, field.TypeString, value)
	}
	if _u.mutation.PayoutBankCodeCleared() {
		_spec.ClearField(fleetmember.FieldPayoutBankCode, field.TypeString)
	}
	if value, ok := _u.mutation.PayoutAccountNumber(); ok {
		_spec.SetField(fleetmember.FieldPayoutAccountNumber, field.TypeString, value)
	}
	if _u.mutation.PayoutAccountNumberCleared() {
		_spec.ClearField(fleetmember.FieldPayoutAccountNumber, field.TypeString)
	}
	if value, ok := _u.mutation.PayoutAccountName(); ok {
		_spec.SetField(fleetmember.FieldPayoutAccountName, field.TypeString, value)
	}
	if _u.mutation.PayoutAccountNameCleared() {
		_spec.ClearField(fleetmember.FieldPayoutAccountName, field.TypeString)
	}
	if value, ok := _u.mutation.PayoutRecipientCode(); ok {
		_spec.SetField(fleetmember.FieldPayoutRecipientCode, field.TypeString, value)
	}
	if _u.mutation.PayoutRecipientCodeCleared() {
		_spec.ClearField(fleetmember.FieldPayoutRecipientCode, field.TypeString)
	}
	if value, ok := _u.mutation.PayoutStatus(); ok {
		_spec.SetField(fleetmember.FieldPayoutStatus, field.TypeEnum, value)
	}
	if _u.mutation.FleetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   fleetmember.FleetTable,
			Columns: []string{fleetmember.FleetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fleet.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FleetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   fleetmember.FleetTable,
			Columns: []string{fleetmember.FleetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fleet.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   fleetmember.UserTable,
			Columns: []string{fleetmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   fleetmember.UserTable,
			Columns: []string{fleetmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VehicleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   fleetmember.VehicleTable,
			Columns: []string{fleetmember.VehicleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vehicle.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VehicleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   fleetmember.VehicleTable,
			Columns: []string{fleetmember.VehicleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vehicle.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fleetmember.AssignmentsTable,
			Columns: []string{fleetmember.AssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskassignment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAssignmentsIDs(); len(nodes) > 0 && !_u.mutation.AssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fleetmember.AssignmentsTable,
			Columns: []string{fleetmember.AssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssignmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fleetmember.AssignmentsTable,
			Columns: []string{fleetmember.AssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RatingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fleetmember.RatingsTable,
			Columns: []string{fleetmember.RatingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(riderrating.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRatingsIDs(); len(nodes) > 0 && !_u.mutation.RatingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fleetmember.RatingsTable,
			Columns: []string{fleetmember.RatingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(riderrating.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RatingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fleetmember.RatingsTable,
			Columns: []string{fleetmember.RatingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(riderrating.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{fleetmember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FleetMemberUpdateOne is the builder for updating a single FleetMember entity.
type FleetMemberUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FleetMemberMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *FleetMemberUpdateOne) SetTenantID(v uuid.UUID) *FleetMemberUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *FleetMemberUpdateOne) SetNillableTenantID(v *uuid.UUID) *FleetMemberUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetFleetID sets the "fleet_id" field.
func (_u *FleetMemberUpdateOne) SetFleetID(v uuid.UUID) *FleetMemberUpdateOne {
	_u.mutation.SetFleetID(v)
	return _u
}

// SetNillableFleetID sets the "fleet_id" field if the given value is not nil.
func (_u *FleetMemberUpdateOne) SetNillableFleetID(v *uuid.UUID) *FleetMemberUpdateOne {
	if v != nil {
		_u.SetFleetID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *FleetMemberUpdateOne) SetUserID(v uuid.UUID) *FleetMemberUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *FleetMemberUpdateOne) SetNillableUserID(v *uuid.UUID) *FleetMemberUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetDriverCode sets the "driver_code" field.
func (_u *FleetMemberUpdateOne) SetDriverCode(v string) *FleetMemberUpdateOne {
	_u.mutation.SetDriverCode(v)
	return _u
}

// SetNillableDriverCode sets the "driver_code" field if the given value is not nil.
func (_u *FleetMemberUpdateOne) SetNillableDriverCode(v *string) *FleetMemberUpdateOne {
	if v != nil {
		_u.SetDriverCode(*v)
	}
	return _u
}

// ClearDriverCode clears the value of the "driver_code" field.
func (_u *FleetMemberUpdateOne) ClearDriverCode() *FleetMemberUpdateOne {
	_u.mutation.ClearDriverCode()
	return _u
}

// SetIDNumber sets the "id_number" field.
func (_u *FleetMemberUpdateOne) SetIDNumber(v string) *FleetMemberUpdateOne {
	_u.mutation.SetIDNumber(v)
	return _u
}

// SetNillableIDNumber sets the "id_number" field if the given value is not nil.
func (_u *FleetMemberUpdateOne) SetNillableIDNumber(v *string) *FleetMemberUpdateOne {
	if v != nil {
		_u.SetIDNumber(*v)
	}
	return _u
}

// ClearIDNumber clears the value of the "id_number" field.
func (_u *FleetMemberUpdateOne) ClearIDNumber() *FleetMemberUpdateOne {
	_u.mutation.ClearIDNumber()
	return _u
}

// SetLicenseNo sets the "license_no" field.
func (_u *FleetMemberUpdateOne) SetLicenseNo(v string) *FleetMemberUpdateOne {
	_u.mutation.SetLicenseNo(v)
	return _u
}

// SetNillableLicenseNo sets the "license_no" field if the given value is not nil.
func (_u *FleetMemberUpdateOne) SetNillableLicenseNo(v *string) *FleetMemberUpdateOne {
	if v != nil {
		_u.SetLicenseNo(*v)
	}
	return _u
}

// ClearLicenseNo clears the value of the "license_no" field.
func (_u *FleetMemberUpdateOne) ClearLicenseNo() *FleetMemberUpdateOne {
	_u.mutation.ClearLicenseNo()
	return _u
}

// SetStatus sets the "status" field.
func (_u *FleetMemberUpdateOne) SetStatus(v string) *FleetMemberUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *FleetMemberUpdateOne) SetNillableStatus(v *string) *FleetMemberUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetInviteCode sets the "invite_code" field.
func (_u *FleetMemberUpdateOne) SetInviteCode(v string) *FleetMemberUpdateOne {
	_u.mutation.SetInviteCode(v)
	return _u
}

// SetNillableInviteCode sets the "invite_code" field if the given value is not nil.
func (_u *FleetMemberUpdateOne) SetNillableInviteCode(v *string) *FleetMemberUpdateOne {
	if v != nil {
		_u.SetInviteCode(*v)
	}
	return _u
}

// ClearInviteCode clears the value of the "invite_code" field.
func (_u *FleetMemberUpdateOne) ClearInviteCode() *FleetMemberUpdateOne {
	_u.mutation.ClearInviteCode()
	return _u
}

// SetKycSubmittedAt sets the "kyc_submitted_at" field.
func (_u *FleetMemberUpdateOne) SetKycSubmittedAt(v time.Time) *FleetMemberUpdateOne {
	_u.mutation.SetKycSubmittedAt(v)
	return _u
}

// SetNillableKycSubmittedAt sets the "kyc_submitted_at" field if the given value is not nil.
func (_u *FleetMemberUpdateOne) SetNillableKycSubmittedAt(v *time.Time) *FleetMemberUpdateOne {
	if v != nil {
		_u.SetKycSubmittedAt(*v)
	}
	return _u
}

// ClearKycSubmittedAt clears the value of the "kyc_submitted_at" field.
func (_u *FleetMemberUpdateOne) ClearKycSubmittedAt() *FleetMemberUpdateOne {
	_u.mutation.ClearKycSubmittedAt()
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *FleetMemberUpdateOne) SetReviewedAt(v time.Time) *FleetMemberUpdateOne {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *FleetMemberUpdateOne) SetNillableReviewedAt(v *time.Time) *FleetMemberUpdateOne {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *FleetMemberUpdateOne) ClearReviewedAt() *FleetMemberUpdateOne {
	_u.mutation.ClearReviewedAt()
	return _u
}

// SetReviewedBy sets the "reviewed_by" field.
func (_u *FleetMemberUpdateOne) SetReviewedBy(v string) *FleetMemberUpdateOne {
	_u.mutation.SetReviewedBy(v)
	return _u
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_u *FleetMemberUpdateOne) SetNillableReviewedBy(v *string) *FleetMemberUpdateOne {
	if v != nil {
		_u.SetReviewedBy(*v)
	}
	return _u
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (_u *FleetMemberUpdateOne) ClearReviewedBy() *FleetMemberUpdateOne {
	_u.mutation.ClearReviewedBy()
	return _u
}

// SetRejectionReason sets the "rejection_reason" field.
func (_u *FleetMemberUpdateOne) SetRejectionReason(v string) *FleetMemberUpdateOne {
	_u.mutation.SetRejectionReason(v)
	return _u
}

// SetNillableRejectionReason sets the "rejection_reason" field if the given value is not nil.
func (_u *FleetMemberUpdateOne) SetNillableRejectionReason(v *string) *FleetMemberUpdateOne {
	if v != nil {
		_u.SetRejectionReason(*v)
	}
	return _u
}

// ClearRejectionReason clears the value of the "rejection_reason" field.
func (_u *FleetMemberUpdateOne) ClearRejectionReason() *FleetMemberUpdateOne {
	_u.mutation.ClearRejectionReason()
	return _u
}

// SetOnboardingSource sets the "onboarding_source" field.
func (_u *FleetMemberUpdateOne) SetOnboardingSource(v string) *FleetMemberUpdateOne {
	_u.mutation.SetOnboardingSource(v)
	return _u
}

// SetNillableOnboardingSource sets the "onboarding_source" field if the given value is not nil.
func (_u *FleetMemberUpdateOne) SetNillableOnboardingSource(v *string) *FleetMemberUpdateOne {
	if v != nil {
		_u.SetOnboardingSource(*v)
	}
	return _u
}

// ClearOnboardingSource clears the value of the "onboarding_source" field.
func (_u *FleetMemberUpdateOne) ClearOnboardingSource() *FleetMemberUpdateOne {
	_u.mutation.ClearOnboardingSource()
	return _u
}

// SetIDPassportAttachment sets the "id_passport_attachment" field.
func (_u *FleetMemberUpdateOne) SetIDPassportAttachment(v string) *FleetMemberUpdateOne {
	_u.mutation.SetIDPassportAttachment(v)
	return _u
}

// SetNillableIDPassportAttachment sets the "id_passport_attachment" field if the given value is not nil.
func (_u *FleetMemberUpdateOne) SetNillableIDPassportAttachment(v *string) *FleetMemberUpdateOne {
	if v != nil {
		_u.SetIDPassportAttachment(*v)
	}
	return _u
}

// ClearIDPassportAttachment clears the value of the "id_passport_attachment" field.
func (_u *FleetMemberUpdateOne) ClearIDPassportAttachment() *FleetMemberUpdateOne {
	_u.mutation.ClearIDPassportAttachment()
	return _u
}

// SetRiderPhoto sets the "rider_photo" field.
func (_u *FleetMemberUpdateOne) SetRiderPhoto(v string) *FleetMemberUpdateOne {
	_u.mutation.SetRiderPhoto(v)
	return _u
}

// SetNillableRiderPhoto sets the "rider_photo" field if the given value is not nil.
func (_u *FleetMemberUpdateOne) SetNillableRiderPhoto(v *string) *FleetMemberUpdateOne {
	if v != nil {
		_u.SetRiderPhoto(*v)
	}
	return _u
}

// ClearRiderPhoto clears the value of the "rider_photo" field.
func (_u *FleetMemberUpdateOne) ClearRiderPhoto() *FleetMemberUpdateOne {
	_u.mutation.ClearRiderPhoto()
	return _u
}

// SetVehicleID sets the "vehicle_id" field.
func (_u *FleetMemberUpdateOne) SetVehicleID(v uuid.UUID) *FleetMemberUpdateOne {
	_u.mutation.SetVehicleID(v)
	return _u
}

// SetNillableVehicleID sets the "vehicle_id" field if the given value is not nil.
func (_u *FleetMemberUpdateOne) SetNillableVehicleID(v *uuid.UUID) *FleetMemberUpdateOne {
	if v != nil {
		_u.SetVehicleID(*v)
	}
	return _u
}

// ClearVehicleID clears the value of the "vehicle_id" field.
func (_u *FleetMemberUpdateOne) ClearVehicleID() *FleetMemberUpdateOne {
	_u.mutation.ClearVehicleID()
	return _u
}

// SetJoinedAt sets the "joined_at" field.
func (_u *FleetMemberUpdateOne) SetJoinedAt(v time.Time) *FleetMemberUpdateOne {
	_u.mutation.SetJoinedAt(v)
	return _u
}

// SetNillableJoinedAt sets the "joined_at" field if the given value is not nil.
func (_u *FleetMemberUpdateOne) SetNillableJoinedAt(v *time.Time) *FleetMemberUpdateOne {
	if v != nil {
		_u.SetJoinedAt(*v)
	}
	return _u
}

// SetSuspendedAt sets the "suspended_at" field.
func (_u *FleetMemberUpdateOne) SetSuspendedAt(v time.Time) *FleetMemberUpdateOne {
	_u.mutation.SetSuspendedAt(v)
	return _u
}

// SetNillableSuspendedAt sets the "suspended_at" field if the given value is not nil.
func (_u *FleetMemberUpdateOne) SetNillableSuspendedAt(v *time.Time) *FleetMemberUpdateOne {
	if v != nil {
		_u.SetSuspendedAt(*v)
	}
	return _u
}

// ClearSuspendedAt clears the value of the "suspended_at" field.
func (_u *FleetMemberUpdateOne) ClearSuspendedAt() *FleetMemberUpdateOne {
	_u.mutation.ClearSuspendedAt()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *FleetMemberUpdateOne) SetMetadata(v map[string]interface{}) *FleetMemberUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetSpecializationTags sets the "specialization_tags" field.
func (_u *FleetMemberUpdateOne) SetSpecializationTags(v []string) *FleetMemberUpdateOne {
	_u.mutation.SetSpecializationTags(v)
	return _u
}

// AppendSpecializationTags appends value to the "specialization_tags" field.
func (_u *FleetMemberUpdateOne) AppendSpecializationTags(v []string) *FleetMemberUpdateOne {
	_u.mutation.AppendSpecializationTags(v)
	return _u
}

// SetHasColdStorage sets the "has_cold_storage" field.
func (_u *FleetMemberUpdateOne) SetHasColdStorage(v bool) *FleetMemberUpdateOne {
	_u.mutation.SetHasColdStorage(v)
	return _u
}

// SetNillableHasColdStorage sets the "has_cold_storage" field if the given value is not nil.
func (_u *FleetMemberUpdateOne) SetNillableHasColdStorage(v *bool) *FleetMemberUpdateOne {
	if v != nil {
		_u.SetHasColdStorage(*v)
	}
	return _u
}

// SetMaxWeightCapacityKg sets the "max_weight_capacity_kg" field.
func (_u *FleetMemberUpdateOne) SetMaxWeightCapacityKg(v float64) *FleetMemberUpdateOne {
	_u.mutation.ResetMaxWeightCapacityKg()
	_u.mutation.SetMaxWeightCapacityKg(v)
	return _u
}

// SetNillableMaxWeightCapacityKg sets the "max_weight_capacity_kg" field if the given value is not nil.
func (_u *FleetMemberUpdateOne) SetNillableMaxWeightCapacityKg(v *float64) *FleetMemberUpdateOne {
	if v != nil {
		_u.SetMaxWeightCapacityKg(*v)
	}
	return _u
}

// AddMaxWeightCapacityKg adds value to the "max_weight_capacity_kg" field.
func (_u *FleetMemberUpdateOne) AddMaxWeightCapacityKg(v float64) *FleetMemberUpdateOne {
	_u.mutation.AddMaxWeightCapacityKg(v)
	return _u
}

// ClearMaxWeightCapacityKg clears the value of the "max_weight_capacity_kg" field.
func (_u *FleetMemberUpdateOne) ClearMaxWeightCapacityKg() *FleetMemberUpdateOne {
	_u.mutation.ClearMaxWeightCapacityKg()
	return _u
}

// SetAverageRating sets the "average_rating" field.
func (_u *FleetMemberUpdateOne) SetAverageRating(v float64) *FleetMemberUpdateOne {
	_u.mutation.ResetAverageRating()
	_u.mutation.SetAverageRating(v)
	return _u
}

// SetNillableAverageRating sets the "average_rating" field if the given value is not nil.
func (_u *FleetMemberUpdateOne) SetNillableAverageRating(v *float64) *FleetMemberUpdateOne {
	if v != nil {
		_u.SetAverageRating(*v)
	}
	return _u
}

// AddAverageRating adds value to the "average_rating" field.
func (_u *FleetMemberUpdateOne) AddAverageRating(v float64) *FleetMemberUpdateOne {
	_u.mutation.AddAverageRating(v)
	return _u
}

// SetTotalRatings sets the "total_ratings" field.
func (_u *FleetMemberUpdateOne) SetTotalRatings(v int) *FleetMemberUpdateOne {
	_u.mutation.ResetTotalRatings()
	_u.mutation.SetTotalRatings(v)
	return _u
}

// SetNillableTotalRatings sets the "total_ratings" field if the given value is not nil.
func (_u *FleetMemberUpdateOne) SetNillableTotalRatings(v *int) *FleetMemberUpdateOne {
	if v != nil {
		_u.SetTotalRatings(*v)
	}
	return _u
}

// AddTotalRatings adds value to the "total_ratings" field.
func (_u *FleetMemberUpdateOne) AddTotalRatings(v int) *FleetMemberUpdateOne {
	_u.mutation.AddTotalRatings(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FleetMemberUpdateOne) SetUpdatedAt(v time.Time) *FleetMemberUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPayoutMethod sets the "payout_method" field.
func (_u *FleetMemberUpdateOne) SetPayoutMethod(v fleetmember.PayoutMethod) *FleetMemberUpdateOne {
	_u.mutation.SetPayoutMethod(v)
	return _u
}

// SetNillablePayoutMethod sets the "payout_method" field if the given value is not nil.
func (_u *FleetMemberUpdateOne) SetNillablePayoutMethod(v *fleetmember.PayoutMethod) *FleetMemberUpdateOne {
	if v != nil {
		_u.SetPayoutMethod(*v)
	}
	return _u
}

// ClearPayoutMethod clears the value of the "payout_method" field.
func (_u *FleetMemberUpdateOne) ClearPayoutMethod() *FleetMemberUpdateOne {
	_u.mutation.ClearPayoutMethod()
	return _u
}

// SetPayoutPhone sets the "payout_phone" field.
func (_u *FleetMemberUpdateOne) SetPayoutPhone(v string) *FleetMemberUpdateOne {
	_u.mutation.SetPayoutPhone(v)
	return _u
}

// SetNillablePayoutPhone sets the "payout_phone" field if the given value is not nil.
func (_u *FleetMemberUpdateOne) SetNillablePayoutPhone(v *string) *FleetMemberUpdateOne {
	if v != nil {
		_u.SetPayoutPhone(*v)
	}
	return _u
}

// ClearPayoutPhone clears the value of the "payout_phone" field.
func (_u *FleetMemberUpdateOne) ClearPayoutPhone() *FleetMemberUpdateOne {
	_u.mutation.ClearPayoutPhone()
	return _u
}

// SetPayoutBankCode sets the "payout_bank_code" field.
func (_u *FleetMemberUpdateOne) SetPayoutBankCode(v string) *FleetMemberUpdateOne {
	_u.mutation.SetPayoutBankCode(v)
	return _u
}

// SetNillablePayoutBankCode sets the "payout_bank_code" field if the given value is not nil.
func (_u *FleetMemberUpdateOne) SetNillablePayoutBankCode(v *string) *FleetMemberUpdateOne {
	if v != nil {
		_u.SetPayoutBankCode(*v)
	}
	return _u
}

// ClearPayoutBankCode clears the value of the "payout_bank_code" field.
func (_u *FleetMemberUpdateOne) ClearPayoutBankCode() *FleetMemberUpdateOne {
	_u.mutation.ClearPayoutBankCode()
	return _u
}

// SetPayoutAccountNumber sets the "payout_account_number" field.
func (_u *FleetMemberUpdateOne) SetPayoutAccountNumber(v string) *FleetMemberUpdateOne {
	_u.mutation.SetPayoutAccountNumber(v)
	return _u
}

// SetNillablePayoutAccountNumber sets the "payout_account_number" field if the given value is not nil.
func (_u *FleetMemberUpdateOne) SetNillablePayoutAccountNumber(v *string) *FleetMemberUpdateOne {
	if v != nil {
		_u.SetPayoutAccountNumber(*v)
	}
	return _u
}

// ClearPayoutAccountNumber clears the value of the "payout_account_number" field.
func (_u *FleetMemberUpdateOne) ClearPayoutAccountNumber() *FleetMemberUpdateOne {
	_u.mutation.ClearPayoutAccountNumber()
	return _u
}

// SetPayoutAccountName sets the "payout_account_name" field.
func (_u *FleetMemberUpdateOne) SetPayoutAccountName(v string) *FleetMemberUpdateOne {
	_u.mutation.SetPayoutAccountName(v)
	return _u
}

// SetNillablePayoutAccountName sets the "payout_account_name" field if the given value is not nil.
func (_u *FleetMemberUpdateOne) SetNillablePayoutAccountName(v *string) *FleetMemberUpdateOne {
	if v != nil {
		_u.SetPayoutAccountName(*v)
	}
	return _u
}

// ClearPayoutAccountName clears the value of the "payout_account_name" field.
func (_u *FleetMemberUpdateOne) ClearPayoutAccountName() *FleetMemberUpdateOne {
	_u.mutation.ClearPayoutAccountName()
	return _u
}

// SetPayoutRecipientCode sets the "payout_recipient_code" field.
func (_u *FleetMemberUpdateOne) SetPayoutRecipientCode(v string) *FleetMemberUpdateOne {
	_u.mutation.SetPayoutRecipientCode(v)
	return _u
}

// SetNillablePayoutRecipientCode sets the "payout_recipient_code" field if the given value is not nil.
func (_u *FleetMemberUpdateOne) SetNillablePayoutRecipientCode(v *string) *FleetMemberUpdateOne {
	if v != nil {
		_u.SetPayoutRecipientCode(*v)
	}
	return _u
}

// ClearPayoutRecipientCode clears the value of the "payout_recipient_code" field.
func (_u *FleetMemberUpdateOne) ClearPayoutRecipientCode() *FleetMemberUpdateOne {
	_u.mutation.ClearPayoutRecipientCode()
	return _u
}

// SetPayoutStatus sets the "payout_status" field.
func (_u *FleetMemberUpdateOne) SetPayoutStatus(v fleetmember.PayoutStatus) *FleetMemberUpdateOne {
	_u.mutation.SetPayoutStatus(v)
	return _u
}

// SetNillablePayoutStatus sets the "payout_status" field if the given value is not nil.
func (_u *FleetMemberUpdateOne) SetNillablePayoutStatus(v *fleetmember.PayoutStatus) *FleetMemberUpdateOne {
	if v != nil {
		_u.SetPayoutStatus(*v)
	}
	return _u
}

// SetFleet sets the "fleet" edge to the Fleet entity.
func (_u *FleetMemberUpdateOne) SetFleet(v *Fleet) *FleetMemberUpdateOne {
	return _u.SetFleetID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *FleetMemberUpdateOne) SetUser(v *User) *FleetMemberUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetVehicle sets the "vehicle" edge to the Vehicle entity.
func (_u *FleetMemberUpdateOne) SetVehicle(v *Vehicle) *FleetMemberUpdateOne {
	return _u.SetVehicleID(v.ID)
}

// AddAssignmentIDs adds the "assignments" edge to the TaskAssignment entity by IDs.
func (_u *FleetMemberUpdateOne) AddAssignmentIDs(ids ...uuid.UUID) *FleetMemberUpdateOne {
	_u.mutation.AddAssignmentIDs(ids...)
	return _u
}

// AddAssignments adds the "assignments" edges to the TaskAssignment entity.
func (_u *FleetMemberUpdateOne) AddAssignments(v ...*TaskAssignment) *FleetMemberUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAssignmentIDs(ids...)
}

// AddRatingIDs adds the "ratings" edge to the RiderRating entity by IDs.
func (_u *FleetMemberUpdateOne) AddRatingIDs(ids ...uuid.UUID) *FleetMemberUpdateOne {
	_u.mutation.AddRatingIDs(ids...)
	return _u
}

// AddRatings adds the "ratings" edges to the RiderRating entity.
func (_u *FleetMemberUpdateOne) AddRatings(v ...*RiderRating) *FleetMemberUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRatingIDs(ids...)
}

// Mutation returns the FleetMemberMutation object of the builder.
func (_u *FleetMemberUpdateOne) Mutation() *FleetMemberMutation {
	return _u.mutation
}

// ClearFleet clears the "fleet" edge to the Fleet entity.
func (_u *FleetMemberUpdateOne) ClearFleet() *FleetMemberUpdateOne {
	_u.mutation.ClearFleet()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *FleetMemberUpdateOne) ClearUser() *FleetMemberUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearVehicle clears the "vehicle" edge to the Vehicle entity.
func (_u *FleetMemberUpdateOne) ClearVehicle() *FleetMemberUpdateOne {
	_u.mutation.ClearVehicle()
	return _u
}

// ClearAssignments clears all "assignments" edges to the TaskAssignment entity.
func (_u *FleetMemberUpdateOne) ClearAssignments() *FleetMemberUpdateOne {
	_u.mutation.ClearAssignments()
	return _u
}

// RemoveAssignmentIDs removes the "assignments" edge to TaskAssignment entities by IDs.
func (_u *FleetMemberUpdateOne) RemoveAssignmentIDs(ids ...uuid.UUID) *FleetMemberUpdateOne {
	_u.mutation.RemoveAssignmentIDs(ids...)
	return _u
}

// RemoveAssignments removes "assignments" edges to TaskAssignment entities.
func (_u *FleetMemberUpdateOne) RemoveAssignments(v ...*TaskAssignment) *FleetMemberUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAssignmentIDs(ids...)
}

// ClearRatings clears all "ratings" edges to the RiderRating entity.
func (_u *FleetMemberUpdateOne) ClearRatings() *FleetMemberUpdateOne {
	_u.mutation.ClearRatings()
	return _u
}

// RemoveRatingIDs removes the "ratings" edge to RiderRating entities by IDs.
func (_u *FleetMemberUpdateOne) RemoveRatingIDs(ids ...uuid.UUID) *FleetMemberUpdateOne {
	_u.mutation.RemoveRatingIDs(ids...)
	return _u
}

// RemoveRatings removes "ratings" edges to RiderRating entities.
func (_u *FleetMemberUpdateOne) RemoveRatings(v ...*RiderRating) *FleetMemberUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRatingIDs(ids...)
}

// Where appends a list predicates to the FleetMemberUpdate builder.
func (_u *FleetMemberUpdateOne) Where(ps ...predicate.FleetMember) *FleetMemberUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FleetMemberUpdateOne) Select(field string, fields ...string) *FleetMemberUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FleetMember entity.
func (_u *FleetMemberUpdateOne) Save(ctx context.Context) (*FleetMember, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FleetMemberUpdateOne) SaveX(ctx context.Context) *FleetMember {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FleetMemberUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FleetMemberUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FleetMemberUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := fleetmember.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FleetMemberUpdateOne) check() error {
	if v, ok := _u.mutation.PayoutMethod(); ok {
		if err := fleetmember.PayoutMethodValidator(v); err != nil {
			return &ValidationError{Name: "payout_method", err: fmt.Errorf(`ent: validator failed for field "FleetMember.payout_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PayoutStatus(); ok {
		if err := fleetmember.PayoutStatusValidator(v); err != nil {
			return &ValidationError{Name: "payout_status", err: fmt.Errorf(`ent: validator failed for field "FleetMember.payout_status": %w`, err)}
		}
	}
	if _u.mutation.FleetCleared() && len(_u.mutation.FleetIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FleetMember.fleet"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FleetMember.user"`)
	}
	return nil
}

func (_u *FleetMemberUpdateOne) sqlSave(ctx context.Context) (_node *FleetMember, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(fleetmember.Table, fleetmember.Columns, sqlgraph.NewFieldSpec(fleetmember.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FleetMember.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, fleetmember.FieldID)
		for _, f := range fields {
			if !fleetmember.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != fleetmember.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(fleetmember.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.DriverCode(); ok {
		_spec.SetField(fleetmember.FieldDriverCode, field.TypeString, value)
	}
	if _u.mutation.DriverCodeCleared() {
		_spec.ClearField(fleetmember.FieldDriverCode, field.TypeString)
	}
	if value, ok := _u.mutation.IDNumber(); ok {
		_spec.SetField(fleetmember.FieldIDNumber, field.TypeString, value)
	}
	if _u.mutation.IDNumberCleared() {
		_spec.ClearField(fleetmember.FieldIDNumber, field.TypeString)
	}
	if value, ok := _u.mutation.LicenseNo(); ok {
		_spec.SetField(fleetmember.FieldLicenseNo, field.TypeString, value)
	}
	if _u.mutation.LicenseNoCleared() {
		_spec.ClearField(fleetmember.FieldLicenseNo, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(fleetmember.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.InviteCode(); ok {
		_spec.SetField(fleetmember.FieldInviteCode, field.TypeString, value)
	}
	if _u.mutation.InviteCodeCleared() {
		_spec.ClearField(fleetmember.FieldInviteCode, field.TypeString)
	}
	if value, ok := _u.mutation.KycSubmittedAt(); ok {
		_spec.SetField(fleetmember.FieldKycSubmittedAt, field.TypeTime, value)
	}
	if _u.mutation.KycSubmittedAtCleared() {
		_spec.ClearField(fleetmember.FieldKycSubmittedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(fleetmember.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(fleetmember.FieldReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ReviewedBy(); ok {
		_spec.SetField(fleetmember.FieldReviewedBy, field.TypeString, value)
	}
	if _u.mutation.ReviewedByCleared() {
		_spec.ClearField(fleetmember.FieldReviewedBy, field.TypeString)
	}
	if value, ok := _u.mutation.RejectionReason(); ok {
		_spec.SetField(fleetmember.FieldRejectionReason, field.TypeString, value)
	}
	if _u.mutation.RejectionReasonCleared() {
		_spec.ClearField(fleetmember.FieldRejectionReason, field.TypeString)
	}
	if value, ok := _u.mutation.OnboardingSource(); ok {
		_spec.SetField(fleetmember.FieldOnboardingSource, field.TypeString, value)
	}
	if _u.mutation.OnboardingSourceCleared() {
		_spec.ClearField(fleetmember.FieldOnboardingSource, field.TypeString)
	}
	if value, ok := _u.mutation.IDPassportAttachment(); ok {
		_spec.SetField(fleetmember.FieldIDPassportAttachment, field.TypeString, value)
	}
	if _u.mutation.IDPassportAttachmentCleared() {
		_spec.ClearField(fleetmember.FieldIDPassportAttachment, field.TypeString)
	}
	if value, ok := _u.mutation.RiderPhoto(); ok {
		_spec.SetField(fleetmember.FieldRiderPhoto, field.TypeString, value)
	}
	if _u.mutation.RiderPhotoCleared() {
		_spec.ClearField(fleetmember.FieldRiderPhoto, field.TypeString)
	}
	if value, ok := _u.mutation.JoinedAt(); ok {
		_spec.SetField(fleetmember.FieldJoinedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SuspendedAt(); ok {
		_spec.SetField(fleetmember.FieldSuspendedAt, field.TypeTime, value)
	}
	if _u.mutation.SuspendedAtCleared() {
		_spec.ClearField(fleetmember.FieldSuspendedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(fleetmember.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.SpecializationTags(); ok {
		_spec.SetField(fleetmember.FieldSpecializationTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSpecializationTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, fleetmember.FieldSpecializationTags, value)
		})
	}
	if value, ok := _u.mutation.HasColdStorage(); ok {
		_spec.SetField(fleetmember.FieldHasColdStorage, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MaxWeightCapacityKg(); ok {
		_spec.SetField(fleetmember.FieldMaxWeightCapacityKg, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxWeightCapacityKg(); ok {
		_spec.AddField(fleetmember.FieldMaxWeightCapacityKg, field.TypeFloat64, value)
	}
	if _u.mutation.MaxWeightCapacityKgCleared() {
		_spec.ClearField(fleetmember.FieldMaxWeightCapacityKg, field.TypeFloat64)
	}
	if value, ok := _u.mutation.AverageRating(); ok {
		_spec.SetField(fleetmember.FieldAverageRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAverageRating(); ok {
		_spec.AddField(fleetmember.FieldAverageRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalRatings(); ok {
		_spec.SetField(fleetmember.FieldTotalRatings, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalRatings(); ok {
		_spec.AddField(fleetmember.FieldTotalRatings, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(fleetmember.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PayoutMethod(); ok {
		_spec.SetField(fleetmember.FieldPayoutMethod, field.TypeEnum, value)
	}
	if _u.mutation.PayoutMethodCleared() {
		_spec.ClearField(fleetmember.FieldPayoutMethod, field.TypeEnum)
	}
	if value, ok := _u.mutation.PayoutPhone(); ok {
		_spec.SetField(fleetmember.FieldPayoutPhone, field.TypeString, value)
	}
	if _u.mutation.PayoutPhoneCleared() {
		_spec.ClearField(fleetmember.FieldPayoutPhone, field.TypeString)
	}
	if value, ok := _u.mutation.PayoutBankCode(); ok {
		_spec.SetField(fleetmember.FieldPayoutBankCode, field.TypeString, value)
	}
	if _u.mutation.PayoutBankCodeCleared() {
		_spec.ClearField(fleetmember.FieldPayoutBankCode, field.TypeString)
	}
	if value, ok := _u.mutation.PayoutAccountNumber(); ok {
		_spec.SetField(fleetmember.FieldPayoutAccountNumber, field.TypeString, value)
	}
	if _u.mutation.PayoutAccountNumberCleared() {
		_spec.ClearField(fleetmember.FieldPayoutAccountNumber, field.TypeString)
	}
	if value, ok := _u.mutation.PayoutAccountName(); ok {
		_spec.SetField(fleetmember.FieldPayoutAccountName, field.TypeString, value)
	}
	if _u.mutation.PayoutAccountNameCleared() {
		_spec.ClearField(fleetmember.FieldPayoutAccountName, field.TypeString)
	}
	if value, ok := _u.mutation.PayoutRecipientCode(); ok {
		_spec.SetField(fleetmember.FieldPayoutRecipientCode, field.TypeString, value)
	}
	if _u.mutation.PayoutRecipientCodeCleared() {
		_spec.ClearField(fleetmember.FieldPayoutRecipientCode, field.TypeString)
	}
	if value, ok := _u.mutation.PayoutStatus(); ok {
		_spec.SetField(fleetmember.FieldPayoutStatus, field.TypeEnum, value)
	}
	if _u.mutation.FleetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   fleetmember.FleetTable,
			Columns: []string{fleetmember.FleetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fleet.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FleetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   fleetmember.FleetTable,
			Columns: []string{fleetmember.FleetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fleet.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   fleetmember.UserTable,
			Columns: []string{fleetmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   fleetmember.UserTable,
			Columns: []string{fleetmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VehicleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   fleetmember.VehicleTable,
			Columns: []string{fleetmember.VehicleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vehicle.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VehicleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   fleetmember.VehicleTable,
			Columns: []string{fleetmember.VehicleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vehicle.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fleetmember.AssignmentsTable,
			Columns: []string{fleetmember.AssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskassignment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAssignmentsIDs(); len(nodes) > 0 && !_u.mutation.AssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fleetmember.AssignmentsTable,
			Columns: []string{fleetmember.AssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssignmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fleetmember.AssignmentsTable,
			Columns: []string{fleetmember.AssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RatingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fleetmember.RatingsTable,
			Columns: []string{fleetmember.RatingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(riderrating.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRatingsIDs(); len(nodes) > 0 && !_u.mutation.RatingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fleetmember.RatingsTable,
			Columns: []string{fleetmember.RatingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(riderrating.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RatingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   fleetmember.RatingsTable,
			Columns: []string{fleetmember.RatingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(riderrating.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &FleetMember{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{fleetmember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
