// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/logistics-service/internal/ent/logisticsnotification"
	"github.com/bengobox/logistics-service/internal/ent/predicate"
)

// LogisticsNotificationDelete is the builder for deleting a LogisticsNotification entity.
type LogisticsNotificationDelete struct {
	config
	hooks    []Hook
	mutation *LogisticsNotificationMutation
}

// Where appends a list predicates to the LogisticsNotificationDelete builder.
func (_d *LogisticsNotificationDelete) Where(ps ...predicate.LogisticsNotification) *LogisticsNotificationDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *LogisticsNotificationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *LogisticsNotificationDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *LogisticsNotificationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(logisticsnotification.Table, sqlgraph.NewFieldSpec(logisticsnotification.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// LogisticsNotificationDeleteOne is the builder for deleting a single LogisticsNotification entity.
type LogisticsNotificationDeleteOne struct {
	_d *LogisticsNotificationDelete
}

// Where appends a list predicates to the LogisticsNotificationDelete builder.
func (_d *LogisticsNotificationDeleteOne) Where(ps ...predicate.LogisticsNotification) *LogisticsNotificationDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *LogisticsNotificationDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{logisticsnotification.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *LogisticsNotificationDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
