// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/logistics-service/internal/ent/predicate"
	"github.com/bengobox/logistics-service/internal/ent/pricingrule"
	"github.com/google/uuid"
)

// PricingRuleUpdate is the builder for updating PricingRule entities.
type PricingRuleUpdate struct {
	config
	hooks    []Hook
	mutation *PricingRuleMutation
}

// Where appends a list predicates to the PricingRuleUpdate builder.
func (_u *PricingRuleUpdate) Where(ps ...predicate.PricingRule) *PricingRuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *PricingRuleUpdate) SetTenantID(v uuid.UUID) *PricingRuleUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *PricingRuleUpdate) SetNillableTenantID(v *uuid.UUID) *PricingRuleUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *PricingRuleUpdate) SetName(v string) *PricingRuleUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PricingRuleUpdate) SetNillableName(v *string) *PricingRuleUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetRuleType sets the "rule_type" field.
func (_u *PricingRuleUpdate) SetRuleType(v pricingrule.RuleType) *PricingRuleUpdate {
	_u.mutation.SetRuleType(v)
	return _u
}

// SetNillableRuleType sets the "rule_type" field if the given value is not nil.
func (_u *PricingRuleUpdate) SetNillableRuleType(v *pricingrule.RuleType) *PricingRuleUpdate {
	if v != nil {
		_u.SetRuleType(*v)
	}
	return _u
}

// SetBaseFee sets the "base_fee" field.
func (_u *PricingRuleUpdate) SetBaseFee(v float64) *PricingRuleUpdate {
	_u.mutation.ResetBaseFee()
	_u.mutation.SetBaseFee(v)
	return _u
}

// SetNillableBaseFee sets the "base_fee" field if the given value is not nil.
func (_u *PricingRuleUpdate) SetNillableBaseFee(v *float64) *PricingRuleUpdate {
	if v != nil {
		_u.SetBaseFee(*v)
	}
	return _u
}

// AddBaseFee adds value to the "base_fee" field.
func (_u *PricingRuleUpdate) AddBaseFee(v float64) *PricingRuleUpdate {
	_u.mutation.AddBaseFee(v)
	return _u
}

// SetPerKmRate sets the "per_km_rate" field.
func (_u *PricingRuleUpdate) SetPerKmRate(v float64) *PricingRuleUpdate {
	_u.mutation.ResetPerKmRate()
	_u.mutation.SetPerKmRate(v)
	return _u
}

// SetNillablePerKmRate sets the "per_km_rate" field if the given value is not nil.
func (_u *PricingRuleUpdate) SetNillablePerKmRate(v *float64) *PricingRuleUpdate {
	if v != nil {
		_u.SetPerKmRate(*v)
	}
	return _u
}

// AddPerKmRate adds value to the "per_km_rate" field.
func (_u *PricingRuleUpdate) AddPerKmRate(v float64) *PricingRuleUpdate {
	_u.mutation.AddPerKmRate(v)
	return _u
}

// ClearPerKmRate clears the value of the "per_km_rate" field.
func (_u *PricingRuleUpdate) ClearPerKmRate() *PricingRuleUpdate {
	_u.mutation.ClearPerKmRate()
	return _u
}

// SetPerKgRate sets the "per_kg_rate" field.
func (_u *PricingRuleUpdate) SetPerKgRate(v float64) *PricingRuleUpdate {
	_u.mutation.ResetPerKgRate()
	_u.mutation.SetPerKgRate(v)
	return _u
}

// SetNillablePerKgRate sets the "per_kg_rate" field if the given value is not nil.
func (_u *PricingRuleUpdate) SetNillablePerKgRate(v *float64) *PricingRuleUpdate {
	if v != nil {
		_u.SetPerKgRate(*v)
	}
	return _u
}

// AddPerKgRate adds value to the "per_kg_rate" field.
func (_u *PricingRuleUpdate) AddPerKgRate(v float64) *PricingRuleUpdate {
	_u.mutation.AddPerKgRate(v)
	return _u
}

// ClearPerKgRate clears the value of the "per_kg_rate" field.
func (_u *PricingRuleUpdate) ClearPerKgRate() *PricingRuleUpdate {
	_u.mutation.ClearPerKgRate()
	return _u
}

// SetSurgeMultiplier sets the "surge_multiplier" field.
func (_u *PricingRuleUpdate) SetSurgeMultiplier(v float64) *PricingRuleUpdate {
	_u.mutation.ResetSurgeMultiplier()
	_u.mutation.SetSurgeMultiplier(v)
	return _u
}

// SetNillableSurgeMultiplier sets the "surge_multiplier" field if the given value is not nil.
func (_u *PricingRuleUpdate) SetNillableSurgeMultiplier(v *float64) *PricingRuleUpdate {
	if v != nil {
		_u.SetSurgeMultiplier(*v)
	}
	return _u
}

// AddSurgeMultiplier adds value to the "surge_multiplier" field.
func (_u *PricingRuleUpdate) AddSurgeMultiplier(v float64) *PricingRuleUpdate {
	_u.mutation.AddSurgeMultiplier(v)
	return _u
}

// ClearSurgeMultiplier clears the value of the "surge_multiplier" field.
func (_u *PricingRuleUpdate) ClearSurgeMultiplier() *PricingRuleUpdate {
	_u.mutation.ClearSurgeMultiplier()
	return _u
}

// SetTimeWindows sets the "time_windows" field.
func (_u *PricingRuleUpdate) SetTimeWindows(v []map[string]interface{}) *PricingRuleUpdate {
	_u.mutation.SetTimeWindows(v)
	return _u
}

// AppendTimeWindows appends value to the "time_windows" field.
func (_u *PricingRuleUpdate) AppendTimeWindows(v []map[string]interface{}) *PricingRuleUpdate {
	_u.mutation.AppendTimeWindows(v)
	return _u
}

// ClearTimeWindows clears the value of the "time_windows" field.
func (_u *PricingRuleUpdate) ClearTimeWindows() *PricingRuleUpdate {
	_u.mutation.ClearTimeWindows()
	return _u
}

// SetDistanceTiers sets the "distance_tiers" field.
func (_u *PricingRuleUpdate) SetDistanceTiers(v []map[string]interface{}) *PricingRuleUpdate {
	_u.mutation.SetDistanceTiers(v)
	return _u
}

// AppendDistanceTiers appends value to the "distance_tiers" field.
func (_u *PricingRuleUpdate) AppendDistanceTiers(v []map[string]interface{}) *PricingRuleUpdate {
	_u.mutation.AppendDistanceTiers(v)
	return _u
}

// ClearDistanceTiers clears the value of the "distance_tiers" field.
func (_u *PricingRuleUpdate) ClearDistanceTiers() *PricingRuleUpdate {
	_u.mutation.ClearDistanceTiers()
	return _u
}

// SetPriority sets the "priority" field.
func (_u *PricingRuleUpdate) SetPriority(v int) *PricingRuleUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *PricingRuleUpdate) SetNillablePriority(v *int) *PricingRuleUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *PricingRuleUpdate) AddPriority(v int) *PricingRuleUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *PricingRuleUpdate) SetIsActive(v bool) *PricingRuleUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *PricingRuleUpdate) SetNillableIsActive(v *bool) *PricingRuleUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PricingRuleUpdate) SetUpdatedAt(v time.Time) *PricingRuleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PricingRuleMutation object of the builder.
func (_u *PricingRuleUpdate) Mutation() *PricingRuleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PricingRuleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PricingRuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PricingRuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PricingRuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PricingRuleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := pricingrule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PricingRuleUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := pricingrule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PricingRule.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RuleType(); ok {
		if err := pricingrule.RuleTypeValidator(v); err != nil {
			return &ValidationError{Name: "rule_type", err: fmt.Errorf(`ent: validator failed for field "PricingRule.rule_type": %w`, err)}
		}
	}
	return nil
}

func (_u *PricingRuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pricingrule.Table, pricingrule.Columns, sqlgraph.NewFieldSpec(pricingrule.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(pricingrule.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(pricingrule.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.RuleType(); ok {
		_spec.SetField(pricingrule.FieldRuleType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.BaseFee(); ok {
		_spec.SetField(pricingrule.FieldBaseFee, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBaseFee(); ok {
		_spec.AddField(pricingrule.FieldBaseFee, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PerKmRate(); ok {
		_spec.SetField(pricingrule.FieldPerKmRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPerKmRate(); ok {
		_spec.AddField(pricingrule.FieldPerKmRate, field.TypeFloat64, value)
	}
	if _u.mutation.PerKmRateCleared() {
		_spec.ClearField(pricingrule.FieldPerKmRate, field.TypeFloat64)
	}
	if value, ok := _u.mutation.PerKgRate(); ok {
		_spec.SetField(pricingrule.FieldPerKgRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPerKgRate(); ok {
		_spec.AddField(pricingrule.FieldPerKgRate, field.TypeFloat64, value)
	}
	if _u.mutation.PerKgRateCleared() {
		_spec.ClearField(pricingrule.FieldPerKgRate, field.TypeFloat64)
	}
	if value, ok := _u.mutation.SurgeMultiplier(); ok {
		_spec.SetField(pricingrule.FieldSurgeMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSurgeMultiplier(); ok {
		_spec.AddField(pricingrule.FieldSurgeMultiplier, field.TypeFloat64, value)
	}
	if _u.mutation.SurgeMultiplierCleared() {
		_spec.ClearField(pricingrule.FieldSurgeMultiplier, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TimeWindows(); ok {
		_spec.SetField(pricingrule.FieldTimeWindows, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTimeWindows(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, pricingrule.FieldTimeWindows, value)
		})
	}
	if _u.mutation.TimeWindowsCleared() {
		_spec.ClearField(pricingrule.FieldTimeWindows, field.TypeJSON)
	}
	if value, ok := _u.mutation.DistanceTiers(); ok {
		_spec.SetField(pricingrule.FieldDistanceTiers, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDistanceTiers(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, pricingrule.FieldDistanceTiers, value)
		})
	}
	if _u.mutation.DistanceTiersCleared() {
		_spec.ClearField(pricingrule.FieldDistanceTiers, field.TypeJSON)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(pricingrule.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(pricingrule.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(pricingrule.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(pricingrule.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pricingrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PricingRuleUpdateOne is the builder for updating a single PricingRule entity.
type PricingRuleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PricingRuleMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *PricingRuleUpdateOne) SetTenantID(v uuid.UUID) *PricingRuleUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *PricingRuleUpdateOne) SetNillableTenantID(v *uuid.UUID) *PricingRuleUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *PricingRuleUpdateOne) SetName(v string) *PricingRuleUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PricingRuleUpdateOne) SetNillableName(v *string) *PricingRuleUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetRuleType sets the "rule_type" field.
func (_u *PricingRuleUpdateOne) SetRuleType(v pricingrule.RuleType) *PricingRuleUpdateOne {
	_u.mutation.SetRuleType(v)
	return _u
}

// SetNillableRuleType sets the "rule_type" field if the given value is not nil.
func (_u *PricingRuleUpdateOne) SetNillableRuleType(v *pricingrule.RuleType) *PricingRuleUpdateOne {
	if v != nil {
		_u.SetRuleType(*v)
	}
	return _u
}

// SetBaseFee sets the "base_fee" field.
func (_u *PricingRuleUpdateOne) SetBaseFee(v float64) *PricingRuleUpdateOne {
	_u.mutation.ResetBaseFee()
	_u.mutation.SetBaseFee(v)
	return _u
}

// SetNillableBaseFee sets the "base_fee" field if the given value is not nil.
func (_u *PricingRuleUpdateOne) SetNillableBaseFee(v *float64) *PricingRuleUpdateOne {
	if v != nil {
		_u.SetBaseFee(*v)
	}
	return _u
}

// AddBaseFee adds value to the "base_fee" field.
func (_u *PricingRuleUpdateOne) AddBaseFee(v float64) *PricingRuleUpdateOne {
	_u.mutation.AddBaseFee(v)
	return _u
}

// SetPerKmRate sets the "per_km_rate" field.
func (_u *PricingRuleUpdateOne) SetPerKmRate(v float64) *PricingRuleUpdateOne {
	_u.mutation.ResetPerKmRate()
	_u.mutation.SetPerKmRate(v)
	return _u
}

// SetNillablePerKmRate sets the "per_km_rate" field if the given value is not nil.
func (_u *PricingRuleUpdateOne) SetNillablePerKmRate(v *float64) *PricingRuleUpdateOne {
	if v != nil {
		_u.SetPerKmRate(*v)
	}
	return _u
}

// AddPerKmRate adds value to the "per_km_rate" field.
func (_u *PricingRuleUpdateOne) AddPerKmRate(v float64) *PricingRuleUpdateOne {
	_u.mutation.AddPerKmRate(v)
	return _u
}

// ClearPerKmRate clears the value of the "per_km_rate" field.
func (_u *PricingRuleUpdateOne) ClearPerKmRate() *PricingRuleUpdateOne {
	_u.mutation.ClearPerKmRate()
	return _u
}

// SetPerKgRate sets the "per_kg_rate" field.
func (_u *PricingRuleUpdateOne) SetPerKgRate(v float64) *PricingRuleUpdateOne {
	_u.mutation.ResetPerKgRate()
	_u.mutation.SetPerKgRate(v)
	return _u
}

// SetNillablePerKgRate sets the "per_kg_rate" field if the given value is not nil.
func (_u *PricingRuleUpdateOne) SetNillablePerKgRate(v *float64) *PricingRuleUpdateOne {
	if v != nil {
		_u.SetPerKgRate(*v)
	}
	return _u
}

// AddPerKgRate adds value to the "per_kg_rate" field.
func (_u *PricingRuleUpdateOne) AddPerKgRate(v float64) *PricingRuleUpdateOne {
	_u.mutation.AddPerKgRate(v)
	return _u
}

// ClearPerKgRate clears the value of the "per_kg_rate" field.
func (_u *PricingRuleUpdateOne) ClearPerKgRate() *PricingRuleUpdateOne {
	_u.mutation.ClearPerKgRate()
	return _u
}

// SetSurgeMultiplier sets the "surge_multiplier" field.
func (_u *PricingRuleUpdateOne) SetSurgeMultiplier(v float64) *PricingRuleUpdateOne {
	_u.mutation.ResetSurgeMultiplier()
	_u.mutation.SetSurgeMultiplier(v)
	return _u
}

// SetNillableSurgeMultiplier sets the "surge_multiplier" field if the given value is not nil.
func (_u *PricingRuleUpdateOne) SetNillableSurgeMultiplier(v *float64) *PricingRuleUpdateOne {
	if v != nil {
		_u.SetSurgeMultiplier(*v)
	}
	return _u
}

// AddSurgeMultiplier adds value to the "surge_multiplier" field.
func (_u *PricingRuleUpdateOne) AddSurgeMultiplier(v float64) *PricingRuleUpdateOne {
	_u.mutation.AddSurgeMultiplier(v)
	return _u
}

// ClearSurgeMultiplier clears the value of the "surge_multiplier" field.
func (_u *PricingRuleUpdateOne) ClearSurgeMultiplier() *PricingRuleUpdateOne {
	_u.mutation.ClearSurgeMultiplier()
	return _u
}

// SetTimeWindows sets the "time_windows" field.
func (_u *PricingRuleUpdateOne) SetTimeWindows(v []map[string]interface{}) *PricingRuleUpdateOne {
	_u.mutation.SetTimeWindows(v)
	return _u
}

// AppendTimeWindows appends value to the "time_windows" field.
func (_u *PricingRuleUpdateOne) AppendTimeWindows(v []map[string]interface{}) *PricingRuleUpdateOne {
	_u.mutation.AppendTimeWindows(v)
	return _u
}

// ClearTimeWindows clears the value of the "time_windows" field.
func (_u *PricingRuleUpdateOne) ClearTimeWindows() *PricingRuleUpdateOne {
	_u.mutation.ClearTimeWindows()
	return _u
}

// SetDistanceTiers sets the "distance_tiers" field.
func (_u *PricingRuleUpdateOne) SetDistanceTiers(v []map[string]interface{}) *PricingRuleUpdateOne {
	_u.mutation.SetDistanceTiers(v)
	return _u
}

// AppendDistanceTiers appends value to the "distance_tiers" field.
func (_u *PricingRuleUpdateOne) AppendDistanceTiers(v []map[string]interface{}) *PricingRuleUpdateOne {
	_u.mutation.AppendDistanceTiers(v)
	return _u
}

// ClearDistanceTiers clears the value of the "distance_tiers" field.
func (_u *PricingRuleUpdateOne) ClearDistanceTiers() *PricingRuleUpdateOne {
	_u.mutation.ClearDistanceTiers()
	return _u
}

// SetPriority sets the "priority" field.
func (_u *PricingRuleUpdateOne) SetPriority(v int) *PricingRuleUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *PricingRuleUpdateOne) SetNillablePriority(v *int) *PricingRuleUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *PricingRuleUpdateOne) AddPriority(v int) *PricingRuleUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *PricingRuleUpdateOne) SetIsActive(v bool) *PricingRuleUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *PricingRuleUpdateOne) SetNillableIsActive(v *bool) *PricingRuleUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PricingRuleUpdateOne) SetUpdatedAt(v time.Time) *PricingRuleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PricingRuleMutation object of the builder.
func (_u *PricingRuleUpdateOne) Mutation() *PricingRuleMutation {
	return _u.mutation
}

// Where appends a list predicates to the PricingRuleUpdate builder.
func (_u *PricingRuleUpdateOne) Where(ps ...predicate.PricingRule) *PricingRuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PricingRuleUpdateOne) Select(field string, fields ...string) *PricingRuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PricingRule entity.
func (_u *PricingRuleUpdateOne) Save(ctx context.Context) (*PricingRule, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PricingRuleUpdateOne) SaveX(ctx context.Context) *PricingRule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PricingRuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PricingRuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PricingRuleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := pricingrule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PricingRuleUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := pricingrule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PricingRule.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RuleType(); ok {
		if err := pricingrule.RuleTypeValidator(v); err != nil {
			return &ValidationError{Name: "rule_type", err: fmt.Errorf(`ent: validator failed for field "PricingRule.rule_type": %w`, err)}
		}
	}
	return nil
}

func (_u *PricingRuleUpdateOne) sqlSave(ctx context.Context) (_node *PricingRule, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pricingrule.Table, pricingrule.Columns, sqlgraph.NewFieldSpec(pricingrule.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PricingRule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pricingrule.FieldID)
		for _, f := range fields {
			if !pricingrule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pricingrule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(pricingrule.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(pricingrule.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.RuleType(); ok {
		_spec.SetField(pricingrule.FieldRuleType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.BaseFee(); ok {
		_spec.SetField(pricingrule.FieldBaseFee, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBaseFee(); ok {
		_spec.AddField(pricingrule.FieldBaseFee, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PerKmRate(); ok {
		_spec.SetField(pricingrule.FieldPerKmRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPerKmRate(); ok {
		_spec.AddField(pricingrule.FieldPerKmRate, field.TypeFloat64, value)
	}
	if _u.mutation.PerKmRateCleared() {
		_spec.ClearField(pricingrule.FieldPerKmRate, field.TypeFloat64)
	}
	if value, ok := _u.mutation.PerKgRate(); ok {
		_spec.SetField(pricingrule.FieldPerKgRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPerKgRate(); ok {
		_spec.AddField(pricingrule.FieldPerKgRate, field.TypeFloat64, value)
	}
	if _u.mutation.PerKgRateCleared() {
		_spec.ClearField(pricingrule.FieldPerKgRate, field.TypeFloat64)
	}
	if value, ok := _u.mutation.SurgeMultiplier(); ok {
		_spec.SetField(pricingrule.FieldSurgeMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSurgeMultiplier(); ok {
		_spec.AddField(pricingrule.FieldSurgeMultiplier, field.TypeFloat64, value)
	}
	if _u.mutation.SurgeMultiplierCleared() {
		_spec.ClearField(pricingrule.FieldSurgeMultiplier, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TimeWindows(); ok {
		_spec.SetField(pricingrule.FieldTimeWindows, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTimeWindows(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, pricingrule.FieldTimeWindows, value)
		})
	}
	if _u.mutation.TimeWindowsCleared() {
		_spec.ClearField(pricingrule.FieldTimeWindows, field.TypeJSON)
	}
	if value, ok := _u.mutation.DistanceTiers(); ok {
		_spec.SetField(pricingrule.FieldDistanceTiers, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDistanceTiers(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, pricingrule.FieldDistanceTiers, value)
		})
	}
	if _u.mutation.DistanceTiersCleared() {
		_spec.ClearField(pricingrule.FieldDistanceTiers, field.TypeJSON)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(pricingrule.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(pricingrule.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(pricingrule.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(pricingrule.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &PricingRule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pricingrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
