// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/logistics-service/internal/ent/pricingrule"
	"github.com/google/uuid"
)

// PricingRuleCreate is the builder for creating a PricingRule entity.
type PricingRuleCreate struct {
	config
	mutation *PricingRuleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (_c *PricingRuleCreate) SetTenantID(v uuid.UUID) *PricingRuleCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *PricingRuleCreate) SetName(v string) *PricingRuleCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetRuleType sets the "rule_type" field.
func (_c *PricingRuleCreate) SetRuleType(v pricingrule.RuleType) *PricingRuleCreate {
	_c.mutation.SetRuleType(v)
	return _c
}

// SetNillableRuleType sets the "rule_type" field if the given value is not nil.
func (_c *PricingRuleCreate) SetNillableRuleType(v *pricingrule.RuleType) *PricingRuleCreate {
	if v != nil {
		_c.SetRuleType(*v)
	}
	return _c
}

// SetBaseFee sets the "base_fee" field.
func (_c *PricingRuleCreate) SetBaseFee(v float64) *PricingRuleCreate {
	_c.mutation.SetBaseFee(v)
	return _c
}

// SetNillableBaseFee sets the "base_fee" field if the given value is not nil.
func (_c *PricingRuleCreate) SetNillableBaseFee(v *float64) *PricingRuleCreate {
	if v != nil {
		_c.SetBaseFee(*v)
	}
	return _c
}

// SetPerKmRate sets the "per_km_rate" field.
func (_c *PricingRuleCreate) SetPerKmRate(v float64) *PricingRuleCreate {
	_c.mutation.SetPerKmRate(v)
	return _c
}

// SetNillablePerKmRate sets the "per_km_rate" field if the given value is not nil.
func (_c *PricingRuleCreate) SetNillablePerKmRate(v *float64) *PricingRuleCreate {
	if v != nil {
		_c.SetPerKmRate(*v)
	}
	return _c
}

// SetPerKgRate sets the "per_kg_rate" field.
func (_c *PricingRuleCreate) SetPerKgRate(v float64) *PricingRuleCreate {
	_c.mutation.SetPerKgRate(v)
	return _c
}

// SetNillablePerKgRate sets the "per_kg_rate" field if the given value is not nil.
func (_c *PricingRuleCreate) SetNillablePerKgRate(v *float64) *PricingRuleCreate {
	if v != nil {
		_c.SetPerKgRate(*v)
	}
	return _c
}

// SetSurgeMultiplier sets the "surge_multiplier" field.
func (_c *PricingRuleCreate) SetSurgeMultiplier(v float64) *PricingRuleCreate {
	_c.mutation.SetSurgeMultiplier(v)
	return _c
}

// SetNillableSurgeMultiplier sets the "surge_multiplier" field if the given value is not nil.
func (_c *PricingRuleCreate) SetNillableSurgeMultiplier(v *float64) *PricingRuleCreate {
	if v != nil {
		_c.SetSurgeMultiplier(*v)
	}
	return _c
}

// SetTimeWindows sets the "time_windows" field.
func (_c *PricingRuleCreate) SetTimeWindows(v []map[string]interface{}) *PricingRuleCreate {
	_c.mutation.SetTimeWindows(v)
	return _c
}

// SetDistanceTiers sets the "distance_tiers" field.
func (_c *PricingRuleCreate) SetDistanceTiers(v []map[string]interface{}) *PricingRuleCreate {
	_c.mutation.SetDistanceTiers(v)
	return _c
}

// SetPriority sets the "priority" field.
func (_c *PricingRuleCreate) SetPriority(v int) *PricingRuleCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *PricingRuleCreate) SetNillablePriority(v *int) *PricingRuleCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *PricingRuleCreate) SetIsActive(v bool) *PricingRuleCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *PricingRuleCreate) SetNillableIsActive(v *bool) *PricingRuleCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PricingRuleCreate) SetCreatedAt(v time.Time) *PricingRuleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PricingRuleCreate) SetNillableCreatedAt(v *time.Time) *PricingRuleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PricingRuleCreate) SetUpdatedAt(v time.Time) *PricingRuleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PricingRuleCreate) SetNillableUpdatedAt(v *time.Time) *PricingRuleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PricingRuleCreate) SetID(v uuid.UUID) *PricingRuleCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PricingRuleCreate) SetNillableID(v *uuid.UUID) *PricingRuleCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the PricingRuleMutation object of the builder.
func (_c *PricingRuleCreate) Mutation() *PricingRuleMutation {
	return _c.mutation
}

// Save creates the PricingRule in the database.
func (_c *PricingRuleCreate) Save(ctx context.Context) (*PricingRule, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PricingRuleCreate) SaveX(ctx context.Context) *PricingRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PricingRuleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PricingRuleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PricingRuleCreate) defaults() {
	if _, ok := _c.mutation.RuleType(); !ok {
		v := pricingrule.DefaultRuleType
		_c.mutation.SetRuleType(v)
	}
	if _, ok := _c.mutation.BaseFee(); !ok {
		v := pricingrule.DefaultBaseFee
		_c.mutation.SetBaseFee(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := pricingrule.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := pricingrule.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := pricingrule.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := pricingrule.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := pricingrule.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PricingRuleCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "PricingRule.tenant_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "PricingRule.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := pricingrule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PricingRule.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RuleType(); !ok {
		return &ValidationError{Name: "rule_type", err: errors.New(`ent: missing required field "PricingRule.rule_type"`)}
	}
	if v, ok := _c.mutation.RuleType(); ok {
		if err := pricingrule.RuleTypeValidator(v); err != nil {
			return &ValidationError{Name: "rule_type", err: fmt.Errorf(`ent: validator failed for field "PricingRule.rule_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BaseFee(); !ok {
		return &ValidationError{Name: "base_fee", err: errors.New(`ent: missing required field "PricingRule.base_fee"`)}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "PricingRule.priority"`)}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "PricingRule.is_active"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PricingRule.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PricingRule.updated_at"`)}
	}
	return nil
}

func (_c *PricingRuleCreate) sqlSave(ctx context.Context) (*PricingRule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PricingRuleCreate) createSpec() (*PricingRule, *sqlgraph.CreateSpec) {
	var (
		_node = &PricingRule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pricingrule.Table, sqlgraph.NewFieldSpec(pricingrule.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(pricingrule.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(pricingrule.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.RuleType(); ok {
		_spec.SetField(pricingrule.FieldRuleType, field.TypeEnum, value)
		_node.RuleType = value
	}
	if value, ok := _c.mutation.BaseFee(); ok {
		_spec.SetField(pricingrule.FieldBaseFee, field.TypeFloat64, value)
		_node.BaseFee = value
	}
	if value, ok := _c.mutation.PerKmRate(); ok {
		_spec.SetField(pricingrule.FieldPerKmRate, field.TypeFloat64, value)
		_node.PerKmRate = &value
	}
	if value, ok := _c.mutation.PerKgRate(); ok {
		_spec.SetField(pricingrule.FieldPerKgRate, field.TypeFloat64, value)
		_node.PerKgRate = &value
	}
	if value, ok := _c.mutation.SurgeMultiplier(); ok {
		_spec.SetField(pricingrule.FieldSurgeMultiplier, field.TypeFloat64, value)
		_node.SurgeMultiplier = &value
	}
	if value, ok := _c.mutation.TimeWindows(); ok {
		_spec.SetField(pricingrule.FieldTimeWindows, field.TypeJSON, value)
		_node.TimeWindows = value
	}
	if value, ok := _c.mutation.DistanceTiers(); ok {
		_spec.SetField(pricingrule.FieldDistanceTiers, field.TypeJSON, value)
		_node.DistanceTiers = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(pricingrule.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(pricingrule.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(pricingrule.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(pricingrule.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PricingRule.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PricingRuleUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *PricingRuleCreate) OnConflict(opts ...sql.ConflictOption) *PricingRuleUpsertOne {
	_c.conflict = opts
	return &PricingRuleUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PricingRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PricingRuleCreate) OnConflictColumns(columns ...string) *PricingRuleUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PricingRuleUpsertOne{
		create: _c,
	}
}

type (
	// PricingRuleUpsertOne is the builder for "upsert"-ing
	//  one PricingRule node.
	PricingRuleUpsertOne struct {
		create *PricingRuleCreate
	}

	// PricingRuleUpsert is the "OnConflict" setter.
	PricingRuleUpsert struct {
		*sql.UpdateSet
	}
)

// SetTenantID sets the "tenant_id" field.
func (u *PricingRuleUpsert) SetTenantID(v uuid.UUID) *PricingRuleUpsert {
	u.Set(pricingrule.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *PricingRuleUpsert) UpdateTenantID() *PricingRuleUpsert {
	u.SetExcluded(pricingrule.FieldTenantID)
	return u
}

// SetName sets the "name" field.
func (u *PricingRuleUpsert) SetName(v string) *PricingRuleUpsert {
	u.Set(pricingrule.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PricingRuleUpsert) UpdateName() *PricingRuleUpsert {
	u.SetExcluded(pricingrule.FieldName)
	return u
}

// SetRuleType sets the "rule_type" field.
func (u *PricingRuleUpsert) SetRuleType(v pricingrule.RuleType) *PricingRuleUpsert {
	u.Set(pricingrule.FieldRuleType, v)
	return u
}

// UpdateRuleType sets the "rule_type" field to the value that was provided on create.
func (u *PricingRuleUpsert) UpdateRuleType() *PricingRuleUpsert {
	u.SetExcluded(pricingrule.FieldRuleType)
	return u
}

// SetBaseFee sets the "base_fee" field.
func (u *PricingRuleUpsert) SetBaseFee(v float64) *PricingRuleUpsert {
	u.Set(pricingrule.FieldBaseFee, v)
	return u
}

// UpdateBaseFee sets the "base_fee" field to the value that was provided on create.
func (u *PricingRuleUpsert) UpdateBaseFee() *PricingRuleUpsert {
	u.SetExcluded(pricingrule.FieldBaseFee)
	return u
}

// AddBaseFee adds v to the "base_fee" field.
func (u *PricingRuleUpsert) AddBaseFee(v float64) *PricingRuleUpsert {
	u.Add(pricingrule.FieldBaseFee, v)
	return u
}

// SetPerKmRate sets the "per_km_rate" field.
func (u *PricingRuleUpsert) SetPerKmRate(v float64) *PricingRuleUpsert {
	u.Set(pricingrule.FieldPerKmRate, v)
	return u
}

// UpdatePerKmRate sets the "per_km_rate" field to the value that was provided on create.
func (u *PricingRuleUpsert) UpdatePerKmRate() *PricingRuleUpsert {
	u.SetExcluded(pricingrule.FieldPerKmRate)
	return u
}

// AddPerKmRate adds v to the "per_km_rate" field.
func (u *PricingRuleUpsert) AddPerKmRate(v float64) *PricingRuleUpsert {
	u.Add(pricingrule.FieldPerKmRate, v)
	return u
}

// ClearPerKmRate clears the value of the "per_km_rate" field.
func (u *PricingRuleUpsert) ClearPerKmRate() *PricingRuleUpsert {
	u.SetNull(pricingrule.FieldPerKmRate)
	return u
}

// SetPerKgRate sets the "per_kg_rate" field.
func (u *PricingRuleUpsert) SetPerKgRate(v float64) *PricingRuleUpsert {
	u.Set(pricingrule.FieldPerKgRate, v)
	return u
}

// UpdatePerKgRate sets the "per_kg_rate" field to the value that was provided on create.
func (u *PricingRuleUpsert) UpdatePerKgRate() *PricingRuleUpsert {
	u.SetExcluded(pricingrule.FieldPerKgRate)
	return u
}

// AddPerKgRate adds v to the "per_kg_rate" field.
func (u *PricingRuleUpsert) AddPerKgRate(v float64) *PricingRuleUpsert {
	u.Add(pricingrule.FieldPerKgRate, v)
	return u
}

// ClearPerKgRate clears the value of the "per_kg_rate" field.
func (u *PricingRuleUpsert) ClearPerKgRate() *PricingRuleUpsert {
	u.SetNull(pricingrule.FieldPerKgRate)
	return u
}

// SetSurgeMultiplier sets the "surge_multiplier" field.
func (u *PricingRuleUpsert) SetSurgeMultiplier(v float64) *PricingRuleUpsert {
	u.Set(pricingrule.FieldSurgeMultiplier, v)
	return u
}

// UpdateSurgeMultiplier sets the "surge_multiplier" field to the value that was provided on create.
func (u *PricingRuleUpsert) UpdateSurgeMultiplier() *PricingRuleUpsert {
	u.SetExcluded(pricingrule.FieldSurgeMultiplier)
	return u
}

// AddSurgeMultiplier adds v to the "surge_multiplier" field.
func (u *PricingRuleUpsert) AddSurgeMultiplier(v float64) *PricingRuleUpsert {
	u.Add(pricingrule.FieldSurgeMultiplier, v)
	return u
}

// ClearSurgeMultiplier clears the value of the "surge_multiplier" field.
func (u *PricingRuleUpsert) ClearSurgeMultiplier() *PricingRuleUpsert {
	u.SetNull(pricingrule.FieldSurgeMultiplier)
	return u
}

// SetTimeWindows sets the "time_windows" field.
func (u *PricingRuleUpsert) SetTimeWindows(v []map[string]interface{}) *PricingRuleUpsert {
	u.Set(pricingrule.FieldTimeWindows, v)
	return u
}

// UpdateTimeWindows sets the "time_windows" field to the value that was provided on create.
func (u *PricingRuleUpsert) UpdateTimeWindows() *PricingRuleUpsert {
	u.SetExcluded(pricingrule.FieldTimeWindows)
	return u
}

// ClearTimeWindows clears the value of the "time_windows" field.
func (u *PricingRuleUpsert) ClearTimeWindows() *PricingRuleUpsert {
	u.SetNull(pricingrule.FieldTimeWindows)
	return u
}

// SetDistanceTiers sets the "distance_tiers" field.
func (u *PricingRuleUpsert) SetDistanceTiers(v []map[string]interface{}) *PricingRuleUpsert {
	u.Set(pricingrule.FieldDistanceTiers, v)
	return u
}

// UpdateDistanceTiers sets the "distance_tiers" field to the value that was provided on create.
func (u *PricingRuleUpsert) UpdateDistanceTiers() *PricingRuleUpsert {
	u.SetExcluded(pricingrule.FieldDistanceTiers)
	return u
}

// ClearDistanceTiers clears the value of the "distance_tiers" field.
func (u *PricingRuleUpsert) ClearDistanceTiers() *PricingRuleUpsert {
	u.SetNull(pricingrule.FieldDistanceTiers)
	return u
}

// SetPriority sets the "priority" field.
func (u *PricingRuleUpsert) SetPriority(v int) *PricingRuleUpsert {
	u.Set(pricingrule.FieldPriority, v)
	return u
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *PricingRuleUpsert) UpdatePriority() *PricingRuleUpsert {
	u.SetExcluded(pricingrule.FieldPriority)
	return u
}

// AddPriority adds v to the "priority" field.
func (u *PricingRuleUpsert) AddPriority(v int) *PricingRuleUpsert {
	u.Add(pricingrule.FieldPriority, v)
	return u
}

// SetIsActive sets the "is_active" field.
func (u *PricingRuleUpsert) SetIsActive(v bool) *PricingRuleUpsert {
	u.Set(pricingrule.FieldIsActive, v)
	return u
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *PricingRuleUpsert) UpdateIsActive() *PricingRuleUpsert {
	u.SetExcluded(pricingrule.FieldIsActive)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PricingRuleUpsert) SetUpdatedAt(v time.Time) *PricingRuleUpsert {
	u.Set(pricingrule.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PricingRuleUpsert) UpdateUpdatedAt() *PricingRuleUpsert {
	u.SetExcluded(pricingrule.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.PricingRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(pricingrule.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PricingRuleUpsertOne) UpdateNewValues() *PricingRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(pricingrule.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(pricingrule.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PricingRule.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PricingRuleUpsertOne) Ignore() *PricingRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PricingRuleUpsertOne) DoNothing() *PricingRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PricingRuleCreate.OnConflict
// documentation for more info.
func (u *PricingRuleUpsertOne) Update(set func(*PricingRuleUpsert)) *PricingRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PricingRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *PricingRuleUpsertOne) SetTenantID(v uuid.UUID) *PricingRuleUpsertOne {
	return u.Update(func(s *PricingRuleUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *PricingRuleUpsertOne) UpdateTenantID() *PricingRuleUpsertOne {
	return u.Update(func(s *PricingRuleUpsert) {
		s.UpdateTenantID()
	})
}

// SetName sets the "name" field.
func (u *PricingRuleUpsertOne) SetName(v string) *PricingRuleUpsertOne {
	return u.Update(func(s *PricingRuleUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PricingRuleUpsertOne) UpdateName() *PricingRuleUpsertOne {
	return u.Update(func(s *PricingRuleUpsert) {
		s.UpdateName()
	})
}

// SetRuleType sets the "rule_type" field.
func (u *PricingRuleUpsertOne) SetRuleType(v pricingrule.RuleType) *PricingRuleUpsertOne {
	return u.Update(func(s *PricingRuleUpsert) {
		s.SetRuleType(v)
	})
}

// UpdateRuleType sets the "rule_type" field to the value that was provided on create.
func (u *PricingRuleUpsertOne) UpdateRuleType() *PricingRuleUpsertOne {
	return u.Update(func(s *PricingRuleUpsert) {
		s.UpdateRuleType()
	})
}

// SetBaseFee sets the "base_fee" field.
func (u *PricingRuleUpsertOne) SetBaseFee(v float64) *PricingRuleUpsertOne {
	return u.Update(func(s *PricingRuleUpsert) {
		s.SetBaseFee(v)
	})
}

// AddBaseFee adds v to the "base_fee" field.
func (u *PricingRuleUpsertOne) AddBaseFee(v float64) *PricingRuleUpsertOne {
	return u.Update(func(s *PricingRuleUpsert) {
		s.AddBaseFee(v)
	})
}

// UpdateBaseFee sets the "base_fee" field to the value that was provided on create.
func (u *PricingRuleUpsertOne) UpdateBaseFee() *PricingRuleUpsertOne {
	return u.Update(func(s *PricingRuleUpsert) {
		s.UpdateBaseFee()
	})
}

// SetPerKmRate sets the "per_km_rate" field.
func (u *PricingRuleUpsertOne) SetPerKmRate(v float64) *PricingRuleUpsertOne {
	return u.Update(func(s *PricingRuleUpsert) {
		s.SetPerKmRate(v)
	})
}

// AddPerKmRate adds v to the "per_km_rate" field.
func (u *PricingRuleUpsertOne) AddPerKmRate(v float64) *PricingRuleUpsertOne {
	return u.Update(func(s *PricingRuleUpsert) {
		s.AddPerKmRate(v)
	})
}

// UpdatePerKmRate sets the "per_km_rate" field to the value that was provided on create.
func (u *PricingRuleUpsertOne) UpdatePerKmRate() *PricingRuleUpsertOne {
	return u.Update(func(s *PricingRuleUpsert) {
		s.UpdatePerKmRate()
	})
}

// ClearPerKmRate clears the value of the "per_km_rate" field.
func (u *PricingRuleUpsertOne) ClearPerKmRate() *PricingRuleUpsertOne {
	return u.Update(func(s *PricingRuleUpsert) {
		s.ClearPerKmRate()
	})
}

// SetPerKgRate sets the "per_kg_rate" field.
func (u *PricingRuleUpsertOne) SetPerKgRate(v float64) *PricingRuleUpsertOne {
	return u.Update(func(s *PricingRuleUpsert) {
		s.SetPerKgRate(v)
	})
}

// AddPerKgRate adds v to the "per_kg_rate" field.
func (u *PricingRuleUpsertOne) AddPerKgRate(v float64) *PricingRuleUpsertOne {
	return u.Update(func(s *PricingRuleUpsert) {
		s.AddPerKgRate(v)
	})
}

// UpdatePerKgRate sets the "per_kg_rate" field to the value that was provided on create.
func (u *PricingRuleUpsertOne) UpdatePerKgRate() *PricingRuleUpsertOne {
	return u.Update(func(s *PricingRuleUpsert) {
		s.UpdatePerKgRate()
	})
}

// ClearPerKgRate clears the value of the "per_kg_rate" field.
func (u *PricingRuleUpsertOne) ClearPerKgRate() *PricingRuleUpsertOne {
	return u.Update(func(s *PricingRuleUpsert) {
		s.ClearPerKgRate()
	})
}

// SetSurgeMultiplier sets the "surge_multiplier" field.
func (u *PricingRuleUpsertOne) SetSurgeMultiplier(v float64) *PricingRuleUpsertOne {
	return u.Update(func(s *PricingRuleUpsert) {
		s.SetSurgeMultiplier(v)
	})
}

// AddSurgeMultiplier adds v to the "surge_multiplier" field.
func (u *PricingRuleUpsertOne) AddSurgeMultiplier(v float64) *PricingRuleUpsertOne {
	return u.Update(func(s *PricingRuleUpsert) {
		s.AddSurgeMultiplier(v)
	})
}

// UpdateSurgeMultiplier sets the "surge_multiplier" field to the value that was provided on create.
func (u *PricingRuleUpsertOne) UpdateSurgeMultiplier() *PricingRuleUpsertOne {
	return u.Update(func(s *PricingRuleUpsert) {
		s.UpdateSurgeMultiplier()
	})
}

// ClearSurgeMultiplier clears the value of the "surge_multiplier" field.
func (u *PricingRuleUpsertOne) ClearSurgeMultiplier() *PricingRuleUpsertOne {
	return u.Update(func(s *PricingRuleUpsert) {
		s.ClearSurgeMultiplier()
	})
}

// SetTimeWindows sets the "time_windows" field.
func (u *PricingRuleUpsertOne) SetTimeWindows(v []map[string]interface{}) *PricingRuleUpsertOne {
	return u.Update(func(s *PricingRuleUpsert) {
		s.SetTimeWindows(v)
	})
}

// UpdateTimeWindows sets the "time_windows" field to the value that was provided on create.
func (u *PricingRuleUpsertOne) UpdateTimeWindows() *PricingRuleUpsertOne {
	return u.Update(func(s *PricingRuleUpsert) {
		s.UpdateTimeWindows()
	})
}

// ClearTimeWindows clears the value of the "time_windows" field.
func (u *PricingRuleUpsertOne) ClearTimeWindows() *PricingRuleUpsertOne {
	return u.Update(func(s *PricingRuleUpsert) {
		s.ClearTimeWindows()
	})
}

// SetDistanceTiers sets the "distance_tiers" field.
func (u *PricingRuleUpsertOne) SetDistanceTiers(v []map[string]interface{}) *PricingRuleUpsertOne {
	return u.Update(func(s *PricingRuleUpsert) {
		s.SetDistanceTiers(v)
	})
}

// UpdateDistanceTiers sets the "distance_tiers" field to the value that was provided on create.
func (u *PricingRuleUpsertOne) UpdateDistanceTiers() *PricingRuleUpsertOne {
	return u.Update(func(s *PricingRuleUpsert) {
		s.UpdateDistanceTiers()
	})
}

// ClearDistanceTiers clears the value of the "distance_tiers" field.
func (u *PricingRuleUpsertOne) ClearDistanceTiers() *PricingRuleUpsertOne {
	return u.Update(func(s *PricingRuleUpsert) {
		s.ClearDistanceTiers()
	})
}

// SetPriority sets the "priority" field.
func (u *PricingRuleUpsertOne) SetPriority(v int) *PricingRuleUpsertOne {
	return u.Update(func(s *PricingRuleUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *PricingRuleUpsertOne) AddPriority(v int) *PricingRuleUpsertOne {
	return u.Update(func(s *PricingRuleUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *PricingRuleUpsertOne) UpdatePriority() *PricingRuleUpsertOne {
	return u.Update(func(s *PricingRuleUpsert) {
		s.UpdatePriority()
	})
}

// SetIsActive sets the "is_active" field.
func (u *PricingRuleUpsertOne) SetIsActive(v bool) *PricingRuleUpsertOne {
	return u.Update(func(s *PricingRuleUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *PricingRuleUpsertOne) UpdateIsActive() *PricingRuleUpsertOne {
	return u.Update(func(s *PricingRuleUpsert) {
		s.UpdateIsActive()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PricingRuleUpsertOne) SetUpdatedAt(v time.Time) *PricingRuleUpsertOne {
	return u.Update(func(s *PricingRuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PricingRuleUpsertOne) UpdateUpdatedAt() *PricingRuleUpsertOne {
	return u.Update(func(s *PricingRuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PricingRuleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PricingRuleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PricingRuleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PricingRuleUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: PricingRuleUpsertOne.ID is not supported by MySQL driver. Use PricingRuleUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PricingRuleUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PricingRuleCreateBulk is the builder for creating many PricingRule entities in bulk.
type PricingRuleCreateBulk struct {
	config
	err      error
	builders []*PricingRuleCreate
	conflict []sql.ConflictOption
}

// Save creates the PricingRule entities in the database.
func (_c *PricingRuleCreateBulk) Save(ctx context.Context) ([]*PricingRule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PricingRule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PricingRuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PricingRuleCreateBulk) SaveX(ctx context.Context) []*PricingRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PricingRuleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PricingRuleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PricingRule.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PricingRuleUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *PricingRuleCreateBulk) OnConflict(opts ...sql.ConflictOption) *PricingRuleUpsertBulk {
	_c.conflict = opts
	return &PricingRuleUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PricingRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PricingRuleCreateBulk) OnConflictColumns(columns ...string) *PricingRuleUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PricingRuleUpsertBulk{
		create: _c,
	}
}

// PricingRuleUpsertBulk is the builder for "upsert"-ing
// a bulk of PricingRule nodes.
type PricingRuleUpsertBulk struct {
	create *PricingRuleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PricingRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(pricingrule.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PricingRuleUpsertBulk) UpdateNewValues() *PricingRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(pricingrule.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(pricingrule.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PricingRule.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PricingRuleUpsertBulk) Ignore() *PricingRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PricingRuleUpsertBulk) DoNothing() *PricingRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PricingRuleCreateBulk.OnConflict
// documentation for more info.
func (u *PricingRuleUpsertBulk) Update(set func(*PricingRuleUpsert)) *PricingRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PricingRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *PricingRuleUpsertBulk) SetTenantID(v uuid.UUID) *PricingRuleUpsertBulk {
	return u.Update(func(s *PricingRuleUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *PricingRuleUpsertBulk) UpdateTenantID() *PricingRuleUpsertBulk {
	return u.Update(func(s *PricingRuleUpsert) {
		s.UpdateTenantID()
	})
}

// SetName sets the "name" field.
func (u *PricingRuleUpsertBulk) SetName(v string) *PricingRuleUpsertBulk {
	return u.Update(func(s *PricingRuleUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PricingRuleUpsertBulk) UpdateName() *PricingRuleUpsertBulk {
	return u.Update(func(s *PricingRuleUpsert) {
		s.UpdateName()
	})
}

// SetRuleType sets the "rule_type" field.
func (u *PricingRuleUpsertBulk) SetRuleType(v pricingrule.RuleType) *PricingRuleUpsertBulk {
	return u.Update(func(s *PricingRuleUpsert) {
		s.SetRuleType(v)
	})
}

// UpdateRuleType sets the "rule_type" field to the value that was provided on create.
func (u *PricingRuleUpsertBulk) UpdateRuleType() *PricingRuleUpsertBulk {
	return u.Update(func(s *PricingRuleUpsert) {
		s.UpdateRuleType()
	})
}

// SetBaseFee sets the "base_fee" field.
func (u *PricingRuleUpsertBulk) SetBaseFee(v float64) *PricingRuleUpsertBulk {
	return u.Update(func(s *PricingRuleUpsert) {
		s.SetBaseFee(v)
	})
}

// AddBaseFee adds v to the "base_fee" field.
func (u *PricingRuleUpsertBulk) AddBaseFee(v float64) *PricingRuleUpsertBulk {
	return u.Update(func(s *PricingRuleUpsert) {
		s.AddBaseFee(v)
	})
}

// UpdateBaseFee sets the "base_fee" field to the value that was provided on create.
func (u *PricingRuleUpsertBulk) UpdateBaseFee() *PricingRuleUpsertBulk {
	return u.Update(func(s *PricingRuleUpsert) {
		s.UpdateBaseFee()
	})
}

// SetPerKmRate sets the "per_km_rate" field.
func (u *PricingRuleUpsertBulk) SetPerKmRate(v float64) *PricingRuleUpsertBulk {
	return u.Update(func(s *PricingRuleUpsert) {
		s.SetPerKmRate(v)
	})
}

// AddPerKmRate adds v to the "per_km_rate" field.
func (u *PricingRuleUpsertBulk) AddPerKmRate(v float64) *PricingRuleUpsertBulk {
	return u.Update(func(s *PricingRuleUpsert) {
		s.AddPerKmRate(v)
	})
}

// UpdatePerKmRate sets the "per_km_rate" field to the value that was provided on create.
func (u *PricingRuleUpsertBulk) UpdatePerKmRate() *PricingRuleUpsertBulk {
	return u.Update(func(s *PricingRuleUpsert) {
		s.UpdatePerKmRate()
	})
}

// ClearPerKmRate clears the value of the "per_km_rate" field.
func (u *PricingRuleUpsertBulk) ClearPerKmRate() *PricingRuleUpsertBulk {
	return u.Update(func(s *PricingRuleUpsert) {
		s.ClearPerKmRate()
	})
}

// SetPerKgRate sets the "per_kg_rate" field.
func (u *PricingRuleUpsertBulk) SetPerKgRate(v float64) *PricingRuleUpsertBulk {
	return u.Update(func(s *PricingRuleUpsert) {
		s.SetPerKgRate(v)
	})
}

// AddPerKgRate adds v to the "per_kg_rate" field.
func (u *PricingRuleUpsertBulk) AddPerKgRate(v float64) *PricingRuleUpsertBulk {
	return u.Update(func(s *PricingRuleUpsert) {
		s.AddPerKgRate(v)
	})
}

// UpdatePerKgRate sets the "per_kg_rate" field to the value that was provided on create.
func (u *PricingRuleUpsertBulk) UpdatePerKgRate() *PricingRuleUpsertBulk {
	return u.Update(func(s *PricingRuleUpsert) {
		s.UpdatePerKgRate()
	})
}

// ClearPerKgRate clears the value of the "per_kg_rate" field.
func (u *PricingRuleUpsertBulk) ClearPerKgRate() *PricingRuleUpsertBulk {
	return u.Update(func(s *PricingRuleUpsert) {
		s.ClearPerKgRate()
	})
}

// SetSurgeMultiplier sets the "surge_multiplier" field.
func (u *PricingRuleUpsertBulk) SetSurgeMultiplier(v float64) *PricingRuleUpsertBulk {
	return u.Update(func(s *PricingRuleUpsert) {
		s.SetSurgeMultiplier(v)
	})
}

// AddSurgeMultiplier adds v to the "surge_multiplier" field.
func (u *PricingRuleUpsertBulk) AddSurgeMultiplier(v float64) *PricingRuleUpsertBulk {
	return u.Update(func(s *PricingRuleUpsert) {
		s.AddSurgeMultiplier(v)
	})
}

// UpdateSurgeMultiplier sets the "surge_multiplier" field to the value that was provided on create.
func (u *PricingRuleUpsertBulk) UpdateSurgeMultiplier() *PricingRuleUpsertBulk {
	return u.Update(func(s *PricingRuleUpsert) {
		s.UpdateSurgeMultiplier()
	})
}

// ClearSurgeMultiplier clears the value of the "surge_multiplier" field.
func (u *PricingRuleUpsertBulk) ClearSurgeMultiplier() *PricingRuleUpsertBulk {
	return u.Update(func(s *PricingRuleUpsert) {
		s.ClearSurgeMultiplier()
	})
}

// SetTimeWindows sets the "time_windows" field.
func (u *PricingRuleUpsertBulk) SetTimeWindows(v []map[string]interface{}) *PricingRuleUpsertBulk {
	return u.Update(func(s *PricingRuleUpsert) {
		s.SetTimeWindows(v)
	})
}

// UpdateTimeWindows sets the "time_windows" field to the value that was provided on create.
func (u *PricingRuleUpsertBulk) UpdateTimeWindows() *PricingRuleUpsertBulk {
	return u.Update(func(s *PricingRuleUpsert) {
		s.UpdateTimeWindows()
	})
}

// ClearTimeWindows clears the value of the "time_windows" field.
func (u *PricingRuleUpsertBulk) ClearTimeWindows() *PricingRuleUpsertBulk {
	return u.Update(func(s *PricingRuleUpsert) {
		s.ClearTimeWindows()
	})
}

// SetDistanceTiers sets the "distance_tiers" field.
func (u *PricingRuleUpsertBulk) SetDistanceTiers(v []map[string]interface{}) *PricingRuleUpsertBulk {
	return u.Update(func(s *PricingRuleUpsert) {
		s.SetDistanceTiers(v)
	})
}

// UpdateDistanceTiers sets the "distance_tiers" field to the value that was provided on create.
func (u *PricingRuleUpsertBulk) UpdateDistanceTiers() *PricingRuleUpsertBulk {
	return u.Update(func(s *PricingRuleUpsert) {
		s.UpdateDistanceTiers()
	})
}

// ClearDistanceTiers clears the value of the "distance_tiers" field.
func (u *PricingRuleUpsertBulk) ClearDistanceTiers() *PricingRuleUpsertBulk {
	return u.Update(func(s *PricingRuleUpsert) {
		s.ClearDistanceTiers()
	})
}

// SetPriority sets the "priority" field.
func (u *PricingRuleUpsertBulk) SetPriority(v int) *PricingRuleUpsertBulk {
	return u.Update(func(s *PricingRuleUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *PricingRuleUpsertBulk) AddPriority(v int) *PricingRuleUpsertBulk {
	return u.Update(func(s *PricingRuleUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *PricingRuleUpsertBulk) UpdatePriority() *PricingRuleUpsertBulk {
	return u.Update(func(s *PricingRuleUpsert) {
		s.UpdatePriority()
	})
}

// SetIsActive sets the "is_active" field.
func (u *PricingRuleUpsertBulk) SetIsActive(v bool) *PricingRuleUpsertBulk {
	return u.Update(func(s *PricingRuleUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *PricingRuleUpsertBulk) UpdateIsActive() *PricingRuleUpsertBulk {
	return u.Update(func(s *PricingRuleUpsert) {
		s.UpdateIsActive()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PricingRuleUpsertBulk) SetUpdatedAt(v time.Time) *PricingRuleUpsertBulk {
	return u.Update(func(s *PricingRuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PricingRuleUpsertBulk) UpdateUpdatedAt() *PricingRuleUpsertBulk {
	return u.Update(func(s *PricingRuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PricingRuleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PricingRuleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PricingRuleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PricingRuleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
