// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/logistics-service/internal/ent/chainofcustody"
	"github.com/bengobox/logistics-service/internal/ent/predicate"
	"github.com/bengobox/logistics-service/internal/ent/shipment"
	"github.com/google/uuid"
)

// ShipmentUpdate is the builder for updating Shipment entities.
type ShipmentUpdate struct {
	config
	hooks    []Hook
	mutation *ShipmentMutation
}

// Where appends a list predicates to the ShipmentUpdate builder.
func (_u *ShipmentUpdate) Where(ps ...predicate.Shipment) *ShipmentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *ShipmentUpdate) SetTenantID(v uuid.UUID) *ShipmentUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *ShipmentUpdate) SetNillableTenantID(v *uuid.UUID) *ShipmentUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetShipmentCode sets the "shipment_code" field.
func (_u *ShipmentUpdate) SetShipmentCode(v string) *ShipmentUpdate {
	_u.mutation.SetShipmentCode(v)
	return _u
}

// SetNillableShipmentCode sets the "shipment_code" field if the given value is not nil.
func (_u *ShipmentUpdate) SetNillableShipmentCode(v *string) *ShipmentUpdate {
	if v != nil {
		_u.SetShipmentCode(*v)
	}
	return _u
}

// SetShipmentType sets the "shipment_type" field.
func (_u *ShipmentUpdate) SetShipmentType(v string) *ShipmentUpdate {
	_u.mutation.SetShipmentType(v)
	return _u
}

// SetNillableShipmentType sets the "shipment_type" field if the given value is not nil.
func (_u *ShipmentUpdate) SetNillableShipmentType(v *string) *ShipmentUpdate {
	if v != nil {
		_u.SetShipmentType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ShipmentUpdate) SetStatus(v string) *ShipmentUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ShipmentUpdate) SetNillableStatus(v *string) *ShipmentUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetFleetType sets the "fleet_type" field.
func (_u *ShipmentUpdate) SetFleetType(v string) *ShipmentUpdate {
	_u.mutation.SetFleetType(v)
	return _u
}

// SetNillableFleetType sets the "fleet_type" field if the given value is not nil.
func (_u *ShipmentUpdate) SetNillableFleetType(v *string) *ShipmentUpdate {
	if v != nil {
		_u.SetFleetType(*v)
	}
	return _u
}

// SetSourceFacilityID sets the "source_facility_id" field.
func (_u *ShipmentUpdate) SetSourceFacilityID(v uuid.UUID) *ShipmentUpdate {
	_u.mutation.SetSourceFacilityID(v)
	return _u
}

// SetNillableSourceFacilityID sets the "source_facility_id" field if the given value is not nil.
func (_u *ShipmentUpdate) SetNillableSourceFacilityID(v *uuid.UUID) *ShipmentUpdate {
	if v != nil {
		_u.SetSourceFacilityID(*v)
	}
	return _u
}

// ClearSourceFacilityID clears the value of the "source_facility_id" field.
func (_u *ShipmentUpdate) ClearSourceFacilityID() *ShipmentUpdate {
	_u.mutation.ClearSourceFacilityID()
	return _u
}

// SetSourceFacilityName sets the "source_facility_name" field.
func (_u *ShipmentUpdate) SetSourceFacilityName(v string) *ShipmentUpdate {
	_u.mutation.SetSourceFacilityName(v)
	return _u
}

// SetNillableSourceFacilityName sets the "source_facility_name" field if the given value is not nil.
func (_u *ShipmentUpdate) SetNillableSourceFacilityName(v *string) *ShipmentUpdate {
	if v != nil {
		_u.SetSourceFacilityName(*v)
	}
	return _u
}

// ClearSourceFacilityName clears the value of the "source_facility_name" field.
func (_u *ShipmentUpdate) ClearSourceFacilityName() *ShipmentUpdate {
	_u.mutation.ClearSourceFacilityName()
	return _u
}

// SetDestFacilityID sets the "dest_facility_id" field.
func (_u *ShipmentUpdate) SetDestFacilityID(v uuid.UUID) *ShipmentUpdate {
	_u.mutation.SetDestFacilityID(v)
	return _u
}

// SetNillableDestFacilityID sets the "dest_facility_id" field if the given value is not nil.
func (_u *ShipmentUpdate) SetNillableDestFacilityID(v *uuid.UUID) *ShipmentUpdate {
	if v != nil {
		_u.SetDestFacilityID(*v)
	}
	return _u
}

// ClearDestFacilityID clears the value of the "dest_facility_id" field.
func (_u *ShipmentUpdate) ClearDestFacilityID() *ShipmentUpdate {
	_u.mutation.ClearDestFacilityID()
	return _u
}

// SetDestFacilityName sets the "dest_facility_name" field.
func (_u *ShipmentUpdate) SetDestFacilityName(v string) *ShipmentUpdate {
	_u.mutation.SetDestFacilityName(v)
	return _u
}

// SetNillableDestFacilityName sets the "dest_facility_name" field if the given value is not nil.
func (_u *ShipmentUpdate) SetNillableDestFacilityName(v *string) *ShipmentUpdate {
	if v != nil {
		_u.SetDestFacilityName(*v)
	}
	return _u
}

// ClearDestFacilityName clears the value of the "dest_facility_name" field.
func (_u *ShipmentUpdate) ClearDestFacilityName() *ShipmentUpdate {
	_u.mutation.ClearDestFacilityName()
	return _u
}

// SetTemperatureMinCelsius sets the "temperature_min_celsius" field.
func (_u *ShipmentUpdate) SetTemperatureMinCelsius(v float64) *ShipmentUpdate {
	_u.mutation.ResetTemperatureMinCelsius()
	_u.mutation.SetTemperatureMinCelsius(v)
	return _u
}

// SetNillableTemperatureMinCelsius sets the "temperature_min_celsius" field if the given value is not nil.
func (_u *ShipmentUpdate) SetNillableTemperatureMinCelsius(v *float64) *ShipmentUpdate {
	if v != nil {
		_u.SetTemperatureMinCelsius(*v)
	}
	return _u
}

// AddTemperatureMinCelsius adds value to the "temperature_min_celsius" field.
func (_u *ShipmentUpdate) AddTemperatureMinCelsius(v float64) *ShipmentUpdate {
	_u.mutation.AddTemperatureMinCelsius(v)
	return _u
}

// ClearTemperatureMinCelsius clears the value of the "temperature_min_celsius" field.
func (_u *ShipmentUpdate) ClearTemperatureMinCelsius() *ShipmentUpdate {
	_u.mutation.ClearTemperatureMinCelsius()
	return _u
}

// SetTemperatureMaxCelsius sets the "temperature_max_celsius" field.
func (_u *ShipmentUpdate) SetTemperatureMaxCelsius(v float64) *ShipmentUpdate {
	_u.mutation.ResetTemperatureMaxCelsius()
	_u.mutation.SetTemperatureMaxCelsius(v)
	return _u
}

// SetNillableTemperatureMaxCelsius sets the "temperature_max_celsius" field if the given value is not nil.
func (_u *ShipmentUpdate) SetNillableTemperatureMaxCelsius(v *float64) *ShipmentUpdate {
	if v != nil {
		_u.SetTemperatureMaxCelsius(*v)
	}
	return _u
}

// AddTemperatureMaxCelsius adds value to the "temperature_max_celsius" field.
func (_u *ShipmentUpdate) AddTemperatureMaxCelsius(v float64) *ShipmentUpdate {
	_u.mutation.AddTemperatureMaxCelsius(v)
	return _u
}

// ClearTemperatureMaxCelsius clears the value of the "temperature_max_celsius" field.
func (_u *ShipmentUpdate) ClearTemperatureMaxCelsius() *ShipmentUpdate {
	_u.mutation.ClearTemperatureMaxCelsius()
	return _u
}

// SetSpecialHandling sets the "special_handling" field.
func (_u *ShipmentUpdate) SetSpecialHandling(v []string) *ShipmentUpdate {
	_u.mutation.SetSpecialHandling(v)
	return _u
}

// AppendSpecialHandling appends value to the "special_handling" field.
func (_u *ShipmentUpdate) AppendSpecialHandling(v []string) *ShipmentUpdate {
	_u.mutation.AppendSpecialHandling(v)
	return _u
}

// ClearSpecialHandling clears the value of the "special_handling" field.
func (_u *ShipmentUpdate) ClearSpecialHandling() *ShipmentUpdate {
	_u.mutation.ClearSpecialHandling()
	return _u
}

// SetSealNumber sets the "seal_number" field.
func (_u *ShipmentUpdate) SetSealNumber(v string) *ShipmentUpdate {
	_u.mutation.SetSealNumber(v)
	return _u
}

// SetNillableSealNumber sets the "seal_number" field if the given value is not nil.
func (_u *ShipmentUpdate) SetNillableSealNumber(v *string) *ShipmentUpdate {
	if v != nil {
		_u.SetSealNumber(*v)
	}
	return _u
}

// ClearSealNumber clears the value of the "seal_number" field.
func (_u *ShipmentUpdate) ClearSealNumber() *ShipmentUpdate {
	_u.mutation.ClearSealNumber()
	return _u
}

// SetPlannedDispatchAt sets the "planned_dispatch_at" field.
func (_u *ShipmentUpdate) SetPlannedDispatchAt(v time.Time) *ShipmentUpdate {
	_u.mutation.SetPlannedDispatchAt(v)
	return _u
}

// SetNillablePlannedDispatchAt sets the "planned_dispatch_at" field if the given value is not nil.
func (_u *ShipmentUpdate) SetNillablePlannedDispatchAt(v *time.Time) *ShipmentUpdate {
	if v != nil {
		_u.SetPlannedDispatchAt(*v)
	}
	return _u
}

// ClearPlannedDispatchAt clears the value of the "planned_dispatch_at" field.
func (_u *ShipmentUpdate) ClearPlannedDispatchAt() *ShipmentUpdate {
	_u.mutation.ClearPlannedDispatchAt()
	return _u
}

// SetDispatchedAt sets the "dispatched_at" field.
func (_u *ShipmentUpdate) SetDispatchedAt(v time.Time) *ShipmentUpdate {
	_u.mutation.SetDispatchedAt(v)
	return _u
}

// SetNillableDispatchedAt sets the "dispatched_at" field if the given value is not nil.
func (_u *ShipmentUpdate) SetNillableDispatchedAt(v *time.Time) *ShipmentUpdate {
	if v != nil {
		_u.SetDispatchedAt(*v)
	}
	return _u
}

// ClearDispatchedAt clears the value of the "dispatched_at" field.
func (_u *ShipmentUpdate) ClearDispatchedAt() *ShipmentUpdate {
	_u.mutation.ClearDispatchedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *ShipmentUpdate) SetCompletedAt(v time.Time) *ShipmentUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *ShipmentUpdate) SetNillableCompletedAt(v *time.Time) *ShipmentUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *ShipmentUpdate) ClearCompletedAt() *ShipmentUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetExternalReference sets the "external_reference" field.
func (_u *ShipmentUpdate) SetExternalReference(v string) *ShipmentUpdate {
	_u.mutation.SetExternalReference(v)
	return _u
}

// SetNillableExternalReference sets the "external_reference" field if the given value is not nil.
func (_u *ShipmentUpdate) SetNillableExternalReference(v *string) *ShipmentUpdate {
	if v != nil {
		_u.SetExternalReference(*v)
	}
	return _u
}

// ClearExternalReference clears the value of the "external_reference" field.
func (_u *ShipmentUpdate) ClearExternalReference() *ShipmentUpdate {
	_u.mutation.ClearExternalReference()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *ShipmentUpdate) SetMetadata(v map[string]interface{}) *ShipmentUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ShipmentUpdate) SetUpdatedAt(v time.Time) *ShipmentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddChainOfCustodyIDs adds the "chain_of_custody" edge to the ChainOfCustody entity by IDs.
func (_u *ShipmentUpdate) AddChainOfCustodyIDs(ids ...uuid.UUID) *ShipmentUpdate {
	_u.mutation.AddChainOfCustodyIDs(ids...)
	return _u
}

// AddChainOfCustody adds the "chain_of_custody" edges to the ChainOfCustody entity.
func (_u *ShipmentUpdate) AddChainOfCustody(v ...*ChainOfCustody) *ShipmentUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChainOfCustodyIDs(ids...)
}

// Mutation returns the ShipmentMutation object of the builder.
func (_u *ShipmentUpdate) Mutation() *ShipmentMutation {
	return _u.mutation
}

// ClearChainOfCustody clears all "chain_of_custody" edges to the ChainOfCustody entity.
func (_u *ShipmentUpdate) ClearChainOfCustody() *ShipmentUpdate {
	_u.mutation.ClearChainOfCustody()
	return _u
}

// RemoveChainOfCustodyIDs removes the "chain_of_custody" edge to ChainOfCustody entities by IDs.
func (_u *ShipmentUpdate) RemoveChainOfCustodyIDs(ids ...uuid.UUID) *ShipmentUpdate {
	_u.mutation.RemoveChainOfCustodyIDs(ids...)
	return _u
}

// RemoveChainOfCustody removes "chain_of_custody" edges to ChainOfCustody entities.
func (_u *ShipmentUpdate) RemoveChainOfCustody(v ...*ChainOfCustody) *ShipmentUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChainOfCustodyIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ShipmentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ShipmentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ShipmentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ShipmentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ShipmentUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := shipment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ShipmentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(shipment.Table, shipment.Columns, sqlgraph.NewFieldSpec(shipment.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(shipment.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ShipmentCode(); ok {
		_spec.SetField(shipment.FieldShipmentCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ShipmentType(); ok {
		_spec.SetField(shipment.FieldShipmentType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(shipment.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.FleetType(); ok {
		_spec.SetField(shipment.FieldFleetType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceFacilityID(); ok {
		_spec.SetField(shipment.FieldSourceFacilityID, field.TypeUUID, value)
	}
	if _u.mutation.SourceFacilityIDCleared() {
		_spec.ClearField(shipment.FieldSourceFacilityID, field.TypeUUID)
	}
	if value, ok := _u.mutation.SourceFacilityName(); ok {
		_spec.SetField(shipment.FieldSourceFacilityName, field.TypeString, value)
	}
	if _u.mutation.SourceFacilityNameCleared() {
		_spec.ClearField(shipment.FieldSourceFacilityName, field.TypeString)
	}
	if value, ok := _u.mutation.DestFacilityID(); ok {
		_spec.SetField(shipment.FieldDestFacilityID, field.TypeUUID, value)
	}
	if _u.mutation.DestFacilityIDCleared() {
		_spec.ClearField(shipment.FieldDestFacilityID, field.TypeUUID)
	}
	if value, ok := _u.mutation.DestFacilityName(); ok {
		_spec.SetField(shipment.FieldDestFacilityName, field.TypeString, value)
	}
	if _u.mutation.DestFacilityNameCleared() {
		_spec.ClearField(shipment.FieldDestFacilityName, field.TypeString)
	}
	if value, ok := _u.mutation.TemperatureMinCelsius(); ok {
		_spec.SetField(shipment.FieldTemperatureMinCelsius, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTemperatureMinCelsius(); ok {
		_spec.AddField(shipment.FieldTemperatureMinCelsius, field.TypeFloat64, value)
	}
	if _u.mutation.TemperatureMinCelsiusCleared() {
		_spec.ClearField(shipment.FieldTemperatureMinCelsius, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TemperatureMaxCelsius(); ok {
		_spec.SetField(shipment.FieldTemperatureMaxCelsius, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTemperatureMaxCelsius(); ok {
		_spec.AddField(shipment.FieldTemperatureMaxCelsius, field.TypeFloat64, value)
	}
	if _u.mutation.TemperatureMaxCelsiusCleared() {
		_spec.ClearField(shipment.FieldTemperatureMaxCelsius, field.TypeFloat64)
	}
	if value, ok := _u.mutation.SpecialHandling(); ok {
		_spec.SetField(shipment.FieldSpecialHandling, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSpecialHandling(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, shipment.FieldSpecialHandling, value)
		})
	}
	if _u.mutation.SpecialHandlingCleared() {
		_spec.ClearField(shipment.FieldSpecialHandling, field.TypeJSON)
	}
	if value, ok := _u.mutation.SealNumber(); ok {
		_spec.SetField(shipment.FieldSealNumber, field.TypeString, value)
	}
	if _u.mutation.SealNumberCleared() {
		_spec.ClearField(shipment.FieldSealNumber, field.TypeString)
	}
	if value, ok := _u.mutation.PlannedDispatchAt(); ok {
		_spec.SetField(shipment.FieldPlannedDispatchAt, field.TypeTime, value)
	}
	if _u.mutation.PlannedDispatchAtCleared() {
		_spec.ClearField(shipment.FieldPlannedDispatchAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DispatchedAt(); ok {
		_spec.SetField(shipment.FieldDispatchedAt, field.TypeTime, value)
	}
	if _u.mutation.DispatchedAtCleared() {
		_spec.ClearField(shipment.FieldDispatchedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(shipment.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(shipment.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExternalReference(); ok {
		_spec.SetField(shipment.FieldExternalReference, field.TypeString, value)
	}
	if _u.mutation.ExternalReferenceCleared() {
		_spec.ClearField(shipment.FieldExternalReference, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(shipment.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(shipment.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ChainOfCustodyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shipment.ChainOfCustodyTable,
			Columns: []string{shipment.ChainOfCustodyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chainofcustody.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChainOfCustodyIDs(); len(nodes) > 0 && !_u.mutation.ChainOfCustodyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shipment.ChainOfCustodyTable,
			Columns: []string{shipment.ChainOfCustodyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chainofcustody.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChainOfCustodyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shipment.ChainOfCustodyTable,
			Columns: []string{shipment.ChainOfCustodyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chainofcustody.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{shipment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ShipmentUpdateOne is the builder for updating a single Shipment entity.
type ShipmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ShipmentMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *ShipmentUpdateOne) SetTenantID(v uuid.UUID) *ShipmentUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *ShipmentUpdateOne) SetNillableTenantID(v *uuid.UUID) *ShipmentUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetShipmentCode sets the "shipment_code" field.
func (_u *ShipmentUpdateOne) SetShipmentCode(v string) *ShipmentUpdateOne {
	_u.mutation.SetShipmentCode(v)
	return _u
}

// SetNillableShipmentCode sets the "shipment_code" field if the given value is not nil.
func (_u *ShipmentUpdateOne) SetNillableShipmentCode(v *string) *ShipmentUpdateOne {
	if v != nil {
		_u.SetShipmentCode(*v)
	}
	return _u
}

// SetShipmentType sets the "shipment_type" field.
func (_u *ShipmentUpdateOne) SetShipmentType(v string) *ShipmentUpdateOne {
	_u.mutation.SetShipmentType(v)
	return _u
}

// SetNillableShipmentType sets the "shipment_type" field if the given value is not nil.
func (_u *ShipmentUpdateOne) SetNillableShipmentType(v *string) *ShipmentUpdateOne {
	if v != nil {
		_u.SetShipmentType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ShipmentUpdateOne) SetStatus(v string) *ShipmentUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ShipmentUpdateOne) SetNillableStatus(v *string) *ShipmentUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetFleetType sets the "fleet_type" field.
func (_u *ShipmentUpdateOne) SetFleetType(v string) *ShipmentUpdateOne {
	_u.mutation.SetFleetType(v)
	return _u
}

// SetNillableFleetType sets the "fleet_type" field if the given value is not nil.
func (_u *ShipmentUpdateOne) SetNillableFleetType(v *string) *ShipmentUpdateOne {
	if v != nil {
		_u.SetFleetType(*v)
	}
	return _u
}

// SetSourceFacilityID sets the "source_facility_id" field.
func (_u *ShipmentUpdateOne) SetSourceFacilityID(v uuid.UUID) *ShipmentUpdateOne {
	_u.mutation.SetSourceFacilityID(v)
	return _u
}

// SetNillableSourceFacilityID sets the "source_facility_id" field if the given value is not nil.
func (_u *ShipmentUpdateOne) SetNillableSourceFacilityID(v *uuid.UUID) *ShipmentUpdateOne {
	if v != nil {
		_u.SetSourceFacilityID(*v)
	}
	return _u
}

// ClearSourceFacilityID clears the value of the "source_facility_id" field.
func (_u *ShipmentUpdateOne) ClearSourceFacilityID() *ShipmentUpdateOne {
	_u.mutation.ClearSourceFacilityID()
	return _u
}

// SetSourceFacilityName sets the "source_facility_name" field.
func (_u *ShipmentUpdateOne) SetSourceFacilityName(v string) *ShipmentUpdateOne {
	_u.mutation.SetSourceFacilityName(v)
	return _u
}

// SetNillableSourceFacilityName sets the "source_facility_name" field if the given value is not nil.
func (_u *ShipmentUpdateOne) SetNillableSourceFacilityName(v *string) *ShipmentUpdateOne {
	if v != nil {
		_u.SetSourceFacilityName(*v)
	}
	return _u
}

// ClearSourceFacilityName clears the value of the "source_facility_name" field.
func (_u *ShipmentUpdateOne) ClearSourceFacilityName() *ShipmentUpdateOne {
	_u.mutation.ClearSourceFacilityName()
	return _u
}

// SetDestFacilityID sets the "dest_facility_id" field.
func (_u *ShipmentUpdateOne) SetDestFacilityID(v uuid.UUID) *ShipmentUpdateOne {
	_u.mutation.SetDestFacilityID(v)
	return _u
}

// SetNillableDestFacilityID sets the "dest_facility_id" field if the given value is not nil.
func (_u *ShipmentUpdateOne) SetNillableDestFacilityID(v *uuid.UUID) *ShipmentUpdateOne {
	if v != nil {
		_u.SetDestFacilityID(*v)
	}
	return _u
}

// ClearDestFacilityID clears the value of the "dest_facility_id" field.
func (_u *ShipmentUpdateOne) ClearDestFacilityID() *ShipmentUpdateOne {
	_u.mutation.ClearDestFacilityID()
	return _u
}

// SetDestFacilityName sets the "dest_facility_name" field.
func (_u *ShipmentUpdateOne) SetDestFacilityName(v string) *ShipmentUpdateOne {
	_u.mutation.SetDestFacilityName(v)
	return _u
}

// SetNillableDestFacilityName sets the "dest_facility_name" field if the given value is not nil.
func (_u *ShipmentUpdateOne) SetNillableDestFacilityName(v *string) *ShipmentUpdateOne {
	if v != nil {
		_u.SetDestFacilityName(*v)
	}
	return _u
}

// ClearDestFacilityName clears the value of the "dest_facility_name" field.
func (_u *ShipmentUpdateOne) ClearDestFacilityName() *ShipmentUpdateOne {
	_u.mutation.ClearDestFacilityName()
	return _u
}

// SetTemperatureMinCelsius sets the "temperature_min_celsius" field.
func (_u *ShipmentUpdateOne) SetTemperatureMinCelsius(v float64) *ShipmentUpdateOne {
	_u.mutation.ResetTemperatureMinCelsius()
	_u.mutation.SetTemperatureMinCelsius(v)
	return _u
}

// SetNillableTemperatureMinCelsius sets the "temperature_min_celsius" field if the given value is not nil.
func (_u *ShipmentUpdateOne) SetNillableTemperatureMinCelsius(v *float64) *ShipmentUpdateOne {
	if v != nil {
		_u.SetTemperatureMinCelsius(*v)
	}
	return _u
}

// AddTemperatureMinCelsius adds value to the "temperature_min_celsius" field.
func (_u *ShipmentUpdateOne) AddTemperatureMinCelsius(v float64) *ShipmentUpdateOne {
	_u.mutation.AddTemperatureMinCelsius(v)
	return _u
}

// ClearTemperatureMinCelsius clears the value of the "temperature_min_celsius" field.
func (_u *ShipmentUpdateOne) ClearTemperatureMinCelsius() *ShipmentUpdateOne {
	_u.mutation.ClearTemperatureMinCelsius()
	return _u
}

// SetTemperatureMaxCelsius sets the "temperature_max_celsius" field.
func (_u *ShipmentUpdateOne) SetTemperatureMaxCelsius(v float64) *ShipmentUpdateOne {
	_u.mutation.ResetTemperatureMaxCelsius()
	_u.mutation.SetTemperatureMaxCelsius(v)
	return _u
}

// SetNillableTemperatureMaxCelsius sets the "temperature_max_celsius" field if the given value is not nil.
func (_u *ShipmentUpdateOne) SetNillableTemperatureMaxCelsius(v *float64) *ShipmentUpdateOne {
	if v != nil {
		_u.SetTemperatureMaxCelsius(*v)
	}
	return _u
}

// AddTemperatureMaxCelsius adds value to the "temperature_max_celsius" field.
func (_u *ShipmentUpdateOne) AddTemperatureMaxCelsius(v float64) *ShipmentUpdateOne {
	_u.mutation.AddTemperatureMaxCelsius(v)
	return _u
}

// ClearTemperatureMaxCelsius clears the value of the "temperature_max_celsius" field.
func (_u *ShipmentUpdateOne) ClearTemperatureMaxCelsius() *ShipmentUpdateOne {
	_u.mutation.ClearTemperatureMaxCelsius()
	return _u
}

// SetSpecialHandling sets the "special_handling" field.
func (_u *ShipmentUpdateOne) SetSpecialHandling(v []string) *ShipmentUpdateOne {
	_u.mutation.SetSpecialHandling(v)
	return _u
}

// AppendSpecialHandling appends value to the "special_handling" field.
func (_u *ShipmentUpdateOne) AppendSpecialHandling(v []string) *ShipmentUpdateOne {
	_u.mutation.AppendSpecialHandling(v)
	return _u
}

// ClearSpecialHandling clears the value of the "special_handling" field.
func (_u *ShipmentUpdateOne) ClearSpecialHandling() *ShipmentUpdateOne {
	_u.mutation.ClearSpecialHandling()
	return _u
}

// SetSealNumber sets the "seal_number" field.
func (_u *ShipmentUpdateOne) SetSealNumber(v string) *ShipmentUpdateOne {
	_u.mutation.SetSealNumber(v)
	return _u
}

// SetNillableSealNumber sets the "seal_number" field if the given value is not nil.
func (_u *ShipmentUpdateOne) SetNillableSealNumber(v *string) *ShipmentUpdateOne {
	if v != nil {
		_u.SetSealNumber(*v)
	}
	return _u
}

// ClearSealNumber clears the value of the "seal_number" field.
func (_u *ShipmentUpdateOne) ClearSealNumber() *ShipmentUpdateOne {
	_u.mutation.ClearSealNumber()
	return _u
}

// SetPlannedDispatchAt sets the "planned_dispatch_at" field.
func (_u *ShipmentUpdateOne) SetPlannedDispatchAt(v time.Time) *ShipmentUpdateOne {
	_u.mutation.SetPlannedDispatchAt(v)
	return _u
}

// SetNillablePlannedDispatchAt sets the "planned_dispatch_at" field if the given value is not nil.
func (_u *ShipmentUpdateOne) SetNillablePlannedDispatchAt(v *time.Time) *ShipmentUpdateOne {
	if v != nil {
		_u.SetPlannedDispatchAt(*v)
	}
	return _u
}

// ClearPlannedDispatchAt clears the value of the "planned_dispatch_at" field.
func (_u *ShipmentUpdateOne) ClearPlannedDispatchAt() *ShipmentUpdateOne {
	_u.mutation.ClearPlannedDispatchAt()
	return _u
}

// SetDispatchedAt sets the "dispatched_at" field.
func (_u *ShipmentUpdateOne) SetDispatchedAt(v time.Time) *ShipmentUpdateOne {
	_u.mutation.SetDispatchedAt(v)
	return _u
}

// SetNillableDispatchedAt sets the "dispatched_at" field if the given value is not nil.
func (_u *ShipmentUpdateOne) SetNillableDispatchedAt(v *time.Time) *ShipmentUpdateOne {
	if v != nil {
		_u.SetDispatchedAt(*v)
	}
	return _u
}

// ClearDispatchedAt clears the value of the "dispatched_at" field.
func (_u *ShipmentUpdateOne) ClearDispatchedAt() *ShipmentUpdateOne {
	_u.mutation.ClearDispatchedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *ShipmentUpdateOne) SetCompletedAt(v time.Time) *ShipmentUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *ShipmentUpdateOne) SetNillableCompletedAt(v *time.Time) *ShipmentUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *ShipmentUpdateOne) ClearCompletedAt() *ShipmentUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetExternalReference sets the "external_reference" field.
func (_u *ShipmentUpdateOne) SetExternalReference(v string) *ShipmentUpdateOne {
	_u.mutation.SetExternalReference(v)
	return _u
}

// SetNillableExternalReference sets the "external_reference" field if the given value is not nil.
func (_u *ShipmentUpdateOne) SetNillableExternalReference(v *string) *ShipmentUpdateOne {
	if v != nil {
		_u.SetExternalReference(*v)
	}
	return _u
}

// ClearExternalReference clears the value of the "external_reference" field.
func (_u *ShipmentUpdateOne) ClearExternalReference() *ShipmentUpdateOne {
	_u.mutation.ClearExternalReference()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *ShipmentUpdateOne) SetMetadata(v map[string]interface{}) *ShipmentUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ShipmentUpdateOne) SetUpdatedAt(v time.Time) *ShipmentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddChainOfCustodyIDs adds the "chain_of_custody" edge to the ChainOfCustody entity by IDs.
func (_u *ShipmentUpdateOne) AddChainOfCustodyIDs(ids ...uuid.UUID) *ShipmentUpdateOne {
	_u.mutation.AddChainOfCustodyIDs(ids...)
	return _u
}

// AddChainOfCustody adds the "chain_of_custody" edges to the ChainOfCustody entity.
func (_u *ShipmentUpdateOne) AddChainOfCustody(v ...*ChainOfCustody) *ShipmentUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChainOfCustodyIDs(ids...)
}

// Mutation returns the ShipmentMutation object of the builder.
func (_u *ShipmentUpdateOne) Mutation() *ShipmentMutation {
	return _u.mutation
}

// ClearChainOfCustody clears all "chain_of_custody" edges to the ChainOfCustody entity.
func (_u *ShipmentUpdateOne) ClearChainOfCustody() *ShipmentUpdateOne {
	_u.mutation.ClearChainOfCustody()
	return _u
}

// RemoveChainOfCustodyIDs removes the "chain_of_custody" edge to ChainOfCustody entities by IDs.
func (_u *ShipmentUpdateOne) RemoveChainOfCustodyIDs(ids ...uuid.UUID) *ShipmentUpdateOne {
	_u.mutation.RemoveChainOfCustodyIDs(ids...)
	return _u
}

// RemoveChainOfCustody removes "chain_of_custody" edges to ChainOfCustody entities.
func (_u *ShipmentUpdateOne) RemoveChainOfCustody(v ...*ChainOfCustody) *ShipmentUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChainOfCustodyIDs(ids...)
}

// Where appends a list predicates to the ShipmentUpdate builder.
func (_u *ShipmentUpdateOne) Where(ps ...predicate.Shipment) *ShipmentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ShipmentUpdateOne) Select(field string, fields ...string) *ShipmentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Shipment entity.
func (_u *ShipmentUpdateOne) Save(ctx context.Context) (*Shipment, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ShipmentUpdateOne) SaveX(ctx context.Context) *Shipment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ShipmentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ShipmentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ShipmentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := shipment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ShipmentUpdateOne) sqlSave(ctx context.Context) (_node *Shipment, err error) {
	_spec := sqlgraph.NewUpdateSpec(shipment.Table, shipment.Columns, sqlgraph.NewFieldSpec(shipment.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Shipment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, shipment.FieldID)
		for _, f := range fields {
			if !shipment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != shipment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(shipment.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ShipmentCode(); ok {
		_spec.SetField(shipment.FieldShipmentCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ShipmentType(); ok {
		_spec.SetField(shipment.FieldShipmentType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(shipment.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.FleetType(); ok {
		_spec.SetField(shipment.FieldFleetType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceFacilityID(); ok {
		_spec.SetField(shipment.FieldSourceFacilityID, field.TypeUUID, value)
	}
	if _u.mutation.SourceFacilityIDCleared() {
		_spec.ClearField(shipment.FieldSourceFacilityID, field.TypeUUID)
	}
	if value, ok := _u.mutation.SourceFacilityName(); ok {
		_spec.SetField(shipment.FieldSourceFacilityName, field.TypeString, value)
	}
	if _u.mutation.SourceFacilityNameCleared() {
		_spec.ClearField(shipment.FieldSourceFacilityName, field.TypeString)
	}
	if value, ok := _u.mutation.DestFacilityID(); ok {
		_spec.SetField(shipment.FieldDestFacilityID, field.TypeUUID, value)
	}
	if _u.mutation.DestFacilityIDCleared() {
		_spec.ClearField(shipment.FieldDestFacilityID, field.TypeUUID)
	}
	if value, ok := _u.mutation.DestFacilityName(); ok {
		_spec.SetField(shipment.FieldDestFacilityName, field.TypeString, value)
	}
	if _u.mutation.DestFacilityNameCleared() {
		_spec.ClearField(shipment.FieldDestFacilityName, field.TypeString)
	}
	if value, ok := _u.mutation.TemperatureMinCelsius(); ok {
		_spec.SetField(shipment.FieldTemperatureMinCelsius, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTemperatureMinCelsius(); ok {
		_spec.AddField(shipment.FieldTemperatureMinCelsius, field.TypeFloat64, value)
	}
	if _u.mutation.TemperatureMinCelsiusCleared() {
		_spec.ClearField(shipment.FieldTemperatureMinCelsius, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TemperatureMaxCelsius(); ok {
		_spec.SetField(shipment.FieldTemperatureMaxCelsius, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTemperatureMaxCelsius(); ok {
		_spec.AddField(shipment.FieldTemperatureMaxCelsius, field.TypeFloat64, value)
	}
	if _u.mutation.TemperatureMaxCelsiusCleared() {
		_spec.ClearField(shipment.FieldTemperatureMaxCelsius, field.TypeFloat64)
	}
	if value, ok := _u.mutation.SpecialHandling(); ok {
		_spec.SetField(shipment.FieldSpecialHandling, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSpecialHandling(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, shipment.FieldSpecialHandling, value)
		})
	}
	if _u.mutation.SpecialHandlingCleared() {
		_spec.ClearField(shipment.FieldSpecialHandling, field.TypeJSON)
	}
	if value, ok := _u.mutation.SealNumber(); ok {
		_spec.SetField(shipment.FieldSealNumber, field.TypeString, value)
	}
	if _u.mutation.SealNumberCleared() {
		_spec.ClearField(shipment.FieldSealNumber, field.TypeString)
	}
	if value, ok := _u.mutation.PlannedDispatchAt(); ok {
		_spec.SetField(shipment.FieldPlannedDispatchAt, field.TypeTime, value)
	}
	if _u.mutation.PlannedDispatchAtCleared() {
		_spec.ClearField(shipment.FieldPlannedDispatchAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DispatchedAt(); ok {
		_spec.SetField(shipment.FieldDispatchedAt, field.TypeTime, value)
	}
	if _u.mutation.DispatchedAtCleared() {
		_spec.ClearField(shipment.FieldDispatchedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(shipment.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(shipment.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExternalReference(); ok {
		_spec.SetField(shipment.FieldExternalReference, field.TypeString, value)
	}
	if _u.mutation.ExternalReferenceCleared() {
		_spec.ClearField(shipment.FieldExternalReference, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(shipment.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(shipment.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ChainOfCustodyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shipment.ChainOfCustodyTable,
			Columns: []string{shipment.ChainOfCustodyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chainofcustody.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChainOfCustodyIDs(); len(nodes) > 0 && !_u.mutation.ChainOfCustodyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shipment.ChainOfCustodyTable,
			Columns: []string{shipment.ChainOfCustodyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chainofcustody.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChainOfCustodyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shipment.ChainOfCustodyTable,
			Columns: []string{shipment.ChainOfCustodyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chainofcustody.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Shipment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{shipment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
