// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/logistics-service/internal/ent/predicate"
	"github.com/bengobox/logistics-service/internal/ent/proofofdelivery"
	"github.com/bengobox/logistics-service/internal/ent/task"
	"github.com/bengobox/logistics-service/internal/ent/taskassignment"
	"github.com/bengobox/logistics-service/internal/ent/taskevent"
	"github.com/bengobox/logistics-service/internal/ent/taskstep"
	"github.com/google/uuid"
)

// TaskUpdate is the builder for updating Task entities.
type TaskUpdate struct {
	config
	hooks    []Hook
	mutation *TaskMutation
}

// Where appends a list predicates to the TaskUpdate builder.
func (_u *TaskUpdate) Where(ps ...predicate.Task) *TaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *TaskUpdate) SetTenantID(v uuid.UUID) *TaskUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableTenantID(v *uuid.UUID) *TaskUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetExternalReference sets the "external_reference" field.
func (_u *TaskUpdate) SetExternalReference(v string) *TaskUpdate {
	_u.mutation.SetExternalReference(v)
	return _u
}

// SetNillableExternalReference sets the "external_reference" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableExternalReference(v *string) *TaskUpdate {
	if v != nil {
		_u.SetExternalReference(*v)
	}
	return _u
}

// ClearExternalReference clears the value of the "external_reference" field.
func (_u *TaskUpdate) ClearExternalReference() *TaskUpdate {
	_u.mutation.ClearExternalReference()
	return _u
}

// SetSourceService sets the "source_service" field.
func (_u *TaskUpdate) SetSourceService(v string) *TaskUpdate {
	_u.mutation.SetSourceService(v)
	return _u
}

// SetNillableSourceService sets the "source_service" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableSourceService(v *string) *TaskUpdate {
	if v != nil {
		_u.SetSourceService(*v)
	}
	return _u
}

// ClearSourceService clears the value of the "source_service" field.
func (_u *TaskUpdate) ClearSourceService() *TaskUpdate {
	_u.mutation.ClearSourceService()
	return _u
}

// SetTaskType sets the "task_type" field.
func (_u *TaskUpdate) SetTaskType(v string) *TaskUpdate {
	_u.mutation.SetTaskType(v)
	return _u
}

// SetNillableTaskType sets the "task_type" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableTaskType(v *string) *TaskUpdate {
	if v != nil {
		_u.SetTaskType(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *TaskUpdate) SetPriority(v int) *TaskUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *TaskUpdate) SetNillablePriority(v *int) *TaskUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *TaskUpdate) AddPriority(v int) *TaskUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *TaskUpdate) SetStatus(v string) *TaskUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableStatus(v *string) *TaskUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSLADueAt sets the "sla_due_at" field.
func (_u *TaskUpdate) SetSLADueAt(v time.Time) *TaskUpdate {
	_u.mutation.SetSLADueAt(v)
	return _u
}

// SetNillableSLADueAt sets the "sla_due_at" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableSLADueAt(v *time.Time) *TaskUpdate {
	if v != nil {
		_u.SetSLADueAt(*v)
	}
	return _u
}

// ClearSLADueAt clears the value of the "sla_due_at" field.
func (_u *TaskUpdate) ClearSLADueAt() *TaskUpdate {
	_u.mutation.ClearSLADueAt()
	return _u
}

// SetRequestedPickupAt sets the "requested_pickup_at" field.
func (_u *TaskUpdate) SetRequestedPickupAt(v time.Time) *TaskUpdate {
	_u.mutation.SetRequestedPickupAt(v)
	return _u
}

// SetNillableRequestedPickupAt sets the "requested_pickup_at" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableRequestedPickupAt(v *time.Time) *TaskUpdate {
	if v != nil {
		_u.SetRequestedPickupAt(*v)
	}
	return _u
}

// ClearRequestedPickupAt clears the value of the "requested_pickup_at" field.
func (_u *TaskUpdate) ClearRequestedPickupAt() *TaskUpdate {
	_u.mutation.ClearRequestedPickupAt()
	return _u
}

// SetRequestedDropoffAt sets the "requested_dropoff_at" field.
func (_u *TaskUpdate) SetRequestedDropoffAt(v time.Time) *TaskUpdate {
	_u.mutation.SetRequestedDropoffAt(v)
	return _u
}

// SetNillableRequestedDropoffAt sets the "requested_dropoff_at" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableRequestedDropoffAt(v *time.Time) *TaskUpdate {
	if v != nil {
		_u.SetRequestedDropoffAt(*v)
	}
	return _u
}

// ClearRequestedDropoffAt clears the value of the "requested_dropoff_at" field.
func (_u *TaskUpdate) ClearRequestedDropoffAt() *TaskUpdate {
	_u.mutation.ClearRequestedDropoffAt()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *TaskUpdate) SetMetadata(v map[string]interface{}) *TaskUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TaskUpdate) SetUpdatedAt(v time.Time) *TaskUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddStepIDs adds the "steps" edge to the TaskStep entity by IDs.
func (_u *TaskUpdate) AddStepIDs(ids ...uuid.UUID) *TaskUpdate {
	_u.mutation.AddStepIDs(ids...)
	return _u
}

// AddSteps adds the "steps" edges to the TaskStep entity.
func (_u *TaskUpdate) AddSteps(v ...*TaskStep) *TaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddStepIDs(ids...)
}

// AddEventIDs adds the "events" edge to the TaskEvent entity by IDs.
func (_u *TaskUpdate) AddEventIDs(ids ...uuid.UUID) *TaskUpdate {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the TaskEvent entity.
func (_u *TaskUpdate) AddEvents(v ...*TaskEvent) *TaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// AddAssignmentIDs adds the "assignments" edge to the TaskAssignment entity by IDs.
func (_u *TaskUpdate) AddAssignmentIDs(ids ...uuid.UUID) *TaskUpdate {
	_u.mutation.AddAssignmentIDs(ids...)
	return _u
}

// AddAssignments adds the "assignments" edges to the TaskAssignment entity.
func (_u *TaskUpdate) AddAssignments(v ...*TaskAssignment) *TaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAssignmentIDs(ids...)
}

// SetProofOfDeliveryID sets the "proof_of_delivery" edge to the ProofOfDelivery entity by ID.
func (_u *TaskUpdate) SetProofOfDeliveryID(id uuid.UUID) *TaskUpdate {
	_u.mutation.SetProofOfDeliveryID(id)
	return _u
}

// SetNillableProofOfDeliveryID sets the "proof_of_delivery" edge to the ProofOfDelivery entity by ID if the given value is not nil.
func (_u *TaskUpdate) SetNillableProofOfDeliveryID(id *uuid.UUID) *TaskUpdate {
	if id != nil {
		_u = _u.SetProofOfDeliveryID(*id)
	}
	return _u
}

// SetProofOfDelivery sets the "proof_of_delivery" edge to the ProofOfDelivery entity.
func (_u *TaskUpdate) SetProofOfDelivery(v *ProofOfDelivery) *TaskUpdate {
	return _u.SetProofOfDeliveryID(v.ID)
}

// Mutation returns the TaskMutation object of the builder.
func (_u *TaskUpdate) Mutation() *TaskMutation {
	return _u.mutation
}

// ClearSteps clears all "steps" edges to the TaskStep entity.
func (_u *TaskUpdate) ClearSteps() *TaskUpdate {
	_u.mutation.ClearSteps()
	return _u
}

// RemoveStepIDs removes the "steps" edge to TaskStep entities by IDs.
func (_u *TaskUpdate) RemoveStepIDs(ids ...uuid.UUID) *TaskUpdate {
	_u.mutation.RemoveStepIDs(ids...)
	return _u
}

// RemoveSteps removes "steps" edges to TaskStep entities.
func (_u *TaskUpdate) RemoveSteps(v ...*TaskStep) *TaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveStepIDs(ids...)
}

// ClearEvents clears all "events" edges to the TaskEvent entity.
func (_u *TaskUpdate) ClearEvents() *TaskUpdate {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to TaskEvent entities by IDs.
func (_u *TaskUpdate) RemoveEventIDs(ids ...uuid.UUID) *TaskUpdate {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to TaskEvent entities.
func (_u *TaskUpdate) RemoveEvents(v ...*TaskEvent) *TaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// ClearAssignments clears all "assignments" edges to the TaskAssignment entity.
func (_u *TaskUpdate) ClearAssignments() *TaskUpdate {
	_u.mutation.ClearAssignments()
	return _u
}

// RemoveAssignmentIDs removes the "assignments" edge to TaskAssignment entities by IDs.
func (_u *TaskUpdate) RemoveAssignmentIDs(ids ...uuid.UUID) *TaskUpdate {
	_u.mutation.RemoveAssignmentIDs(ids...)
	return _u
}

// RemoveAssignments removes "assignments" edges to TaskAssignment entities.
func (_u *TaskUpdate) RemoveAssignments(v ...*TaskAssignment) *TaskUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAssignmentIDs(ids...)
}

// ClearProofOfDelivery clears the "proof_of_delivery" edge to the ProofOfDelivery entity.
func (_u *TaskUpdate) ClearProofOfDelivery() *TaskUpdate {
	_u.mutation.ClearProofOfDelivery()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TaskUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TaskUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := task.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *TaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(task.Table, task.Columns, sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(task.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ExternalReference(); ok {
		_spec.SetField(task.FieldExternalReference, field.TypeString, value)
	}
	if _u.mutation.ExternalReferenceCleared() {
		_spec.ClearField(task.FieldExternalReference, field.TypeString)
	}
	if value, ok := _u.mutation.SourceService(); ok {
		_spec.SetField(task.FieldSourceService, field.TypeString, value)
	}
	if _u.mutation.SourceServiceCleared() {
		_spec.ClearField(task.FieldSourceService, field.TypeString)
	}
	if value, ok := _u.mutation.TaskType(); ok {
		_spec.SetField(task.FieldTaskType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(task.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(task.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(task.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.SLADueAt(); ok {
		_spec.SetField(task.FieldSLADueAt, field.TypeTime, value)
	}
	if _u.mutation.SLADueAtCleared() {
		_spec.ClearField(task.FieldSLADueAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RequestedPickupAt(); ok {
		_spec.SetField(task.FieldRequestedPickupAt, field.TypeTime, value)
	}
	if _u.mutation.RequestedPickupAtCleared() {
		_spec.ClearField(task.FieldRequestedPickupAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RequestedDropoffAt(); ok {
		_spec.SetField(task.FieldRequestedDropoffAt, field.TypeTime, value)
	}
	if _u.mutation.RequestedDropoffAtCleared() {
		_spec.ClearField(task.FieldRequestedDropoffAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(task.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(task.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.StepsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.StepsTable,
			Columns: []string{task.StepsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskstep.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStepsIDs(); len(nodes) > 0 && !_u.mutation.StepsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.StepsTable,
			Columns: []string{task.StepsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskstep.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StepsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.StepsTable,
			Columns: []string{task.StepsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskstep.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.EventsTable,
			Columns: []string{task.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskevent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.EventsTable,
			Columns: []string{task.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.EventsTable,
			Columns: []string{task.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.AssignmentsTable,
			Columns: []string{task.AssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskassignment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAssignmentsIDs(); len(nodes) > 0 && !_u.mutation.AssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.AssignmentsTable,
			Columns: []string{task.AssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssignmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.AssignmentsTable,
			Columns: []string{task.AssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProofOfDeliveryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   task.ProofOfDeliveryTable,
			Columns: []string{task.ProofOfDeliveryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proofofdelivery.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProofOfDeliveryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   task.ProofOfDeliveryTable,
			Columns: []string{task.ProofOfDeliveryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proofofdelivery.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{task.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TaskUpdateOne is the builder for updating a single Task entity.
type TaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TaskMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *TaskUpdateOne) SetTenantID(v uuid.UUID) *TaskUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableTenantID(v *uuid.UUID) *TaskUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetExternalReference sets the "external_reference" field.
func (_u *TaskUpdateOne) SetExternalReference(v string) *TaskUpdateOne {
	_u.mutation.SetExternalReference(v)
	return _u
}

// SetNillableExternalReference sets the "external_reference" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableExternalReference(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetExternalReference(*v)
	}
	return _u
}

// ClearExternalReference clears the value of the "external_reference" field.
func (_u *TaskUpdateOne) ClearExternalReference() *TaskUpdateOne {
	_u.mutation.ClearExternalReference()
	return _u
}

// SetSourceService sets the "source_service" field.
func (_u *TaskUpdateOne) SetSourceService(v string) *TaskUpdateOne {
	_u.mutation.SetSourceService(v)
	return _u
}

// SetNillableSourceService sets the "source_service" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableSourceService(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetSourceService(*v)
	}
	return _u
}

// ClearSourceService clears the value of the "source_service" field.
func (_u *TaskUpdateOne) ClearSourceService() *TaskUpdateOne {
	_u.mutation.ClearSourceService()
	return _u
}

// SetTaskType sets the "task_type" field.
func (_u *TaskUpdateOne) SetTaskType(v string) *TaskUpdateOne {
	_u.mutation.SetTaskType(v)
	return _u
}

// SetNillableTaskType sets the "task_type" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableTaskType(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetTaskType(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *TaskUpdateOne) SetPriority(v int) *TaskUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillablePriority(v *int) *TaskUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *TaskUpdateOne) AddPriority(v int) *TaskUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *TaskUpdateOne) SetStatus(v string) *TaskUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableStatus(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSLADueAt sets the "sla_due_at" field.
func (_u *TaskUpdateOne) SetSLADueAt(v time.Time) *TaskUpdateOne {
	_u.mutation.SetSLADueAt(v)
	return _u
}

// SetNillableSLADueAt sets the "sla_due_at" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableSLADueAt(v *time.Time) *TaskUpdateOne {
	if v != nil {
		_u.SetSLADueAt(*v)
	}
	return _u
}

// ClearSLADueAt clears the value of the "sla_due_at" field.
func (_u *TaskUpdateOne) ClearSLADueAt() *TaskUpdateOne {
	_u.mutation.ClearSLADueAt()
	return _u
}

// SetRequestedPickupAt sets the "requested_pickup_at" field.
func (_u *TaskUpdateOne) SetRequestedPickupAt(v time.Time) *TaskUpdateOne {
	_u.mutation.SetRequestedPickupAt(v)
	return _u
}

// SetNillableRequestedPickupAt sets the "requested_pickup_at" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableRequestedPickupAt(v *time.Time) *TaskUpdateOne {
	if v != nil {
		_u.SetRequestedPickupAt(*v)
	}
	return _u
}

// ClearRequestedPickupAt clears the value of the "requested_pickup_at" field.
func (_u *TaskUpdateOne) ClearRequestedPickupAt() *TaskUpdateOne {
	_u.mutation.ClearRequestedPickupAt()
	return _u
}

// SetRequestedDropoffAt sets the "requested_dropoff_at" field.
func (_u *TaskUpdateOne) SetRequestedDropoffAt(v time.Time) *TaskUpdateOne {
	_u.mutation.SetRequestedDropoffAt(v)
	return _u
}

// SetNillableRequestedDropoffAt sets the "requested_dropoff_at" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableRequestedDropoffAt(v *time.Time) *TaskUpdateOne {
	if v != nil {
		_u.SetRequestedDropoffAt(*v)
	}
	return _u
}

// ClearRequestedDropoffAt clears the value of the "requested_dropoff_at" field.
func (_u *TaskUpdateOne) ClearRequestedDropoffAt() *TaskUpdateOne {
	_u.mutation.ClearRequestedDropoffAt()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *TaskUpdateOne) SetMetadata(v map[string]interface{}) *TaskUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TaskUpdateOne) SetUpdatedAt(v time.Time) *TaskUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddStepIDs adds the "steps" edge to the TaskStep entity by IDs.
func (_u *TaskUpdateOne) AddStepIDs(ids ...uuid.UUID) *TaskUpdateOne {
	_u.mutation.AddStepIDs(ids...)
	return _u
}

// AddSteps adds the "steps" edges to the TaskStep entity.
func (_u *TaskUpdateOne) AddSteps(v ...*TaskStep) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddStepIDs(ids...)
}

// AddEventIDs adds the "events" edge to the TaskEvent entity by IDs.
func (_u *TaskUpdateOne) AddEventIDs(ids ...uuid.UUID) *TaskUpdateOne {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the TaskEvent entity.
func (_u *TaskUpdateOne) AddEvents(v ...*TaskEvent) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// AddAssignmentIDs adds the "assignments" edge to the TaskAssignment entity by IDs.
func (_u *TaskUpdateOne) AddAssignmentIDs(ids ...uuid.UUID) *TaskUpdateOne {
	_u.mutation.AddAssignmentIDs(ids...)
	return _u
}

// AddAssignments adds the "assignments" edges to the TaskAssignment entity.
func (_u *TaskUpdateOne) AddAssignments(v ...*TaskAssignment) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAssignmentIDs(ids...)
}

// SetProofOfDeliveryID sets the "proof_of_delivery" edge to the ProofOfDelivery entity by ID.
func (_u *TaskUpdateOne) SetProofOfDeliveryID(id uuid.UUID) *TaskUpdateOne {
	_u.mutation.SetProofOfDeliveryID(id)
	return _u
}

// SetNillableProofOfDeliveryID sets the "proof_of_delivery" edge to the ProofOfDelivery entity by ID if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableProofOfDeliveryID(id *uuid.UUID) *TaskUpdateOne {
	if id != nil {
		_u = _u.SetProofOfDeliveryID(*id)
	}
	return _u
}

// SetProofOfDelivery sets the "proof_of_delivery" edge to the ProofOfDelivery entity.
func (_u *TaskUpdateOne) SetProofOfDelivery(v *ProofOfDelivery) *TaskUpdateOne {
	return _u.SetProofOfDeliveryID(v.ID)
}

// Mutation returns the TaskMutation object of the builder.
func (_u *TaskUpdateOne) Mutation() *TaskMutation {
	return _u.mutation
}

// ClearSteps clears all "steps" edges to the TaskStep entity.
func (_u *TaskUpdateOne) ClearSteps() *TaskUpdateOne {
	_u.mutation.ClearSteps()
	return _u
}

// RemoveStepIDs removes the "steps" edge to TaskStep entities by IDs.
func (_u *TaskUpdateOne) RemoveStepIDs(ids ...uuid.UUID) *TaskUpdateOne {
	_u.mutation.RemoveStepIDs(ids...)
	return _u
}

// RemoveSteps removes "steps" edges to TaskStep entities.
func (_u *TaskUpdateOne) RemoveSteps(v ...*TaskStep) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveStepIDs(ids...)
}

// ClearEvents clears all "events" edges to the TaskEvent entity.
func (_u *TaskUpdateOne) ClearEvents() *TaskUpdateOne {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to TaskEvent entities by IDs.
func (_u *TaskUpdateOne) RemoveEventIDs(ids ...uuid.UUID) *TaskUpdateOne {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to TaskEvent entities.
func (_u *TaskUpdateOne) RemoveEvents(v ...*TaskEvent) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// ClearAssignments clears all "assignments" edges to the TaskAssignment entity.
func (_u *TaskUpdateOne) ClearAssignments() *TaskUpdateOne {
	_u.mutation.ClearAssignments()
	return _u
}

// RemoveAssignmentIDs removes the "assignments" edge to TaskAssignment entities by IDs.
func (_u *TaskUpdateOne) RemoveAssignmentIDs(ids ...uuid.UUID) *TaskUpdateOne {
	_u.mutation.RemoveAssignmentIDs(ids...)
	return _u
}

// RemoveAssignments removes "assignments" edges to TaskAssignment entities.
func (_u *TaskUpdateOne) RemoveAssignments(v ...*TaskAssignment) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAssignmentIDs(ids...)
}

// ClearProofOfDelivery clears the "proof_of_delivery" edge to the ProofOfDelivery entity.
func (_u *TaskUpdateOne) ClearProofOfDelivery() *TaskUpdateOne {
	_u.mutation.ClearProofOfDelivery()
	return _u
}

// Where appends a list predicates to the TaskUpdate builder.
func (_u *TaskUpdateOne) Where(ps ...predicate.Task) *TaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TaskUpdateOne) Select(field string, fields ...string) *TaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Task entity.
func (_u *TaskUpdateOne) Save(ctx context.Context) (*Task, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskUpdateOne) SaveX(ctx context.Context) *Task {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TaskUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := task.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *TaskUpdateOne) sqlSave(ctx context.Context) (_node *Task, err error) {
	_spec := sqlgraph.NewUpdateSpec(task.Table, task.Columns, sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Task.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, task.FieldID)
		for _, f := range fields {
			if !task.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != task.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(task.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ExternalReference(); ok {
		_spec.SetField(task.FieldExternalReference, field.TypeString, value)
	}
	if _u.mutation.ExternalReferenceCleared() {
		_spec.ClearField(task.FieldExternalReference, field.TypeString)
	}
	if value, ok := _u.mutation.SourceService(); ok {
		_spec.SetField(task.FieldSourceService, field.TypeString, value)
	}
	if _u.mutation.SourceServiceCleared() {
		_spec.ClearField(task.FieldSourceService, field.TypeString)
	}
	if value, ok := _u.mutation.TaskType(); ok {
		_spec.SetField(task.FieldTaskType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(task.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(task.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(task.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.SLADueAt(); ok {
		_spec.SetField(task.FieldSLADueAt, field.TypeTime, value)
	}
	if _u.mutation.SLADueAtCleared() {
		_spec.ClearField(task.FieldSLADueAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RequestedPickupAt(); ok {
		_spec.SetField(task.FieldRequestedPickupAt, field.TypeTime, value)
	}
	if _u.mutation.RequestedPickupAtCleared() {
		_spec.ClearField(task.FieldRequestedPickupAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RequestedDropoffAt(); ok {
		_spec.SetField(task.FieldRequestedDropoffAt, field.TypeTime, value)
	}
	if _u.mutation.RequestedDropoffAtCleared() {
		_spec.ClearField(task.FieldRequestedDropoffAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(task.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(task.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.StepsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.StepsTable,
			Columns: []string{task.StepsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskstep.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStepsIDs(); len(nodes) > 0 && !_u.mutation.StepsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.StepsTable,
			Columns: []string{task.StepsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskstep.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StepsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.StepsTable,
			Columns: []string{task.StepsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskstep.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.EventsTable,
			Columns: []string{task.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskevent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.EventsTable,
			Columns: []string{task.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.EventsTable,
			Columns: []string{task.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.AssignmentsTable,
			Columns: []string{task.AssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskassignment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAssignmentsIDs(); len(nodes) > 0 && !_u.mutation.AssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.AssignmentsTable,
			Columns: []string{task.AssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssignmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.AssignmentsTable,
			Columns: []string{task.AssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProofOfDeliveryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   task.ProofOfDeliveryTable,
			Columns: []string{task.ProofOfDeliveryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proofofdelivery.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProofOfDeliveryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   task.ProofOfDeliveryTable,
			Columns: []string{task.ProofOfDeliveryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proofofdelivery.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Task{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{task.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
