// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/logistics-service/internal/ent/fleetmember"
	"github.com/bengobox/logistics-service/internal/ent/task"
	"github.com/bengobox/logistics-service/internal/ent/taskassignment"
	"github.com/google/uuid"
)

// TaskAssignment is the model entity for the TaskAssignment schema.
type TaskAssignment struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TaskID holds the value of the "task_id" field.
	TaskID uuid.UUID `json:"task_id,omitempty"`
	// FleetMemberID holds the value of the "fleet_member_id" field.
	FleetMemberID uuid.UUID `json:"fleet_member_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// AssignedAt holds the value of the "assigned_at" field.
	AssignedAt time.Time `json:"assigned_at,omitempty"`
	// AcceptedAt holds the value of the "accepted_at" field.
	AcceptedAt *time.Time `json:"accepted_at,omitempty"`
	// DeclinedAt holds the value of the "declined_at" field.
	DeclinedAt *time.Time `json:"declined_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// ReasonCode holds the value of the "reason_code" field.
	ReasonCode string `json:"reason_code,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TaskAssignmentQuery when eager-loading is set.
	Edges        TaskAssignmentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TaskAssignmentEdges holds the relations/edges for other nodes in the graph.
type TaskAssignmentEdges struct {
	// Task holds the value of the task edge.
	Task *Task `json:"task,omitempty"`
	// Member holds the value of the member edge.
	Member *FleetMember `json:"member,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TaskOrErr returns the Task value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskAssignmentEdges) TaskOrErr() (*Task, error) {
	if e.Task != nil {
		return e.Task, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: task.Label}
	}
	return nil, &NotLoadedError{edge: "task"}
}

// MemberOrErr returns the Member value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskAssignmentEdges) MemberOrErr() (*FleetMember, error) {
	if e.Member != nil {
		return e.Member, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: fleetmember.Label}
	}
	return nil, &NotLoadedError{edge: "member"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TaskAssignment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case taskassignment.FieldMetadata:
			values[i] = new([]byte)
		case taskassignment.FieldStatus, taskassignment.FieldReasonCode:
			values[i] = new(sql.NullString)
		case taskassignment.FieldAssignedAt, taskassignment.FieldAcceptedAt, taskassignment.FieldDeclinedAt, taskassignment.FieldCompletedAt:
			values[i] = new(sql.NullTime)
		case taskassignment.FieldID, taskassignment.FieldTaskID, taskassignment.FieldFleetMemberID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TaskAssignment fields.
func (_m *TaskAssignment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case taskassignment.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case taskassignment.FieldTaskID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field task_id", values[i])
			} else if value != nil {
				_m.TaskID = *value
			}
		case taskassignment.FieldFleetMemberID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field fleet_member_id", values[i])
			} else if value != nil {
				_m.FleetMemberID = *value
			}
		case taskassignment.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case taskassignment.FieldAssignedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field assigned_at", values[i])
			} else if value.Valid {
				_m.AssignedAt = value.Time
			}
		case taskassignment.FieldAcceptedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field accepted_at", values[i])
			} else if value.Valid {
				_m.AcceptedAt = new(time.Time)
				*_m.AcceptedAt = value.Time
			}
		case taskassignment.FieldDeclinedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field declined_at", values[i])
			} else if value.Valid {
				_m.DeclinedAt = new(time.Time)
				*_m.DeclinedAt = value.Time
			}
		case taskassignment.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		case taskassignment.FieldReasonCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason_code", values[i])
			} else if value.Valid {
				_m.ReasonCode = value.String
			}
		case taskassignment.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TaskAssignment.
// This includes values selected through modifiers, order, etc.
func (_m *TaskAssignment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTask queries the "task" edge of the TaskAssignment entity.
func (_m *TaskAssignment) QueryTask() *TaskQuery {
	return NewTaskAssignmentClient(_m.config).QueryTask(_m)
}

// QueryMember queries the "member" edge of the TaskAssignment entity.
func (_m *TaskAssignment) QueryMember() *FleetMemberQuery {
	return NewTaskAssignmentClient(_m.config).QueryMember(_m)
}

// Update returns a builder for updating this TaskAssignment.
// Note that you need to call TaskAssignment.Unwrap() before calling this method if this TaskAssignment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TaskAssignment) Update() *TaskAssignmentUpdateOne {
	return NewTaskAssignmentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TaskAssignment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TaskAssignment) Unwrap() *TaskAssignment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TaskAssignment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TaskAssignment) String() string {
	var builder strings.Builder
	builder.WriteString("TaskAssignment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("task_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TaskID))
	builder.WriteString(", ")
	builder.WriteString("fleet_member_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.FleetMemberID))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("assigned_at=")
	builder.WriteString(_m.AssignedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.AcceptedAt; v != nil {
		builder.WriteString("accepted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeclinedAt; v != nil {
		builder.WriteString("declined_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("reason_code=")
	builder.WriteString(_m.ReasonCode)
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteByte(')')
	return builder.String()
}

// TaskAssignments is a parsable slice of TaskAssignment.
type TaskAssignments []*TaskAssignment
