// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/logistics-service/internal/ent/fleetmember"
	"github.com/bengobox/logistics-service/internal/ent/task"
	"github.com/bengobox/logistics-service/internal/ent/taskassignment"
	"github.com/google/uuid"
)

// TaskAssignmentCreate is the builder for creating a TaskAssignment entity.
type TaskAssignmentCreate struct {
	config
	mutation *TaskAssignmentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTaskID sets the "task_id" field.
func (_c *TaskAssignmentCreate) SetTaskID(v uuid.UUID) *TaskAssignmentCreate {
	_c.mutation.SetTaskID(v)
	return _c
}

// SetFleetMemberID sets the "fleet_member_id" field.
func (_c *TaskAssignmentCreate) SetFleetMemberID(v uuid.UUID) *TaskAssignmentCreate {
	_c.mutation.SetFleetMemberID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *TaskAssignmentCreate) SetStatus(v string) *TaskAssignmentCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *TaskAssignmentCreate) SetNillableStatus(v *string) *TaskAssignmentCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAssignedAt sets the "assigned_at" field.
func (_c *TaskAssignmentCreate) SetAssignedAt(v time.Time) *TaskAssignmentCreate {
	_c.mutation.SetAssignedAt(v)
	return _c
}

// SetNillableAssignedAt sets the "assigned_at" field if the given value is not nil.
func (_c *TaskAssignmentCreate) SetNillableAssignedAt(v *time.Time) *TaskAssignmentCreate {
	if v != nil {
		_c.SetAssignedAt(*v)
	}
	return _c
}

// SetAcceptedAt sets the "accepted_at" field.
func (_c *TaskAssignmentCreate) SetAcceptedAt(v time.Time) *TaskAssignmentCreate {
	_c.mutation.SetAcceptedAt(v)
	return _c
}

// SetNillableAcceptedAt sets the "accepted_at" field if the given value is not nil.
func (_c *TaskAssignmentCreate) SetNillableAcceptedAt(v *time.Time) *TaskAssignmentCreate {
	if v != nil {
		_c.SetAcceptedAt(*v)
	}
	return _c
}

// SetDeclinedAt sets the "declined_at" field.
func (_c *TaskAssignmentCreate) SetDeclinedAt(v time.Time) *TaskAssignmentCreate {
	_c.mutation.SetDeclinedAt(v)
	return _c
}

// SetNillableDeclinedAt sets the "declined_at" field if the given value is not nil.
func (_c *TaskAssignmentCreate) SetNillableDeclinedAt(v *time.Time) *TaskAssignmentCreate {
	if v != nil {
		_c.SetDeclinedAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *TaskAssignmentCreate) SetCompletedAt(v time.Time) *TaskAssignmentCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *TaskAssignmentCreate) SetNillableCompletedAt(v *time.Time) *TaskAssignmentCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetReasonCode sets the "reason_code" field.
func (_c *TaskAssignmentCreate) SetReasonCode(v string) *TaskAssignmentCreate {
	_c.mutation.SetReasonCode(v)
	return _c
}

// SetNillableReasonCode sets the "reason_code" field if the given value is not nil.
func (_c *TaskAssignmentCreate) SetNillableReasonCode(v *string) *TaskAssignmentCreate {
	if v != nil {
		_c.SetReasonCode(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *TaskAssignmentCreate) SetMetadata(v map[string]interface{}) *TaskAssignmentCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetID sets the "id" field.
func (_c *TaskAssignmentCreate) SetID(v uuid.UUID) *TaskAssignmentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *TaskAssignmentCreate) SetNillableID(v *uuid.UUID) *TaskAssignmentCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetTask sets the "task" edge to the Task entity.
func (_c *TaskAssignmentCreate) SetTask(v *Task) *TaskAssignmentCreate {
	return _c.SetTaskID(v.ID)
}

// SetMemberID sets the "member" edge to the FleetMember entity by ID.
func (_c *TaskAssignmentCreate) SetMemberID(id uuid.UUID) *TaskAssignmentCreate {
	_c.mutation.SetMemberID(id)
	return _c
}

// SetMember sets the "member" edge to the FleetMember entity.
func (_c *TaskAssignmentCreate) SetMember(v *FleetMember) *TaskAssignmentCreate {
	return _c.SetMemberID(v.ID)
}

// Mutation returns the TaskAssignmentMutation object of the builder.
func (_c *TaskAssignmentCreate) Mutation() *TaskAssignmentMutation {
	return _c.mutation
}

// Save creates the TaskAssignment in the database.
func (_c *TaskAssignmentCreate) Save(ctx context.Context) (*TaskAssignment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TaskAssignmentCreate) SaveX(ctx context.Context) *TaskAssignment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskAssignmentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskAssignmentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TaskAssignmentCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := taskassignment.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.AssignedAt(); !ok {
		v := taskassignment.DefaultAssignedAt()
		_c.mutation.SetAssignedAt(v)
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		v := taskassignment.DefaultMetadata
		_c.mutation.SetMetadata(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := taskassignment.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TaskAssignmentCreate) check() error {
	if _, ok := _c.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task_id", err: errors.New(`ent: missing required field "TaskAssignment.task_id"`)}
	}
	if _, ok := _c.mutation.FleetMemberID(); !ok {
		return &ValidationError{Name: "fleet_member_id", err: errors.New(`ent: missing required field "TaskAssignment.fleet_member_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "TaskAssignment.status"`)}
	}
	if _, ok := _c.mutation.AssignedAt(); !ok {
		return &ValidationError{Name: "assigned_at", err: errors.New(`ent: missing required field "TaskAssignment.assigned_at"`)}
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		return &ValidationError{Name: "metadata", err: errors.New(`ent: missing required field "TaskAssignment.metadata"`)}
	}
	if len(_c.mutation.TaskIDs()) == 0 {
		return &ValidationError{Name: "task", err: errors.New(`ent: missing required edge "TaskAssignment.task"`)}
	}
	if len(_c.mutation.MemberIDs()) == 0 {
		return &ValidationError{Name: "member", err: errors.New(`ent: missing required edge "TaskAssignment.member"`)}
	}
	return nil
}

func (_c *TaskAssignmentCreate) sqlSave(ctx context.Context) (*TaskAssignment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TaskAssignmentCreate) createSpec() (*TaskAssignment, *sqlgraph.CreateSpec) {
	var (
		_node = &TaskAssignment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(taskassignment.Table, sqlgraph.NewFieldSpec(taskassignment.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(taskassignment.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.AssignedAt(); ok {
		_spec.SetField(taskassignment.FieldAssignedAt, field.TypeTime, value)
		_node.AssignedAt = value
	}
	if value, ok := _c.mutation.AcceptedAt(); ok {
		_spec.SetField(taskassignment.FieldAcceptedAt, field.TypeTime, value)
		_node.AcceptedAt = &value
	}
	if value, ok := _c.mutation.DeclinedAt(); ok {
		_spec.SetField(taskassignment.FieldDeclinedAt, field.TypeTime, value)
		_node.DeclinedAt = &value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(taskassignment.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := _c.mutation.ReasonCode(); ok {
		_spec.SetField(taskassignment.FieldReasonCode, field.TypeString, value)
		_node.ReasonCode = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(taskassignment.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if nodes := _c.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskassignment.TaskTable,
			Columns: []string{taskassignment.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TaskID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MemberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskassignment.MemberTable,
			Columns: []string{taskassignment.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fleetmember.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.FleetMemberID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TaskAssignment.Create().
//		SetTaskID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TaskAssignmentUpsert) {
//			SetTaskID(v+v).
//		}).
//		Exec(ctx)
func (_c *TaskAssignmentCreate) OnConflict(opts ...sql.ConflictOption) *TaskAssignmentUpsertOne {
	_c.conflict = opts
	return &TaskAssignmentUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TaskAssignment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TaskAssignmentCreate) OnConflictColumns(columns ...string) *TaskAssignmentUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TaskAssignmentUpsertOne{
		create: _c,
	}
}

type (
	// TaskAssignmentUpsertOne is the builder for "upsert"-ing
	//  one TaskAssignment node.
	TaskAssignmentUpsertOne struct {
		create *TaskAssignmentCreate
	}

	// TaskAssignmentUpsert is the "OnConflict" setter.
	TaskAssignmentUpsert struct {
		*sql.UpdateSet
	}
)

// SetTaskID sets the "task_id" field.
func (u *TaskAssignmentUpsert) SetTaskID(v uuid.UUID) *TaskAssignmentUpsert {
	u.Set(taskassignment.FieldTaskID, v)
	return u
}

// UpdateTaskID sets the "task_id" field to the value that was provided on create.
func (u *TaskAssignmentUpsert) UpdateTaskID() *TaskAssignmentUpsert {
	u.SetExcluded(taskassignment.FieldTaskID)
	return u
}

// SetFleetMemberID sets the "fleet_member_id" field.
func (u *TaskAssignmentUpsert) SetFleetMemberID(v uuid.UUID) *TaskAssignmentUpsert {
	u.Set(taskassignment.FieldFleetMemberID, v)
	return u
}

// UpdateFleetMemberID sets the "fleet_member_id" field to the value that was provided on create.
func (u *TaskAssignmentUpsert) UpdateFleetMemberID() *TaskAssignmentUpsert {
	u.SetExcluded(taskassignment.FieldFleetMemberID)
	return u
}

// SetStatus sets the "status" field.
func (u *TaskAssignmentUpsert) SetStatus(v string) *TaskAssignmentUpsert {
	u.Set(taskassignment.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TaskAssignmentUpsert) UpdateStatus() *TaskAssignmentUpsert {
	u.SetExcluded(taskassignment.FieldStatus)
	return u
}

// SetAssignedAt sets the "assigned_at" field.
func (u *TaskAssignmentUpsert) SetAssignedAt(v time.Time) *TaskAssignmentUpsert {
	u.Set(taskassignment.FieldAssignedAt, v)
	return u
}

// UpdateAssignedAt sets the "assigned_at" field to the value that was provided on create.
func (u *TaskAssignmentUpsert) UpdateAssignedAt() *TaskAssignmentUpsert {
	u.SetExcluded(taskassignment.FieldAssignedAt)
	return u
}

// SetAcceptedAt sets the "accepted_at" field.
func (u *TaskAssignmentUpsert) SetAcceptedAt(v time.Time) *TaskAssignmentUpsert {
	u.Set(taskassignment.FieldAcceptedAt, v)
	return u
}

// UpdateAcceptedAt sets the "accepted_at" field to the value that was provided on create.
func (u *TaskAssignmentUpsert) UpdateAcceptedAt() *TaskAssignmentUpsert {
	u.SetExcluded(taskassignment.FieldAcceptedAt)
	return u
}

// ClearAcceptedAt clears the value of the "accepted_at" field.
func (u *TaskAssignmentUpsert) ClearAcceptedAt() *TaskAssignmentUpsert {
	u.SetNull(taskassignment.FieldAcceptedAt)
	return u
}

// SetDeclinedAt sets the "declined_at" field.
func (u *TaskAssignmentUpsert) SetDeclinedAt(v time.Time) *TaskAssignmentUpsert {
	u.Set(taskassignment.FieldDeclinedAt, v)
	return u
}

// UpdateDeclinedAt sets the "declined_at" field to the value that was provided on create.
func (u *TaskAssignmentUpsert) UpdateDeclinedAt() *TaskAssignmentUpsert {
	u.SetExcluded(taskassignment.FieldDeclinedAt)
	return u
}

// ClearDeclinedAt clears the value of the "declined_at" field.
func (u *TaskAssignmentUpsert) ClearDeclinedAt() *TaskAssignmentUpsert {
	u.SetNull(taskassignment.FieldDeclinedAt)
	return u
}

// SetCompletedAt sets the "completed_at" field.
func (u *TaskAssignmentUpsert) SetCompletedAt(v time.Time) *TaskAssignmentUpsert {
	u.Set(taskassignment.FieldCompletedAt, v)
	return u
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *TaskAssignmentUpsert) UpdateCompletedAt() *TaskAssignmentUpsert {
	u.SetExcluded(taskassignment.FieldCompletedAt)
	return u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *TaskAssignmentUpsert) ClearCompletedAt() *TaskAssignmentUpsert {
	u.SetNull(taskassignment.FieldCompletedAt)
	return u
}

// SetReasonCode sets the "reason_code" field.
func (u *TaskAssignmentUpsert) SetReasonCode(v string) *TaskAssignmentUpsert {
	u.Set(taskassignment.FieldReasonCode, v)
	return u
}

// UpdateReasonCode sets the "reason_code" field to the value that was provided on create.
func (u *TaskAssignmentUpsert) UpdateReasonCode() *TaskAssignmentUpsert {
	u.SetExcluded(taskassignment.FieldReasonCode)
	return u
}

// ClearReasonCode clears the value of the "reason_code" field.
func (u *TaskAssignmentUpsert) ClearReasonCode() *TaskAssignmentUpsert {
	u.SetNull(taskassignment.FieldReasonCode)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *TaskAssignmentUpsert) SetMetadata(v map[string]interface{}) *TaskAssignmentUpsert {
	u.Set(taskassignment.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *TaskAssignmentUpsert) UpdateMetadata() *TaskAssignmentUpsert {
	u.SetExcluded(taskassignment.FieldMetadata)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.TaskAssignment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(taskassignment.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TaskAssignmentUpsertOne) UpdateNewValues() *TaskAssignmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(taskassignment.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TaskAssignment.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TaskAssignmentUpsertOne) Ignore() *TaskAssignmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TaskAssignmentUpsertOne) DoNothing() *TaskAssignmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TaskAssignmentCreate.OnConflict
// documentation for more info.
func (u *TaskAssignmentUpsertOne) Update(set func(*TaskAssignmentUpsert)) *TaskAssignmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TaskAssignmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetTaskID sets the "task_id" field.
func (u *TaskAssignmentUpsertOne) SetTaskID(v uuid.UUID) *TaskAssignmentUpsertOne {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.SetTaskID(v)
	})
}

// UpdateTaskID sets the "task_id" field to the value that was provided on create.
func (u *TaskAssignmentUpsertOne) UpdateTaskID() *TaskAssignmentUpsertOne {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.UpdateTaskID()
	})
}

// SetFleetMemberID sets the "fleet_member_id" field.
func (u *TaskAssignmentUpsertOne) SetFleetMemberID(v uuid.UUID) *TaskAssignmentUpsertOne {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.SetFleetMemberID(v)
	})
}

// UpdateFleetMemberID sets the "fleet_member_id" field to the value that was provided on create.
func (u *TaskAssignmentUpsertOne) UpdateFleetMemberID() *TaskAssignmentUpsertOne {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.UpdateFleetMemberID()
	})
}

// SetStatus sets the "status" field.
func (u *TaskAssignmentUpsertOne) SetStatus(v string) *TaskAssignmentUpsertOne {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TaskAssignmentUpsertOne) UpdateStatus() *TaskAssignmentUpsertOne {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.UpdateStatus()
	})
}

// SetAssignedAt sets the "assigned_at" field.
func (u *TaskAssignmentUpsertOne) SetAssignedAt(v time.Time) *TaskAssignmentUpsertOne {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.SetAssignedAt(v)
	})
}

// UpdateAssignedAt sets the "assigned_at" field to the value that was provided on create.
func (u *TaskAssignmentUpsertOne) UpdateAssignedAt() *TaskAssignmentUpsertOne {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.UpdateAssignedAt()
	})
}

// SetAcceptedAt sets the "accepted_at" field.
func (u *TaskAssignmentUpsertOne) SetAcceptedAt(v time.Time) *TaskAssignmentUpsertOne {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.SetAcceptedAt(v)
	})
}

// UpdateAcceptedAt sets the "accepted_at" field to the value that was provided on create.
func (u *TaskAssignmentUpsertOne) UpdateAcceptedAt() *TaskAssignmentUpsertOne {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.UpdateAcceptedAt()
	})
}

// ClearAcceptedAt clears the value of the "accepted_at" field.
func (u *TaskAssignmentUpsertOne) ClearAcceptedAt() *TaskAssignmentUpsertOne {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.ClearAcceptedAt()
	})
}

// SetDeclinedAt sets the "declined_at" field.
func (u *TaskAssignmentUpsertOne) SetDeclinedAt(v time.Time) *TaskAssignmentUpsertOne {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.SetDeclinedAt(v)
	})
}

// UpdateDeclinedAt sets the "declined_at" field to the value that was provided on create.
func (u *TaskAssignmentUpsertOne) UpdateDeclinedAt() *TaskAssignmentUpsertOne {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.UpdateDeclinedAt()
	})
}

// ClearDeclinedAt clears the value of the "declined_at" field.
func (u *TaskAssignmentUpsertOne) ClearDeclinedAt() *TaskAssignmentUpsertOne {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.ClearDeclinedAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *TaskAssignmentUpsertOne) SetCompletedAt(v time.Time) *TaskAssignmentUpsertOne {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *TaskAssignmentUpsertOne) UpdateCompletedAt() *TaskAssignmentUpsertOne {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *TaskAssignmentUpsertOne) ClearCompletedAt() *TaskAssignmentUpsertOne {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.ClearCompletedAt()
	})
}

// SetReasonCode sets the "reason_code" field.
func (u *TaskAssignmentUpsertOne) SetReasonCode(v string) *TaskAssignmentUpsertOne {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.SetReasonCode(v)
	})
}

// UpdateReasonCode sets the "reason_code" field to the value that was provided on create.
func (u *TaskAssignmentUpsertOne) UpdateReasonCode() *TaskAssignmentUpsertOne {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.UpdateReasonCode()
	})
}

// ClearReasonCode clears the value of the "reason_code" field.
func (u *TaskAssignmentUpsertOne) ClearReasonCode() *TaskAssignmentUpsertOne {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.ClearReasonCode()
	})
}

// SetMetadata sets the "metadata" field.
func (u *TaskAssignmentUpsertOne) SetMetadata(v map[string]interface{}) *TaskAssignmentUpsertOne {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *TaskAssignmentUpsertOne) UpdateMetadata() *TaskAssignmentUpsertOne {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.UpdateMetadata()
	})
}

// Exec executes the query.
func (u *TaskAssignmentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TaskAssignmentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TaskAssignmentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TaskAssignmentUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: TaskAssignmentUpsertOne.ID is not supported by MySQL driver. Use TaskAssignmentUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TaskAssignmentUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TaskAssignmentCreateBulk is the builder for creating many TaskAssignment entities in bulk.
type TaskAssignmentCreateBulk struct {
	config
	err      error
	builders []*TaskAssignmentCreate
	conflict []sql.ConflictOption
}

// Save creates the TaskAssignment entities in the database.
func (_c *TaskAssignmentCreateBulk) Save(ctx context.Context) ([]*TaskAssignment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TaskAssignment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TaskAssignmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TaskAssignmentCreateBulk) SaveX(ctx context.Context) []*TaskAssignment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskAssignmentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskAssignmentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TaskAssignment.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TaskAssignmentUpsert) {
//			SetTaskID(v+v).
//		}).
//		Exec(ctx)
func (_c *TaskAssignmentCreateBulk) OnConflict(opts ...sql.ConflictOption) *TaskAssignmentUpsertBulk {
	_c.conflict = opts
	return &TaskAssignmentUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TaskAssignment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TaskAssignmentCreateBulk) OnConflictColumns(columns ...string) *TaskAssignmentUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TaskAssignmentUpsertBulk{
		create: _c,
	}
}

// TaskAssignmentUpsertBulk is the builder for "upsert"-ing
// a bulk of TaskAssignment nodes.
type TaskAssignmentUpsertBulk struct {
	create *TaskAssignmentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TaskAssignment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(taskassignment.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TaskAssignmentUpsertBulk) UpdateNewValues() *TaskAssignmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(taskassignment.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TaskAssignment.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TaskAssignmentUpsertBulk) Ignore() *TaskAssignmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TaskAssignmentUpsertBulk) DoNothing() *TaskAssignmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TaskAssignmentCreateBulk.OnConflict
// documentation for more info.
func (u *TaskAssignmentUpsertBulk) Update(set func(*TaskAssignmentUpsert)) *TaskAssignmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TaskAssignmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetTaskID sets the "task_id" field.
func (u *TaskAssignmentUpsertBulk) SetTaskID(v uuid.UUID) *TaskAssignmentUpsertBulk {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.SetTaskID(v)
	})
}

// UpdateTaskID sets the "task_id" field to the value that was provided on create.
func (u *TaskAssignmentUpsertBulk) UpdateTaskID() *TaskAssignmentUpsertBulk {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.UpdateTaskID()
	})
}

// SetFleetMemberID sets the "fleet_member_id" field.
func (u *TaskAssignmentUpsertBulk) SetFleetMemberID(v uuid.UUID) *TaskAssignmentUpsertBulk {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.SetFleetMemberID(v)
	})
}

// UpdateFleetMemberID sets the "fleet_member_id" field to the value that was provided on create.
func (u *TaskAssignmentUpsertBulk) UpdateFleetMemberID() *TaskAssignmentUpsertBulk {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.UpdateFleetMemberID()
	})
}

// SetStatus sets the "status" field.
func (u *TaskAssignmentUpsertBulk) SetStatus(v string) *TaskAssignmentUpsertBulk {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TaskAssignmentUpsertBulk) UpdateStatus() *TaskAssignmentUpsertBulk {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.UpdateStatus()
	})
}

// SetAssignedAt sets the "assigned_at" field.
func (u *TaskAssignmentUpsertBulk) SetAssignedAt(v time.Time) *TaskAssignmentUpsertBulk {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.SetAssignedAt(v)
	})
}

// UpdateAssignedAt sets the "assigned_at" field to the value that was provided on create.
func (u *TaskAssignmentUpsertBulk) UpdateAssignedAt() *TaskAssignmentUpsertBulk {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.UpdateAssignedAt()
	})
}

// SetAcceptedAt sets the "accepted_at" field.
func (u *TaskAssignmentUpsertBulk) SetAcceptedAt(v time.Time) *TaskAssignmentUpsertBulk {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.SetAcceptedAt(v)
	})
}

// UpdateAcceptedAt sets the "accepted_at" field to the value that was provided on create.
func (u *TaskAssignmentUpsertBulk) UpdateAcceptedAt() *TaskAssignmentUpsertBulk {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.UpdateAcceptedAt()
	})
}

// ClearAcceptedAt clears the value of the "accepted_at" field.
func (u *TaskAssignmentUpsertBulk) ClearAcceptedAt() *TaskAssignmentUpsertBulk {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.ClearAcceptedAt()
	})
}

// SetDeclinedAt sets the "declined_at" field.
func (u *TaskAssignmentUpsertBulk) SetDeclinedAt(v time.Time) *TaskAssignmentUpsertBulk {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.SetDeclinedAt(v)
	})
}

// UpdateDeclinedAt sets the "declined_at" field to the value that was provided on create.
func (u *TaskAssignmentUpsertBulk) UpdateDeclinedAt() *TaskAssignmentUpsertBulk {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.UpdateDeclinedAt()
	})
}

// ClearDeclinedAt clears the value of the "declined_at" field.
func (u *TaskAssignmentUpsertBulk) ClearDeclinedAt() *TaskAssignmentUpsertBulk {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.ClearDeclinedAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *TaskAssignmentUpsertBulk) SetCompletedAt(v time.Time) *TaskAssignmentUpsertBulk {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *TaskAssignmentUpsertBulk) UpdateCompletedAt() *TaskAssignmentUpsertBulk {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *TaskAssignmentUpsertBulk) ClearCompletedAt() *TaskAssignmentUpsertBulk {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.ClearCompletedAt()
	})
}

// SetReasonCode sets the "reason_code" field.
func (u *TaskAssignmentUpsertBulk) SetReasonCode(v string) *TaskAssignmentUpsertBulk {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.SetReasonCode(v)
	})
}

// UpdateReasonCode sets the "reason_code" field to the value that was provided on create.
func (u *TaskAssignmentUpsertBulk) UpdateReasonCode() *TaskAssignmentUpsertBulk {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.UpdateReasonCode()
	})
}

// ClearReasonCode clears the value of the "reason_code" field.
func (u *TaskAssignmentUpsertBulk) ClearReasonCode() *TaskAssignmentUpsertBulk {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.ClearReasonCode()
	})
}

// SetMetadata sets the "metadata" field.
func (u *TaskAssignmentUpsertBulk) SetMetadata(v map[string]interface{}) *TaskAssignmentUpsertBulk {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *TaskAssignmentUpsertBulk) UpdateMetadata() *TaskAssignmentUpsertBulk {
	return u.Update(func(s *TaskAssignmentUpsert) {
		s.UpdateMetadata()
	})
}

// Exec executes the query.
func (u *TaskAssignmentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TaskAssignmentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TaskAssignmentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TaskAssignmentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
