// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/logistics-service/internal/ent/telemetrystream"
	"github.com/google/uuid"
)

// TelemetryStream is the model entity for the TelemetryStream schema.
type TelemetryStream struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// FleetMemberID holds the value of the "fleet_member_id" field.
	FleetMemberID uuid.UUID `json:"fleet_member_id,omitempty"`
	// DeviceID holds the value of the "device_id" field.
	DeviceID string `json:"device_id,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt time.Time `json:"started_at,omitempty"`
	// EndedAt holds the value of the "ended_at" field.
	EndedAt *time.Time `json:"ended_at,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TelemetryStreamQuery when eager-loading is set.
	Edges        TelemetryStreamEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TelemetryStreamEdges holds the relations/edges for other nodes in the graph.
type TelemetryStreamEdges struct {
	// Points holds the value of the points edge.
	Points []*TelemetryPoint `json:"points,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PointsOrErr returns the Points value or an error if the edge
// was not loaded in eager-loading.
func (e TelemetryStreamEdges) PointsOrErr() ([]*TelemetryPoint, error) {
	if e.loadedTypes[0] {
		return e.Points, nil
	}
	return nil, &NotLoadedError{edge: "points"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TelemetryStream) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case telemetrystream.FieldMetadata:
			values[i] = new([]byte)
		case telemetrystream.FieldDeviceID, telemetrystream.FieldStatus:
			values[i] = new(sql.NullString)
		case telemetrystream.FieldStartedAt, telemetrystream.FieldEndedAt:
			values[i] = new(sql.NullTime)
		case telemetrystream.FieldID, telemetrystream.FieldTenantID, telemetrystream.FieldFleetMemberID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TelemetryStream fields.
func (_m *TelemetryStream) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case telemetrystream.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case telemetrystream.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantID = *value
			}
		case telemetrystream.FieldFleetMemberID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field fleet_member_id", values[i])
			} else if value != nil {
				_m.FleetMemberID = *value
			}
		case telemetrystream.FieldDeviceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field device_id", values[i])
			} else if value.Valid {
				_m.DeviceID = value.String
			}
		case telemetrystream.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case telemetrystream.FieldEndedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field ended_at", values[i])
			} else if value.Valid {
				_m.EndedAt = new(time.Time)
				*_m.EndedAt = value.Time
			}
		case telemetrystream.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case telemetrystream.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TelemetryStream.
// This includes values selected through modifiers, order, etc.
func (_m *TelemetryStream) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPoints queries the "points" edge of the TelemetryStream entity.
func (_m *TelemetryStream) QueryPoints() *TelemetryPointQuery {
	return NewTelemetryStreamClient(_m.config).QueryPoints(_m)
}

// Update returns a builder for updating this TelemetryStream.
// Note that you need to call TelemetryStream.Unwrap() before calling this method if this TelemetryStream
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TelemetryStream) Update() *TelemetryStreamUpdateOne {
	return NewTelemetryStreamClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TelemetryStream entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TelemetryStream) Unwrap() *TelemetryStream {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TelemetryStream is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TelemetryStream) String() string {
	var builder strings.Builder
	builder.WriteString("TelemetryStream(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("fleet_member_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.FleetMemberID))
	builder.WriteString(", ")
	builder.WriteString("device_id=")
	builder.WriteString(_m.DeviceID)
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.EndedAt; v != nil {
		builder.WriteString("ended_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteByte(')')
	return builder.String()
}

// TelemetryStreams is a parsable slice of TelemetryStream.
type TelemetryStreams []*TelemetryStream
