// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/logistics-service/internal/ent/telemetrypoint"
	"github.com/bengobox/logistics-service/internal/ent/telemetrystream"
	"github.com/google/uuid"
)

// TelemetryPoint is the model entity for the TelemetryPoint schema.
type TelemetryPoint struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// StreamID holds the value of the "stream_id" field.
	StreamID uuid.UUID `json:"stream_id,omitempty"`
	// CapturedAt holds the value of the "captured_at" field.
	CapturedAt time.Time `json:"captured_at,omitempty"`
	// SpeedKph holds the value of the "speed_kph" field.
	SpeedKph float64 `json:"speed_kph,omitempty"`
	// BearingDeg holds the value of the "bearing_deg" field.
	BearingDeg float64 `json:"bearing_deg,omitempty"`
	// AccuracyM holds the value of the "accuracy_m" field.
	AccuracyM float64 `json:"accuracy_m,omitempty"`
	// AltitudeM holds the value of the "altitude_m" field.
	AltitudeM float64 `json:"altitude_m,omitempty"`
	// BatteryPct holds the value of the "battery_pct" field.
	BatteryPct float64 `json:"battery_pct,omitempty"`
	// Temperature reading from IoT sensor (°C) — used for cold chain monitoring
	TemperatureCelsius *float64 `json:"temperature_celsius,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TelemetryPointQuery when eager-loading is set.
	Edges        TelemetryPointEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TelemetryPointEdges holds the relations/edges for other nodes in the graph.
type TelemetryPointEdges struct {
	// Stream holds the value of the stream edge.
	Stream *TelemetryStream `json:"stream,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// StreamOrErr returns the Stream value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TelemetryPointEdges) StreamOrErr() (*TelemetryStream, error) {
	if e.Stream != nil {
		return e.Stream, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: telemetrystream.Label}
	}
	return nil, &NotLoadedError{edge: "stream"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TelemetryPoint) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case telemetrypoint.FieldMetadata:
			values[i] = new([]byte)
		case telemetrypoint.FieldSpeedKph, telemetrypoint.FieldBearingDeg, telemetrypoint.FieldAccuracyM, telemetrypoint.FieldAltitudeM, telemetrypoint.FieldBatteryPct, telemetrypoint.FieldTemperatureCelsius:
			values[i] = new(sql.NullFloat64)
		case telemetrypoint.FieldCapturedAt:
			values[i] = new(sql.NullTime)
		case telemetrypoint.FieldID, telemetrypoint.FieldStreamID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TelemetryPoint fields.
func (_m *TelemetryPoint) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case telemetrypoint.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case telemetrypoint.FieldStreamID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field stream_id", values[i])
			} else if value != nil {
				_m.StreamID = *value
			}
		case telemetrypoint.FieldCapturedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field captured_at", values[i])
			} else if value.Valid {
				_m.CapturedAt = value.Time
			}
		case telemetrypoint.FieldSpeedKph:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field speed_kph", values[i])
			} else if value.Valid {
				_m.SpeedKph = value.Float64
			}
		case telemetrypoint.FieldBearingDeg:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field bearing_deg", values[i])
			} else if value.Valid {
				_m.BearingDeg = value.Float64
			}
		case telemetrypoint.FieldAccuracyM:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field accuracy_m", values[i])
			} else if value.Valid {
				_m.AccuracyM = value.Float64
			}
		case telemetrypoint.FieldAltitudeM:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field altitude_m", values[i])
			} else if value.Valid {
				_m.AltitudeM = value.Float64
			}
		case telemetrypoint.FieldBatteryPct:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field battery_pct", values[i])
			} else if value.Valid {
				_m.BatteryPct = value.Float64
			}
		case telemetrypoint.FieldTemperatureCelsius:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field temperature_celsius", values[i])
			} else if value.Valid {
				_m.TemperatureCelsius = new(float64)
				*_m.TemperatureCelsius = value.Float64
			}
		case telemetrypoint.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TelemetryPoint.
// This includes values selected through modifiers, order, etc.
func (_m *TelemetryPoint) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryStream queries the "stream" edge of the TelemetryPoint entity.
func (_m *TelemetryPoint) QueryStream() *TelemetryStreamQuery {
	return NewTelemetryPointClient(_m.config).QueryStream(_m)
}

// Update returns a builder for updating this TelemetryPoint.
// Note that you need to call TelemetryPoint.Unwrap() before calling this method if this TelemetryPoint
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TelemetryPoint) Update() *TelemetryPointUpdateOne {
	return NewTelemetryPointClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TelemetryPoint entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TelemetryPoint) Unwrap() *TelemetryPoint {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TelemetryPoint is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TelemetryPoint) String() string {
	var builder strings.Builder
	builder.WriteString("TelemetryPoint(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("stream_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.StreamID))
	builder.WriteString(", ")
	builder.WriteString("captured_at=")
	builder.WriteString(_m.CapturedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("speed_kph=")
	builder.WriteString(fmt.Sprintf("%v", _m.SpeedKph))
	builder.WriteString(", ")
	builder.WriteString("bearing_deg=")
	builder.WriteString(fmt.Sprintf("%v", _m.BearingDeg))
	builder.WriteString(", ")
	builder.WriteString("accuracy_m=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccuracyM))
	builder.WriteString(", ")
	builder.WriteString("altitude_m=")
	builder.WriteString(fmt.Sprintf("%v", _m.AltitudeM))
	builder.WriteString(", ")
	builder.WriteString("battery_pct=")
	builder.WriteString(fmt.Sprintf("%v", _m.BatteryPct))
	builder.WriteString(", ")
	if v := _m.TemperatureCelsius; v != nil {
		builder.WriteString("temperature_celsius=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteByte(')')
	return builder.String()
}

// TelemetryPoints is a parsable slice of TelemetryPoint.
type TelemetryPoints []*TelemetryPoint
