// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/logistics-service/internal/ent/tenantsyncevent"
	"github.com/google/uuid"
)

// TenantSyncEventCreate is the builder for creating a TenantSyncEvent entity.
type TenantSyncEventCreate struct {
	config
	mutation *TenantSyncEventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (_c *TenantSyncEventCreate) SetTenantID(v uuid.UUID) *TenantSyncEventCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *TenantSyncEventCreate) SetNillableTenantID(v *uuid.UUID) *TenantSyncEventCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetTenantSlug sets the "tenant_slug" field.
func (_c *TenantSyncEventCreate) SetTenantSlug(v string) *TenantSyncEventCreate {
	_c.mutation.SetTenantSlug(v)
	return _c
}

// SetSourceService sets the "source_service" field.
func (_c *TenantSyncEventCreate) SetSourceService(v string) *TenantSyncEventCreate {
	_c.mutation.SetSourceService(v)
	return _c
}

// SetPayload sets the "payload" field.
func (_c *TenantSyncEventCreate) SetPayload(v map[string]interface{}) *TenantSyncEventCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetSyncedAt sets the "synced_at" field.
func (_c *TenantSyncEventCreate) SetSyncedAt(v time.Time) *TenantSyncEventCreate {
	_c.mutation.SetSyncedAt(v)
	return _c
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_c *TenantSyncEventCreate) SetNillableSyncedAt(v *time.Time) *TenantSyncEventCreate {
	if v != nil {
		_c.SetSyncedAt(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *TenantSyncEventCreate) SetStatus(v string) *TenantSyncEventCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *TenantSyncEventCreate) SetNillableStatus(v *string) *TenantSyncEventCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TenantSyncEventCreate) SetID(v uuid.UUID) *TenantSyncEventCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *TenantSyncEventCreate) SetNillableID(v *uuid.UUID) *TenantSyncEventCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the TenantSyncEventMutation object of the builder.
func (_c *TenantSyncEventCreate) Mutation() *TenantSyncEventMutation {
	return _c.mutation
}

// Save creates the TenantSyncEvent in the database.
func (_c *TenantSyncEventCreate) Save(ctx context.Context) (*TenantSyncEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TenantSyncEventCreate) SaveX(ctx context.Context) *TenantSyncEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TenantSyncEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TenantSyncEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TenantSyncEventCreate) defaults() {
	if _, ok := _c.mutation.SyncedAt(); !ok {
		v := tenantsyncevent.DefaultSyncedAt()
		_c.mutation.SetSyncedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := tenantsyncevent.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := tenantsyncevent.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TenantSyncEventCreate) check() error {
	if _, ok := _c.mutation.TenantSlug(); !ok {
		return &ValidationError{Name: "tenant_slug", err: errors.New(`ent: missing required field "TenantSyncEvent.tenant_slug"`)}
	}
	if v, ok := _c.mutation.TenantSlug(); ok {
		if err := tenantsyncevent.TenantSlugValidator(v); err != nil {
			return &ValidationError{Name: "tenant_slug", err: fmt.Errorf(`ent: validator failed for field "TenantSyncEvent.tenant_slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceService(); !ok {
		return &ValidationError{Name: "source_service", err: errors.New(`ent: missing required field "TenantSyncEvent.source_service"`)}
	}
	if v, ok := _c.mutation.SourceService(); ok {
		if err := tenantsyncevent.SourceServiceValidator(v); err != nil {
			return &ValidationError{Name: "source_service", err: fmt.Errorf(`ent: validator failed for field "TenantSyncEvent.source_service": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "TenantSyncEvent.payload"`)}
	}
	if _, ok := _c.mutation.SyncedAt(); !ok {
		return &ValidationError{Name: "synced_at", err: errors.New(`ent: missing required field "TenantSyncEvent.synced_at"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "TenantSyncEvent.status"`)}
	}
	return nil
}

func (_c *TenantSyncEventCreate) sqlSave(ctx context.Context) (*TenantSyncEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TenantSyncEventCreate) createSpec() (*TenantSyncEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &TenantSyncEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tenantsyncevent.Table, sqlgraph.NewFieldSpec(tenantsyncevent.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(tenantsyncevent.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.TenantSlug(); ok {
		_spec.SetField(tenantsyncevent.FieldTenantSlug, field.TypeString, value)
		_node.TenantSlug = value
	}
	if value, ok := _c.mutation.SourceService(); ok {
		_spec.SetField(tenantsyncevent.FieldSourceService, field.TypeString, value)
		_node.SourceService = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(tenantsyncevent.FieldPayload, field.TypeJSON, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.SyncedAt(); ok {
		_spec.SetField(tenantsyncevent.FieldSyncedAt, field.TypeTime, value)
		_node.SyncedAt = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(tenantsyncevent.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TenantSyncEvent.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TenantSyncEventUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *TenantSyncEventCreate) OnConflict(opts ...sql.ConflictOption) *TenantSyncEventUpsertOne {
	_c.conflict = opts
	return &TenantSyncEventUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TenantSyncEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TenantSyncEventCreate) OnConflictColumns(columns ...string) *TenantSyncEventUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TenantSyncEventUpsertOne{
		create: _c,
	}
}

type (
	// TenantSyncEventUpsertOne is the builder for "upsert"-ing
	//  one TenantSyncEvent node.
	TenantSyncEventUpsertOne struct {
		create *TenantSyncEventCreate
	}

	// TenantSyncEventUpsert is the "OnConflict" setter.
	TenantSyncEventUpsert struct {
		*sql.UpdateSet
	}
)

// SetTenantID sets the "tenant_id" field.
func (u *TenantSyncEventUpsert) SetTenantID(v uuid.UUID) *TenantSyncEventUpsert {
	u.Set(tenantsyncevent.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *TenantSyncEventUpsert) UpdateTenantID() *TenantSyncEventUpsert {
	u.SetExcluded(tenantsyncevent.FieldTenantID)
	return u
}

// ClearTenantID clears the value of the "tenant_id" field.
func (u *TenantSyncEventUpsert) ClearTenantID() *TenantSyncEventUpsert {
	u.SetNull(tenantsyncevent.FieldTenantID)
	return u
}

// SetTenantSlug sets the "tenant_slug" field.
func (u *TenantSyncEventUpsert) SetTenantSlug(v string) *TenantSyncEventUpsert {
	u.Set(tenantsyncevent.FieldTenantSlug, v)
	return u
}

// UpdateTenantSlug sets the "tenant_slug" field to the value that was provided on create.
func (u *TenantSyncEventUpsert) UpdateTenantSlug() *TenantSyncEventUpsert {
	u.SetExcluded(tenantsyncevent.FieldTenantSlug)
	return u
}

// SetSourceService sets the "source_service" field.
func (u *TenantSyncEventUpsert) SetSourceService(v string) *TenantSyncEventUpsert {
	u.Set(tenantsyncevent.FieldSourceService, v)
	return u
}

// UpdateSourceService sets the "source_service" field to the value that was provided on create.
func (u *TenantSyncEventUpsert) UpdateSourceService() *TenantSyncEventUpsert {
	u.SetExcluded(tenantsyncevent.FieldSourceService)
	return u
}

// SetPayload sets the "payload" field.
func (u *TenantSyncEventUpsert) SetPayload(v map[string]interface{}) *TenantSyncEventUpsert {
	u.Set(tenantsyncevent.FieldPayload, v)
	return u
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *TenantSyncEventUpsert) UpdatePayload() *TenantSyncEventUpsert {
	u.SetExcluded(tenantsyncevent.FieldPayload)
	return u
}

// SetSyncedAt sets the "synced_at" field.
func (u *TenantSyncEventUpsert) SetSyncedAt(v time.Time) *TenantSyncEventUpsert {
	u.Set(tenantsyncevent.FieldSyncedAt, v)
	return u
}

// UpdateSyncedAt sets the "synced_at" field to the value that was provided on create.
func (u *TenantSyncEventUpsert) UpdateSyncedAt() *TenantSyncEventUpsert {
	u.SetExcluded(tenantsyncevent.FieldSyncedAt)
	return u
}

// SetStatus sets the "status" field.
func (u *TenantSyncEventUpsert) SetStatus(v string) *TenantSyncEventUpsert {
	u.Set(tenantsyncevent.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TenantSyncEventUpsert) UpdateStatus() *TenantSyncEventUpsert {
	u.SetExcluded(tenantsyncevent.FieldStatus)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.TenantSyncEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(tenantsyncevent.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TenantSyncEventUpsertOne) UpdateNewValues() *TenantSyncEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(tenantsyncevent.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TenantSyncEvent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TenantSyncEventUpsertOne) Ignore() *TenantSyncEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TenantSyncEventUpsertOne) DoNothing() *TenantSyncEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TenantSyncEventCreate.OnConflict
// documentation for more info.
func (u *TenantSyncEventUpsertOne) Update(set func(*TenantSyncEventUpsert)) *TenantSyncEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TenantSyncEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *TenantSyncEventUpsertOne) SetTenantID(v uuid.UUID) *TenantSyncEventUpsertOne {
	return u.Update(func(s *TenantSyncEventUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *TenantSyncEventUpsertOne) UpdateTenantID() *TenantSyncEventUpsertOne {
	return u.Update(func(s *TenantSyncEventUpsert) {
		s.UpdateTenantID()
	})
}

// ClearTenantID clears the value of the "tenant_id" field.
func (u *TenantSyncEventUpsertOne) ClearTenantID() *TenantSyncEventUpsertOne {
	return u.Update(func(s *TenantSyncEventUpsert) {
		s.ClearTenantID()
	})
}

// SetTenantSlug sets the "tenant_slug" field.
func (u *TenantSyncEventUpsertOne) SetTenantSlug(v string) *TenantSyncEventUpsertOne {
	return u.Update(func(s *TenantSyncEventUpsert) {
		s.SetTenantSlug(v)
	})
}

// UpdateTenantSlug sets the "tenant_slug" field to the value that was provided on create.
func (u *TenantSyncEventUpsertOne) UpdateTenantSlug() *TenantSyncEventUpsertOne {
	return u.Update(func(s *TenantSyncEventUpsert) {
		s.UpdateTenantSlug()
	})
}

// SetSourceService sets the "source_service" field.
func (u *TenantSyncEventUpsertOne) SetSourceService(v string) *TenantSyncEventUpsertOne {
	return u.Update(func(s *TenantSyncEventUpsert) {
		s.SetSourceService(v)
	})
}

// UpdateSourceService sets the "source_service" field to the value that was provided on create.
func (u *TenantSyncEventUpsertOne) UpdateSourceService() *TenantSyncEventUpsertOne {
	return u.Update(func(s *TenantSyncEventUpsert) {
		s.UpdateSourceService()
	})
}

// SetPayload sets the "payload" field.
func (u *TenantSyncEventUpsertOne) SetPayload(v map[string]interface{}) *TenantSyncEventUpsertOne {
	return u.Update(func(s *TenantSyncEventUpsert) {
		s.SetPayload(v)
	})
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *TenantSyncEventUpsertOne) UpdatePayload() *TenantSyncEventUpsertOne {
	return u.Update(func(s *TenantSyncEventUpsert) {
		s.UpdatePayload()
	})
}

// SetSyncedAt sets the "synced_at" field.
func (u *TenantSyncEventUpsertOne) SetSyncedAt(v time.Time) *TenantSyncEventUpsertOne {
	return u.Update(func(s *TenantSyncEventUpsert) {
		s.SetSyncedAt(v)
	})
}

// UpdateSyncedAt sets the "synced_at" field to the value that was provided on create.
func (u *TenantSyncEventUpsertOne) UpdateSyncedAt() *TenantSyncEventUpsertOne {
	return u.Update(func(s *TenantSyncEventUpsert) {
		s.UpdateSyncedAt()
	})
}

// SetStatus sets the "status" field.
func (u *TenantSyncEventUpsertOne) SetStatus(v string) *TenantSyncEventUpsertOne {
	return u.Update(func(s *TenantSyncEventUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TenantSyncEventUpsertOne) UpdateStatus() *TenantSyncEventUpsertOne {
	return u.Update(func(s *TenantSyncEventUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *TenantSyncEventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TenantSyncEventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TenantSyncEventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TenantSyncEventUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: TenantSyncEventUpsertOne.ID is not supported by MySQL driver. Use TenantSyncEventUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TenantSyncEventUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TenantSyncEventCreateBulk is the builder for creating many TenantSyncEvent entities in bulk.
type TenantSyncEventCreateBulk struct {
	config
	err      error
	builders []*TenantSyncEventCreate
	conflict []sql.ConflictOption
}

// Save creates the TenantSyncEvent entities in the database.
func (_c *TenantSyncEventCreateBulk) Save(ctx context.Context) ([]*TenantSyncEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TenantSyncEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TenantSyncEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TenantSyncEventCreateBulk) SaveX(ctx context.Context) []*TenantSyncEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TenantSyncEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TenantSyncEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TenantSyncEvent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TenantSyncEventUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *TenantSyncEventCreateBulk) OnConflict(opts ...sql.ConflictOption) *TenantSyncEventUpsertBulk {
	_c.conflict = opts
	return &TenantSyncEventUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TenantSyncEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TenantSyncEventCreateBulk) OnConflictColumns(columns ...string) *TenantSyncEventUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TenantSyncEventUpsertBulk{
		create: _c,
	}
}

// TenantSyncEventUpsertBulk is the builder for "upsert"-ing
// a bulk of TenantSyncEvent nodes.
type TenantSyncEventUpsertBulk struct {
	create *TenantSyncEventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TenantSyncEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(tenantsyncevent.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TenantSyncEventUpsertBulk) UpdateNewValues() *TenantSyncEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(tenantsyncevent.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TenantSyncEvent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TenantSyncEventUpsertBulk) Ignore() *TenantSyncEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TenantSyncEventUpsertBulk) DoNothing() *TenantSyncEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TenantSyncEventCreateBulk.OnConflict
// documentation for more info.
func (u *TenantSyncEventUpsertBulk) Update(set func(*TenantSyncEventUpsert)) *TenantSyncEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TenantSyncEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *TenantSyncEventUpsertBulk) SetTenantID(v uuid.UUID) *TenantSyncEventUpsertBulk {
	return u.Update(func(s *TenantSyncEventUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *TenantSyncEventUpsertBulk) UpdateTenantID() *TenantSyncEventUpsertBulk {
	return u.Update(func(s *TenantSyncEventUpsert) {
		s.UpdateTenantID()
	})
}

// ClearTenantID clears the value of the "tenant_id" field.
func (u *TenantSyncEventUpsertBulk) ClearTenantID() *TenantSyncEventUpsertBulk {
	return u.Update(func(s *TenantSyncEventUpsert) {
		s.ClearTenantID()
	})
}

// SetTenantSlug sets the "tenant_slug" field.
func (u *TenantSyncEventUpsertBulk) SetTenantSlug(v string) *TenantSyncEventUpsertBulk {
	return u.Update(func(s *TenantSyncEventUpsert) {
		s.SetTenantSlug(v)
	})
}

// UpdateTenantSlug sets the "tenant_slug" field to the value that was provided on create.
func (u *TenantSyncEventUpsertBulk) UpdateTenantSlug() *TenantSyncEventUpsertBulk {
	return u.Update(func(s *TenantSyncEventUpsert) {
		s.UpdateTenantSlug()
	})
}

// SetSourceService sets the "source_service" field.
func (u *TenantSyncEventUpsertBulk) SetSourceService(v string) *TenantSyncEventUpsertBulk {
	return u.Update(func(s *TenantSyncEventUpsert) {
		s.SetSourceService(v)
	})
}

// UpdateSourceService sets the "source_service" field to the value that was provided on create.
func (u *TenantSyncEventUpsertBulk) UpdateSourceService() *TenantSyncEventUpsertBulk {
	return u.Update(func(s *TenantSyncEventUpsert) {
		s.UpdateSourceService()
	})
}

// SetPayload sets the "payload" field.
func (u *TenantSyncEventUpsertBulk) SetPayload(v map[string]interface{}) *TenantSyncEventUpsertBulk {
	return u.Update(func(s *TenantSyncEventUpsert) {
		s.SetPayload(v)
	})
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *TenantSyncEventUpsertBulk) UpdatePayload() *TenantSyncEventUpsertBulk {
	return u.Update(func(s *TenantSyncEventUpsert) {
		s.UpdatePayload()
	})
}

// SetSyncedAt sets the "synced_at" field.
func (u *TenantSyncEventUpsertBulk) SetSyncedAt(v time.Time) *TenantSyncEventUpsertBulk {
	return u.Update(func(s *TenantSyncEventUpsert) {
		s.SetSyncedAt(v)
	})
}

// UpdateSyncedAt sets the "synced_at" field to the value that was provided on create.
func (u *TenantSyncEventUpsertBulk) UpdateSyncedAt() *TenantSyncEventUpsertBulk {
	return u.Update(func(s *TenantSyncEventUpsert) {
		s.UpdateSyncedAt()
	})
}

// SetStatus sets the "status" field.
func (u *TenantSyncEventUpsertBulk) SetStatus(v string) *TenantSyncEventUpsertBulk {
	return u.Update(func(s *TenantSyncEventUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TenantSyncEventUpsertBulk) UpdateStatus() *TenantSyncEventUpsertBulk {
	return u.Update(func(s *TenantSyncEventUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *TenantSyncEventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TenantSyncEventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TenantSyncEventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TenantSyncEventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
