// Code generated by ent, DO NOT EDIT.

package fleetmember

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/bengobox/logistics-service/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldEQ(FieldTenantID, v))
}

// FleetID applies equality check predicate on the "fleet_id" field. It's identical to FleetIDEQ.
func FleetID(v uuid.UUID) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldEQ(FieldFleetID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldEQ(FieldUserID, v))
}

// DriverCode applies equality check predicate on the "driver_code" field. It's identical to DriverCodeEQ.
func DriverCode(v string) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldEQ(FieldDriverCode, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldEQ(FieldStatus, v))
}

// VehicleID applies equality check predicate on the "vehicle_id" field. It's identical to VehicleIDEQ.
func VehicleID(v uuid.UUID) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldEQ(FieldVehicleID, v))
}

// JoinedAt applies equality check predicate on the "joined_at" field. It's identical to JoinedAtEQ.
func JoinedAt(v time.Time) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldEQ(FieldJoinedAt, v))
}

// SuspendedAt applies equality check predicate on the "suspended_at" field. It's identical to SuspendedAtEQ.
func SuspendedAt(v time.Time) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldEQ(FieldSuspendedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uuid.UUID) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uuid.UUID) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uuid.UUID) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uuid.UUID) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldLTE(FieldTenantID, v))
}

// FleetIDEQ applies the EQ predicate on the "fleet_id" field.
func FleetIDEQ(v uuid.UUID) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldEQ(FieldFleetID, v))
}

// FleetIDNEQ applies the NEQ predicate on the "fleet_id" field.
func FleetIDNEQ(v uuid.UUID) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldNEQ(FieldFleetID, v))
}

// FleetIDIn applies the In predicate on the "fleet_id" field.
func FleetIDIn(vs ...uuid.UUID) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldIn(FieldFleetID, vs...))
}

// FleetIDNotIn applies the NotIn predicate on the "fleet_id" field.
func FleetIDNotIn(vs ...uuid.UUID) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldNotIn(FieldFleetID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldNotIn(FieldUserID, vs...))
}

// DriverCodeEQ applies the EQ predicate on the "driver_code" field.
func DriverCodeEQ(v string) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldEQ(FieldDriverCode, v))
}

// DriverCodeNEQ applies the NEQ predicate on the "driver_code" field.
func DriverCodeNEQ(v string) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldNEQ(FieldDriverCode, v))
}

// DriverCodeIn applies the In predicate on the "driver_code" field.
func DriverCodeIn(vs ...string) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldIn(FieldDriverCode, vs...))
}

// DriverCodeNotIn applies the NotIn predicate on the "driver_code" field.
func DriverCodeNotIn(vs ...string) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldNotIn(FieldDriverCode, vs...))
}

// DriverCodeGT applies the GT predicate on the "driver_code" field.
func DriverCodeGT(v string) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldGT(FieldDriverCode, v))
}

// DriverCodeGTE applies the GTE predicate on the "driver_code" field.
func DriverCodeGTE(v string) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldGTE(FieldDriverCode, v))
}

// DriverCodeLT applies the LT predicate on the "driver_code" field.
func DriverCodeLT(v string) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldLT(FieldDriverCode, v))
}

// DriverCodeLTE applies the LTE predicate on the "driver_code" field.
func DriverCodeLTE(v string) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldLTE(FieldDriverCode, v))
}

// DriverCodeContains applies the Contains predicate on the "driver_code" field.
func DriverCodeContains(v string) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldContains(FieldDriverCode, v))
}

// DriverCodeHasPrefix applies the HasPrefix predicate on the "driver_code" field.
func DriverCodeHasPrefix(v string) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldHasPrefix(FieldDriverCode, v))
}

// DriverCodeHasSuffix applies the HasSuffix predicate on the "driver_code" field.
func DriverCodeHasSuffix(v string) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldHasSuffix(FieldDriverCode, v))
}

// DriverCodeIsNil applies the IsNil predicate on the "driver_code" field.
func DriverCodeIsNil() predicate.FleetMember {
	return predicate.FleetMember(sql.FieldIsNull(FieldDriverCode))
}

// DriverCodeNotNil applies the NotNil predicate on the "driver_code" field.
func DriverCodeNotNil() predicate.FleetMember {
	return predicate.FleetMember(sql.FieldNotNull(FieldDriverCode))
}

// DriverCodeEqualFold applies the EqualFold predicate on the "driver_code" field.
func DriverCodeEqualFold(v string) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldEqualFold(FieldDriverCode, v))
}

// DriverCodeContainsFold applies the ContainsFold predicate on the "driver_code" field.
func DriverCodeContainsFold(v string) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldContainsFold(FieldDriverCode, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldContainsFold(FieldStatus, v))
}

// VehicleIDEQ applies the EQ predicate on the "vehicle_id" field.
func VehicleIDEQ(v uuid.UUID) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldEQ(FieldVehicleID, v))
}

// VehicleIDNEQ applies the NEQ predicate on the "vehicle_id" field.
func VehicleIDNEQ(v uuid.UUID) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldNEQ(FieldVehicleID, v))
}

// VehicleIDIn applies the In predicate on the "vehicle_id" field.
func VehicleIDIn(vs ...uuid.UUID) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldIn(FieldVehicleID, vs...))
}

// VehicleIDNotIn applies the NotIn predicate on the "vehicle_id" field.
func VehicleIDNotIn(vs ...uuid.UUID) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldNotIn(FieldVehicleID, vs...))
}

// VehicleIDIsNil applies the IsNil predicate on the "vehicle_id" field.
func VehicleIDIsNil() predicate.FleetMember {
	return predicate.FleetMember(sql.FieldIsNull(FieldVehicleID))
}

// VehicleIDNotNil applies the NotNil predicate on the "vehicle_id" field.
func VehicleIDNotNil() predicate.FleetMember {
	return predicate.FleetMember(sql.FieldNotNull(FieldVehicleID))
}

// JoinedAtEQ applies the EQ predicate on the "joined_at" field.
func JoinedAtEQ(v time.Time) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldEQ(FieldJoinedAt, v))
}

// JoinedAtNEQ applies the NEQ predicate on the "joined_at" field.
func JoinedAtNEQ(v time.Time) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldNEQ(FieldJoinedAt, v))
}

// JoinedAtIn applies the In predicate on the "joined_at" field.
func JoinedAtIn(vs ...time.Time) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldIn(FieldJoinedAt, vs...))
}

// JoinedAtNotIn applies the NotIn predicate on the "joined_at" field.
func JoinedAtNotIn(vs ...time.Time) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldNotIn(FieldJoinedAt, vs...))
}

// JoinedAtGT applies the GT predicate on the "joined_at" field.
func JoinedAtGT(v time.Time) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldGT(FieldJoinedAt, v))
}

// JoinedAtGTE applies the GTE predicate on the "joined_at" field.
func JoinedAtGTE(v time.Time) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldGTE(FieldJoinedAt, v))
}

// JoinedAtLT applies the LT predicate on the "joined_at" field.
func JoinedAtLT(v time.Time) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldLT(FieldJoinedAt, v))
}

// JoinedAtLTE applies the LTE predicate on the "joined_at" field.
func JoinedAtLTE(v time.Time) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldLTE(FieldJoinedAt, v))
}

// SuspendedAtEQ applies the EQ predicate on the "suspended_at" field.
func SuspendedAtEQ(v time.Time) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldEQ(FieldSuspendedAt, v))
}

// SuspendedAtNEQ applies the NEQ predicate on the "suspended_at" field.
func SuspendedAtNEQ(v time.Time) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldNEQ(FieldSuspendedAt, v))
}

// SuspendedAtIn applies the In predicate on the "suspended_at" field.
func SuspendedAtIn(vs ...time.Time) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldIn(FieldSuspendedAt, vs...))
}

// SuspendedAtNotIn applies the NotIn predicate on the "suspended_at" field.
func SuspendedAtNotIn(vs ...time.Time) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldNotIn(FieldSuspendedAt, vs...))
}

// SuspendedAtGT applies the GT predicate on the "suspended_at" field.
func SuspendedAtGT(v time.Time) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldGT(FieldSuspendedAt, v))
}

// SuspendedAtGTE applies the GTE predicate on the "suspended_at" field.
func SuspendedAtGTE(v time.Time) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldGTE(FieldSuspendedAt, v))
}

// SuspendedAtLT applies the LT predicate on the "suspended_at" field.
func SuspendedAtLT(v time.Time) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldLT(FieldSuspendedAt, v))
}

// SuspendedAtLTE applies the LTE predicate on the "suspended_at" field.
func SuspendedAtLTE(v time.Time) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldLTE(FieldSuspendedAt, v))
}

// SuspendedAtIsNil applies the IsNil predicate on the "suspended_at" field.
func SuspendedAtIsNil() predicate.FleetMember {
	return predicate.FleetMember(sql.FieldIsNull(FieldSuspendedAt))
}

// SuspendedAtNotNil applies the NotNil predicate on the "suspended_at" field.
func SuspendedAtNotNil() predicate.FleetMember {
	return predicate.FleetMember(sql.FieldNotNull(FieldSuspendedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.FleetMember {
	return predicate.FleetMember(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasFleet applies the HasEdge predicate on the "fleet" edge.
func HasFleet() predicate.FleetMember {
	return predicate.FleetMember(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, FleetTable, FleetColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFleetWith applies the HasEdge predicate on the "fleet" edge with a given conditions (other predicates).
func HasFleetWith(preds ...predicate.Fleet) predicate.FleetMember {
	return predicate.FleetMember(func(s *sql.Selector) {
		step := newFleetStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.FleetMember {
	return predicate.FleetMember(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.FleetMember {
	return predicate.FleetMember(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasVehicle applies the HasEdge predicate on the "vehicle" edge.
func HasVehicle() predicate.FleetMember {
	return predicate.FleetMember(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, VehicleTable, VehicleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVehicleWith applies the HasEdge predicate on the "vehicle" edge with a given conditions (other predicates).
func HasVehicleWith(preds ...predicate.Vehicle) predicate.FleetMember {
	return predicate.FleetMember(func(s *sql.Selector) {
		step := newVehicleStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAssignments applies the HasEdge predicate on the "assignments" edge.
func HasAssignments() predicate.FleetMember {
	return predicate.FleetMember(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AssignmentsTable, AssignmentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAssignmentsWith applies the HasEdge predicate on the "assignments" edge with a given conditions (other predicates).
func HasAssignmentsWith(preds ...predicate.TaskAssignment) predicate.FleetMember {
	return predicate.FleetMember(func(s *sql.Selector) {
		step := newAssignmentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FleetMember) predicate.FleetMember {
	return predicate.FleetMember(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FleetMember) predicate.FleetMember {
	return predicate.FleetMember(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FleetMember) predicate.FleetMember {
	return predicate.FleetMember(sql.NotPredicates(p))
}
