// Code generated by ent, DO NOT EDIT.

package telemetrystream

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/bengobox/logistics-service/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldEQ(FieldTenantID, v))
}

// FleetMemberID applies equality check predicate on the "fleet_member_id" field. It's identical to FleetMemberIDEQ.
func FleetMemberID(v uuid.UUID) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldEQ(FieldFleetMemberID, v))
}

// DeviceID applies equality check predicate on the "device_id" field. It's identical to DeviceIDEQ.
func DeviceID(v string) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldEQ(FieldDeviceID, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldEQ(FieldStartedAt, v))
}

// EndedAt applies equality check predicate on the "ended_at" field. It's identical to EndedAtEQ.
func EndedAt(v time.Time) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldEQ(FieldEndedAt, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldEQ(FieldStatus, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uuid.UUID) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uuid.UUID) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uuid.UUID) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uuid.UUID) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldLTE(FieldTenantID, v))
}

// FleetMemberIDEQ applies the EQ predicate on the "fleet_member_id" field.
func FleetMemberIDEQ(v uuid.UUID) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldEQ(FieldFleetMemberID, v))
}

// FleetMemberIDNEQ applies the NEQ predicate on the "fleet_member_id" field.
func FleetMemberIDNEQ(v uuid.UUID) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldNEQ(FieldFleetMemberID, v))
}

// FleetMemberIDIn applies the In predicate on the "fleet_member_id" field.
func FleetMemberIDIn(vs ...uuid.UUID) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldIn(FieldFleetMemberID, vs...))
}

// FleetMemberIDNotIn applies the NotIn predicate on the "fleet_member_id" field.
func FleetMemberIDNotIn(vs ...uuid.UUID) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldNotIn(FieldFleetMemberID, vs...))
}

// FleetMemberIDGT applies the GT predicate on the "fleet_member_id" field.
func FleetMemberIDGT(v uuid.UUID) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldGT(FieldFleetMemberID, v))
}

// FleetMemberIDGTE applies the GTE predicate on the "fleet_member_id" field.
func FleetMemberIDGTE(v uuid.UUID) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldGTE(FieldFleetMemberID, v))
}

// FleetMemberIDLT applies the LT predicate on the "fleet_member_id" field.
func FleetMemberIDLT(v uuid.UUID) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldLT(FieldFleetMemberID, v))
}

// FleetMemberIDLTE applies the LTE predicate on the "fleet_member_id" field.
func FleetMemberIDLTE(v uuid.UUID) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldLTE(FieldFleetMemberID, v))
}

// DeviceIDEQ applies the EQ predicate on the "device_id" field.
func DeviceIDEQ(v string) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldEQ(FieldDeviceID, v))
}

// DeviceIDNEQ applies the NEQ predicate on the "device_id" field.
func DeviceIDNEQ(v string) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldNEQ(FieldDeviceID, v))
}

// DeviceIDIn applies the In predicate on the "device_id" field.
func DeviceIDIn(vs ...string) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldIn(FieldDeviceID, vs...))
}

// DeviceIDNotIn applies the NotIn predicate on the "device_id" field.
func DeviceIDNotIn(vs ...string) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldNotIn(FieldDeviceID, vs...))
}

// DeviceIDGT applies the GT predicate on the "device_id" field.
func DeviceIDGT(v string) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldGT(FieldDeviceID, v))
}

// DeviceIDGTE applies the GTE predicate on the "device_id" field.
func DeviceIDGTE(v string) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldGTE(FieldDeviceID, v))
}

// DeviceIDLT applies the LT predicate on the "device_id" field.
func DeviceIDLT(v string) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldLT(FieldDeviceID, v))
}

// DeviceIDLTE applies the LTE predicate on the "device_id" field.
func DeviceIDLTE(v string) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldLTE(FieldDeviceID, v))
}

// DeviceIDContains applies the Contains predicate on the "device_id" field.
func DeviceIDContains(v string) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldContains(FieldDeviceID, v))
}

// DeviceIDHasPrefix applies the HasPrefix predicate on the "device_id" field.
func DeviceIDHasPrefix(v string) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldHasPrefix(FieldDeviceID, v))
}

// DeviceIDHasSuffix applies the HasSuffix predicate on the "device_id" field.
func DeviceIDHasSuffix(v string) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldHasSuffix(FieldDeviceID, v))
}

// DeviceIDIsNil applies the IsNil predicate on the "device_id" field.
func DeviceIDIsNil() predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldIsNull(FieldDeviceID))
}

// DeviceIDNotNil applies the NotNil predicate on the "device_id" field.
func DeviceIDNotNil() predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldNotNull(FieldDeviceID))
}

// DeviceIDEqualFold applies the EqualFold predicate on the "device_id" field.
func DeviceIDEqualFold(v string) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldEqualFold(FieldDeviceID, v))
}

// DeviceIDContainsFold applies the ContainsFold predicate on the "device_id" field.
func DeviceIDContainsFold(v string) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldContainsFold(FieldDeviceID, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldLTE(FieldStartedAt, v))
}

// EndedAtEQ applies the EQ predicate on the "ended_at" field.
func EndedAtEQ(v time.Time) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldEQ(FieldEndedAt, v))
}

// EndedAtNEQ applies the NEQ predicate on the "ended_at" field.
func EndedAtNEQ(v time.Time) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldNEQ(FieldEndedAt, v))
}

// EndedAtIn applies the In predicate on the "ended_at" field.
func EndedAtIn(vs ...time.Time) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldIn(FieldEndedAt, vs...))
}

// EndedAtNotIn applies the NotIn predicate on the "ended_at" field.
func EndedAtNotIn(vs ...time.Time) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldNotIn(FieldEndedAt, vs...))
}

// EndedAtGT applies the GT predicate on the "ended_at" field.
func EndedAtGT(v time.Time) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldGT(FieldEndedAt, v))
}

// EndedAtGTE applies the GTE predicate on the "ended_at" field.
func EndedAtGTE(v time.Time) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldGTE(FieldEndedAt, v))
}

// EndedAtLT applies the LT predicate on the "ended_at" field.
func EndedAtLT(v time.Time) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldLT(FieldEndedAt, v))
}

// EndedAtLTE applies the LTE predicate on the "ended_at" field.
func EndedAtLTE(v time.Time) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldLTE(FieldEndedAt, v))
}

// EndedAtIsNil applies the IsNil predicate on the "ended_at" field.
func EndedAtIsNil() predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldIsNull(FieldEndedAt))
}

// EndedAtNotNil applies the NotNil predicate on the "ended_at" field.
func EndedAtNotNil() predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldNotNull(FieldEndedAt))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.FieldContainsFold(FieldStatus, v))
}

// HasPoints applies the HasEdge predicate on the "points" edge.
func HasPoints() predicate.TelemetryStream {
	return predicate.TelemetryStream(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PointsTable, PointsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPointsWith applies the HasEdge predicate on the "points" edge with a given conditions (other predicates).
func HasPointsWith(preds ...predicate.TelemetryPoint) predicate.TelemetryStream {
	return predicate.TelemetryStream(func(s *sql.Selector) {
		step := newPointsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TelemetryStream) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TelemetryStream) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TelemetryStream) predicate.TelemetryStream {
	return predicate.TelemetryStream(sql.NotPredicates(p))
}
