// Code generated by ent, DO NOT EDIT.

package taskevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/bengobox/logistics-service/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldLTE(FieldID, id))
}

// TaskID applies equality check predicate on the "task_id" field. It's identical to TaskIDEQ.
func TaskID(v uuid.UUID) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldEQ(FieldTaskID, v))
}

// EventType applies equality check predicate on the "event_type" field. It's identical to EventTypeEQ.
func EventType(v string) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldEQ(FieldEventType, v))
}

// ActorID applies equality check predicate on the "actor_id" field. It's identical to ActorIDEQ.
func ActorID(v uuid.UUID) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldEQ(FieldActorID, v))
}

// ActorType applies equality check predicate on the "actor_type" field. It's identical to ActorTypeEQ.
func ActorType(v string) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldEQ(FieldActorType, v))
}

// OccurredAt applies equality check predicate on the "occurred_at" field. It's identical to OccurredAtEQ.
func OccurredAt(v time.Time) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldEQ(FieldOccurredAt, v))
}

// TaskIDEQ applies the EQ predicate on the "task_id" field.
func TaskIDEQ(v uuid.UUID) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldEQ(FieldTaskID, v))
}

// TaskIDNEQ applies the NEQ predicate on the "task_id" field.
func TaskIDNEQ(v uuid.UUID) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldNEQ(FieldTaskID, v))
}

// TaskIDIn applies the In predicate on the "task_id" field.
func TaskIDIn(vs ...uuid.UUID) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldIn(FieldTaskID, vs...))
}

// TaskIDNotIn applies the NotIn predicate on the "task_id" field.
func TaskIDNotIn(vs ...uuid.UUID) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldNotIn(FieldTaskID, vs...))
}

// EventTypeEQ applies the EQ predicate on the "event_type" field.
func EventTypeEQ(v string) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldEQ(FieldEventType, v))
}

// EventTypeNEQ applies the NEQ predicate on the "event_type" field.
func EventTypeNEQ(v string) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldNEQ(FieldEventType, v))
}

// EventTypeIn applies the In predicate on the "event_type" field.
func EventTypeIn(vs ...string) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldIn(FieldEventType, vs...))
}

// EventTypeNotIn applies the NotIn predicate on the "event_type" field.
func EventTypeNotIn(vs ...string) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldNotIn(FieldEventType, vs...))
}

// EventTypeGT applies the GT predicate on the "event_type" field.
func EventTypeGT(v string) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldGT(FieldEventType, v))
}

// EventTypeGTE applies the GTE predicate on the "event_type" field.
func EventTypeGTE(v string) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldGTE(FieldEventType, v))
}

// EventTypeLT applies the LT predicate on the "event_type" field.
func EventTypeLT(v string) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldLT(FieldEventType, v))
}

// EventTypeLTE applies the LTE predicate on the "event_type" field.
func EventTypeLTE(v string) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldLTE(FieldEventType, v))
}

// EventTypeContains applies the Contains predicate on the "event_type" field.
func EventTypeContains(v string) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldContains(FieldEventType, v))
}

// EventTypeHasPrefix applies the HasPrefix predicate on the "event_type" field.
func EventTypeHasPrefix(v string) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldHasPrefix(FieldEventType, v))
}

// EventTypeHasSuffix applies the HasSuffix predicate on the "event_type" field.
func EventTypeHasSuffix(v string) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldHasSuffix(FieldEventType, v))
}

// EventTypeEqualFold applies the EqualFold predicate on the "event_type" field.
func EventTypeEqualFold(v string) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldEqualFold(FieldEventType, v))
}

// EventTypeContainsFold applies the ContainsFold predicate on the "event_type" field.
func EventTypeContainsFold(v string) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldContainsFold(FieldEventType, v))
}

// ActorIDEQ applies the EQ predicate on the "actor_id" field.
func ActorIDEQ(v uuid.UUID) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldEQ(FieldActorID, v))
}

// ActorIDNEQ applies the NEQ predicate on the "actor_id" field.
func ActorIDNEQ(v uuid.UUID) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldNEQ(FieldActorID, v))
}

// ActorIDIn applies the In predicate on the "actor_id" field.
func ActorIDIn(vs ...uuid.UUID) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldIn(FieldActorID, vs...))
}

// ActorIDNotIn applies the NotIn predicate on the "actor_id" field.
func ActorIDNotIn(vs ...uuid.UUID) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldNotIn(FieldActorID, vs...))
}

// ActorIDGT applies the GT predicate on the "actor_id" field.
func ActorIDGT(v uuid.UUID) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldGT(FieldActorID, v))
}

// ActorIDGTE applies the GTE predicate on the "actor_id" field.
func ActorIDGTE(v uuid.UUID) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldGTE(FieldActorID, v))
}

// ActorIDLT applies the LT predicate on the "actor_id" field.
func ActorIDLT(v uuid.UUID) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldLT(FieldActorID, v))
}

// ActorIDLTE applies the LTE predicate on the "actor_id" field.
func ActorIDLTE(v uuid.UUID) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldLTE(FieldActorID, v))
}

// ActorIDIsNil applies the IsNil predicate on the "actor_id" field.
func ActorIDIsNil() predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldIsNull(FieldActorID))
}

// ActorIDNotNil applies the NotNil predicate on the "actor_id" field.
func ActorIDNotNil() predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldNotNull(FieldActorID))
}

// ActorTypeEQ applies the EQ predicate on the "actor_type" field.
func ActorTypeEQ(v string) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldEQ(FieldActorType, v))
}

// ActorTypeNEQ applies the NEQ predicate on the "actor_type" field.
func ActorTypeNEQ(v string) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldNEQ(FieldActorType, v))
}

// ActorTypeIn applies the In predicate on the "actor_type" field.
func ActorTypeIn(vs ...string) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldIn(FieldActorType, vs...))
}

// ActorTypeNotIn applies the NotIn predicate on the "actor_type" field.
func ActorTypeNotIn(vs ...string) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldNotIn(FieldActorType, vs...))
}

// ActorTypeGT applies the GT predicate on the "actor_type" field.
func ActorTypeGT(v string) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldGT(FieldActorType, v))
}

// ActorTypeGTE applies the GTE predicate on the "actor_type" field.
func ActorTypeGTE(v string) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldGTE(FieldActorType, v))
}

// ActorTypeLT applies the LT predicate on the "actor_type" field.
func ActorTypeLT(v string) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldLT(FieldActorType, v))
}

// ActorTypeLTE applies the LTE predicate on the "actor_type" field.
func ActorTypeLTE(v string) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldLTE(FieldActorType, v))
}

// ActorTypeContains applies the Contains predicate on the "actor_type" field.
func ActorTypeContains(v string) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldContains(FieldActorType, v))
}

// ActorTypeHasPrefix applies the HasPrefix predicate on the "actor_type" field.
func ActorTypeHasPrefix(v string) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldHasPrefix(FieldActorType, v))
}

// ActorTypeHasSuffix applies the HasSuffix predicate on the "actor_type" field.
func ActorTypeHasSuffix(v string) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldHasSuffix(FieldActorType, v))
}

// ActorTypeIsNil applies the IsNil predicate on the "actor_type" field.
func ActorTypeIsNil() predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldIsNull(FieldActorType))
}

// ActorTypeNotNil applies the NotNil predicate on the "actor_type" field.
func ActorTypeNotNil() predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldNotNull(FieldActorType))
}

// ActorTypeEqualFold applies the EqualFold predicate on the "actor_type" field.
func ActorTypeEqualFold(v string) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldEqualFold(FieldActorType, v))
}

// ActorTypeContainsFold applies the ContainsFold predicate on the "actor_type" field.
func ActorTypeContainsFold(v string) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldContainsFold(FieldActorType, v))
}

// OccurredAtEQ applies the EQ predicate on the "occurred_at" field.
func OccurredAtEQ(v time.Time) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldEQ(FieldOccurredAt, v))
}

// OccurredAtNEQ applies the NEQ predicate on the "occurred_at" field.
func OccurredAtNEQ(v time.Time) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldNEQ(FieldOccurredAt, v))
}

// OccurredAtIn applies the In predicate on the "occurred_at" field.
func OccurredAtIn(vs ...time.Time) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldIn(FieldOccurredAt, vs...))
}

// OccurredAtNotIn applies the NotIn predicate on the "occurred_at" field.
func OccurredAtNotIn(vs ...time.Time) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldNotIn(FieldOccurredAt, vs...))
}

// OccurredAtGT applies the GT predicate on the "occurred_at" field.
func OccurredAtGT(v time.Time) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldGT(FieldOccurredAt, v))
}

// OccurredAtGTE applies the GTE predicate on the "occurred_at" field.
func OccurredAtGTE(v time.Time) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldGTE(FieldOccurredAt, v))
}

// OccurredAtLT applies the LT predicate on the "occurred_at" field.
func OccurredAtLT(v time.Time) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldLT(FieldOccurredAt, v))
}

// OccurredAtLTE applies the LTE predicate on the "occurred_at" field.
func OccurredAtLTE(v time.Time) predicate.TaskEvent {
	return predicate.TaskEvent(sql.FieldLTE(FieldOccurredAt, v))
}

// HasTask applies the HasEdge predicate on the "task" edge.
func HasTask() predicate.TaskEvent {
	return predicate.TaskEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TaskTable, TaskColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTaskWith applies the HasEdge predicate on the "task" edge with a given conditions (other predicates).
func HasTaskWith(preds ...predicate.Task) predicate.TaskEvent {
	return predicate.TaskEvent(func(s *sql.Selector) {
		step := newTaskStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TaskEvent) predicate.TaskEvent {
	return predicate.TaskEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TaskEvent) predicate.TaskEvent {
	return predicate.TaskEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TaskEvent) predicate.TaskEvent {
	return predicate.TaskEvent(sql.NotPredicates(p))
}
