// Code generated by ent, DO NOT EDIT.

package ridershift

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the ridershift type in the database.
	Label = "rider_shift"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldFleetMemberID holds the string denoting the fleet_member_id field in the database.
	FieldFleetMemberID = "fleet_member_id"
	// FieldShiftStart holds the string denoting the shift_start field in the database.
	FieldShiftStart = "shift_start"
	// FieldShiftEnd holds the string denoting the shift_end field in the database.
	FieldShiftEnd = "shift_end"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldZoneIds holds the string denoting the zone_ids field in the database.
	FieldZoneIds = "zone_ids"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the ridershift in the database.
	Table = "rider_shifts"
)

// Columns holds all SQL columns for ridershift fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldFleetMemberID,
	FieldShiftStart,
	FieldShiftEnd,
	FieldStatus,
	FieldZoneIds,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusScheduled is the default value of the Status enum.
const DefaultStatus = StatusScheduled

// Status values.
const (
	StatusScheduled Status = "scheduled"
	StatusActive    Status = "active"
	StatusCompleted Status = "completed"
	StatusCancelled Status = "cancelled"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusScheduled, StatusActive, StatusCompleted, StatusCancelled:
		return nil
	default:
		return fmt.Errorf("ridershift: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the RiderShift queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByFleetMemberID orders the results by the fleet_member_id field.
func ByFleetMemberID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFleetMemberID, opts...).ToFunc()
}

// ByShiftStart orders the results by the shift_start field.
func ByShiftStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldShiftStart, opts...).ToFunc()
}

// ByShiftEnd orders the results by the shift_end field.
func ByShiftEnd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldShiftEnd, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
